### ISSUE TITLE
edit function not working with elegantthemes theme divi

### ISSUE THREAD

**Issue by stefanclara** [Codeinwp/visualizer#100]
Hi, I am using the Divi Theme from elegantthemes and I added the visualizer plugin. All works fine on creating charts, but editing is not working at all. When I click the edit button it is showing up just a blank page.

BR
Stefan

**Comment by HardeepAsrani** [comment]
@stefanclara Can you try this and see if your console throws any errors? https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

If yes then screenshots will be appreciated. :)

**Comment by stefanclara** [comment]
@HardeepAsrani thx for the quick feedback. please find attached the error log from the console

![image](https://cloud.githubusercontent.com/assets/17905514/18540853/d59dcef2-7b21-11e6-89ec-a3844fbd8bb7.png)

**Comment by HardeepAsrani** [comment]
@Basilakis Did you check?

**Comment by Basilakis** [comment]
@HardeepAsrani Added my self as participant, so I can get notifications.
Now with console it is clear, I will give it a look today.

**Comment by stefanclara** [comment]
thanx for coming back @HardeepAsrani and welcome @Basilakis .

i disabled the the "avira browser guard" and the only error that is now left over ist the one you can see on the picture below. I was trying this on chrome, but the weird thing is, the edit screen on the visualizer is still just blank.

![image](https://cloud.githubusercontent.com/assets/17905514/18624530/c4d99644-7e48-11e6-949b-463b8852aaff.png)

**Comment by selul** [comment]
@Basilakis can you try to see if you can replicate

**Comment by Basilakis** [comment]
@selul Could not, for me it seems to be OK all the process.

**Comment by stefanclara** [comment]
@Basilakis, below i send you 2 images how it looks like. first the charts and second i clicked the edit button on 1 of them

![image](https://cloud.githubusercontent.com/assets/17905514/18741435/86c4ce1e-80af-11e6-9189-23b18f396528.png)

![image](https://cloud.githubusercontent.com/assets/17905514/18741442/913a748e-80af-11e6-83f4-53fa0b2f3a84.png)

**Comment by stefanclara** [comment]
any updates/news on this one guys?

**Comment by selul** [comment]
@stefanclara can you do a printscreen of the whole window from console  ? Im interested more in the right side

**Comment by stefanclara** [comment]
@selul ... sorry if I need to raise maybe a stupid question, but what do you mean with a "printscreen from console" ???

**Comment by selul** [comment]
similar with this one: 

https://cloud.githubusercontent.com/assets/17905514/18624530/c4d99644-7e48-11e6-949b-463b8852aaff.png 

the console is the place where the red message comes up. Im interested more in the right side of the screen

**Comment by stefanclara** [comment]
:) ... ok. I hope this is what you would like to see

![image](https://cloud.githubusercontent.com/assets/17905514/19317030/f02d33f6-90a3-11e6-8a39-aef29d36a8c1.png)

**Comment by selul** [comment]
Please do one when the errors occurs

**Comment by stefanclara** [comment]
there are no errors... sorry. not on the page by itselfes nor on the wordpress admin. see below

this is if i click on the "new" or "edit" button ... white screen and nothing in the console.

![image](https://cloud.githubusercontent.com/assets/17905514/19317365/15ca5d5e-90a5-11e6-8a15-fbacb0fae0f0.png)

... and this is on the website.

![image](https://cloud.githubusercontent.com/assets/17905514/19317433/4af9c708-90a5-11e6-827d-92c683bf092e.png)

**Comment by stefanclara** [comment]
Please help me to understand 1 thing. I have the "Visualizer" link on the "Media" menu-item. If I want to make a new chart, click the "new" button I am getting the white screen as you can see. If I click the mouse and move it on this white part of the screen I am getting the message to "Drop a file" here ... Is the correct?

**Comment by stefanclara** [comment]
below you can see what I mean. It is in german but it is saying "Provide files for the upload"

![image](https://cloud.githubusercontent.com/assets/17905514/19317768/6d7b183a-90a6-11e6-913e-132b88a0c473.png)

**Comment by stefanclara** [comment]
under the blue frame you can see the white window after clicking on the "new" button. to me it seems, that the window is having items on it, but they are not showing up...
