### ISSUE TITLE
Name the first option in Legend > Position Default

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/visualizer#1003]
In the Legend > Position, the user can select the first option, which does not have a name, it's just an empty place.
Its result is that the legend will be placed to the left. Wouldn't it be more clear to name it "Default" instead of leaving it empty?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/232741157-ba28d9f5-d9a1-45ea-8998-fdc12afa8889.png">

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina Applied your suggestion in this PR https://github.com/Codeinwp/visualizer/issues/1003, please check with the build zip.

**Comment by AndreeaCristinaRadacina** [comment]
Great job! It appears and works as expected.🚀 Thank you, @girishpanchal30!
