### ISSUE TITLE
Name the first option in Tooltip Default

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/visualizer#1006]
Hi there! 
Similar to this one - https://github.com/Codeinwp/visualizer/issues/1003, the first option in Tooltip is empty, but it acts like the second option (the tooltip appears when the user hovers over the chart). Maybe we can also name it as default?
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/86592992/232994444-000b03c4-1c23-42cd-81b1-508505bc917e.png">

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina Applied your suggestion in this PR https://github.com/Codeinwp/visualizer/pull/1009, please check with the build zip.

**Comment by AndreeaCristinaRadacina** [comment]
Perfect, @girishpanchal30! 🙌🏻
