### ISSUE TITLE
Compatibility issues with Canyon Partners theme

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/visualizer#1008]
### Description

A customer of Visualizer is using this theme, Canyon Partners and the charts are not rendered with it.

They said they were able to fix the issue by replacing the [render-facade.js](https://github.com/Codeinwp/visualizer/blob/master/js/render-facade.js) file of Visualizer with the same file from version 3.5.0 of the plugin.

### Step-by-step reproduction instructions

1. Download the Canyon Partners theme

[canyon-partners.zip](https://github.com/Codeinwp/visualizer/files/11270417/canyon-partners.zip)

2. Install and activate it
3. Create a bar chart and try to render it on a page with its shortcode -> it doesn't show and there is no error in the browser console
4. If you switch the theme to Neve, the chart is rendered correctly 

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2204059811/364460/

### Environment info

https://pastebin.com/3HvQgqcu

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

I've checked with my local and it seems working fine for me. Can you please share staging/test instance details here?
Ref: https://tinyurl.com/2cef6drr

Thanks

**Comment by stefan-cotitosu** [comment]
Sure, here it is:

http://feedzy.stefancoti.com/wp-admin/
stefan
Student1234

Does it help if I share the staging of the customer?

WordPress Login: https://rivercyndev8.wpengine.com/wp-login.php
Parrot Token: ti_parrot
Parrot Token: PdYpt*Wb!IGB%nwyc

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

I've checked with provided test site and found the issue is related to the theme, not a visualizer plugin.

Chart rendering is now working properly after I fixed the [fatal PHP error](https://tinyurl.com/25ev333n) in the header.php file.
Ref: https://tinyurl.com/24vpwfrc

Thanks

**Comment by stefan-cotitosu** [comment]
@girishpanchal30, thank you. Would it be possible to share the fix so the customer can get in touch with the theme developer?

Or at least for me to share the changes, as they are afraid to use the latest version of Visualizer because of this conflict.

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

> @girishpanchal30, thank you. Would it be possible to share the fix so the customer can get in touch with the theme developer?

Sure!, User can compare diff here - https://www.diffchecker.com/5EvBVjXj/

Thanks
