### ISSUE TITLE
axis color 

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#101]
https://wordpress.org/support/topic/wrong-text-color-on-x-and-y-axis/ 

can you have a look here

**Comment by contactashish13** [comment]
@selul i cannot replicate this issue. it loads the right color every time, even if I empty my cache.

**Comment by selul** [comment]
@UVLabs have you tried to replicate and is not working ?

**Comment by UVLabs** [comment]
@selul I will try
