### ISSUE TITLE
Clicking on Advanced Options breaks the block for newly created chart through wizard

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#1010]
### Description

Clicking on Advanced Options breaks the block for newly created chart through wizard

### Step-by-step reproduction instructions

1. Install Visualizer
2. Run through the wizard ( choose to create a draft page )
3. Go to edit that draft page
4. Click on the Visualizer chart block in that page
5. Click on Advanced Options => an error appears "This block has encountered an error and cannot be previewed."

This happens for the chart, unless you go to Visualizer > Chart Library > Edit chart > Settings tab and apply some change there ( For example, add a title )

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/wEEzhk

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

I've reviewed this issue and fixed it with this PR, please check and let me know if you have any issues.

Thanks
