### ISSUE TITLE
Inserting a Table chart in a post not working well

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#1012]
### Description

Inserting a Table chart in a post not working well

### Step-by-step reproduction instructions

1. Create a Table chart
2. Create a post and using the Visualizer Chart block, insert the previously created table chart
3. Click on Save
4. Click on Done => An error appears

I've tried on PHP 8.2 and 8.1

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/XUdcPH

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

I've reviewed this issue and fixed it with the attached PR, please check and do let me know if you have any issues.

Thanks
