### ISSUE TITLE
Console errors when inserting into a new page a newly created chart through wizard

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#1014]
### Description

Console errors when inserting into a new page a newly created chart through wizard

### Step-by-step reproduction instructions

1. Follow the onboarding wizard to create a chart (I've tested with Table and Pie )
2. Create a new page
3. In that new page, insert the previously created chart ( from the wizard ) using the Visualizer Chart block
4. Try to click on Save button => errors in the console

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1503" alt="Screenshot on 2023-04-26 at 10-34-15" src="https://user-images.githubusercontent.com/3266155/234503545-00020688-8fd7-422c-b8c9-aa0f5c6aa48f.png">
<img width="1498" alt="Screenshot on 2023-04-26 at 10-18-42" src="https://user-images.githubusercontent.com/3266155/234503554-434351b3-9635-43bb-bd07-47880f05a754.png">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

I've reviewed this issue and fixed it with existing open PR https://github.com/Codeinwp/visualizer/pull/1011, please check with the latest build zip

Thanks
