### ISSUE TITLE
Series Settings not correct for Bar chart in the page editor

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#1017]
### Description

The Series Settings options are not correct in the page editor ( unlike the Visualizer charts library ), for the Bar chart

### Step-by-step reproduction instructions

1. Create a default Bar chart
2. Try to edit that chart. Go to Settings > Series Settings => The correct series order is displayed ( Austria, Bulgaria, Denmark, Greece )
3. Create a new page and insert the previously created chart in it
4. from that page, try to edit the chart block and go to Series Settings => The series order is not correct causing issues when trying to edit the chart ( Year, Austria, Bulgaria, Denmark )

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/Udqq5r

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

I've reviewed this issue and fixed it in this PR https://github.com/Codeinwp/visualizer/issues/1017, please check and do let me know if you have any issues.

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 it's working well 👍
