### ISSUE TITLE
Charts library or adding a new chart isn't working with WP 5.1 or lower

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#1034]
### Description

The charts aren't loading and adding a new chart isn't working with WordPress 5.1 or a lower version https://vertis.d.pr/v/QW9sAX 
On wp.org the minimum WordPress version for Visualizer is [3.5](https://vertis.d.pr/i/PiwOm5) which is pretty old so i think we should change it to 5.2 where nothing seems to be broken

### Step-by-step reproduction instructions

1. Install Visualizer and create some charts
2. Switch to WordPress 5.1
3. Go to the charts library and check if the charts are loaded
4. Try to add a new chart

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/QW9sAX 

### Environment info

Wordpress 5.1 or lower / Visualizer 3.10.3 / PHP 7.0

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Updated. Thanks @irinelenache
