### ISSUE TITLE
export not working

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#104]
An user reported that the export is not working well, filling the csv file with `Array `strings 

[varejo-graf4-3_PIB-brasil.zip](https://github.com/Codeinwp/visualizer/files/511389/varejo-graf4-3_PIB-brasil.zip)

here you have the sample he attached

**Comment by contactashish13** [comment]
@selul Can you provide more information on this? It works on my end.

**Comment by selul** [comment]
i've sent you on upwork

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/106
