### ISSUE TITLE
Charts not responsive on smaller screen sizes

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/visualizer#1049]
### What problem does this address?

Based on Rohan's message, it's very important for the Charts to be responsive for the smaller screen sizes. There are many instances where he has provided the CSS to add a horizontal scroll in order to make the chart properly visible and not cut off.

Reference:
https://secure.helpscout.net/conversation/2368782956/386474?folderId=212385
https://secure.helpscout.net/conversation/2392310533/389351/

### What is your proposed solution?

Introduce the code by default in order to make the charts responsive without using the Horizontal scroll method so the charts can have a landscape layout on desktops and a portrait layout on Mobiles.

### Will this feature require documentation? (Optional)

No.

**Comment by RohanSharma2598** [comment]
https://secure.helpscout.net/conversation/2418972316/392600/

**Comment by vytisbulkevicius** [comment]
@girishpanchal30, let's see what we can do here. Not a priority, but when you have time let's review what options we have.
I think it can be a simple solution to make it better with some CSS based on the screensize or a clean but more complicated way to redraw charts when the screen is resized.

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/visualizer/pull/1057, Please check with the attached zip when you have a moment.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and everything's fine on my end 👍 

@AndreeaCristinaRadacina Let me know if you can also confirm the desired behaviour 🙏

**Comment by AndreeaCristinaRadacina** [comment]
Looks fine now! Thank you!
