### ISSUE TITLE
Margin fields doesn't save values

### ISSUE THREAD

**Issue by pbworksro** [Codeinwp/visualizer#105]
To see the issue, please follow next steps:
1) Edit a chart
2) Click Next
3) Select Advanced -> Layout & Chart Area -> Chart Area
4) Set any margin field from Left And Top Margins (http://prntscr.com/cqh9lv)
5) And then Save Chart
6) Go back and edit same chart
7) In the Chart Area location, you will see that margin field not saved the previous value (http://prntscr.com/cqhakk)

**Comment by contactashish13** [comment]
@pbworksro @selul I dont think this is a bug, more a misunderstanding.

when you provide 0, it is not shown in the text box. if you provide any non zero value it is shown. in either case, the value is saved and used.

please test this by using 5% and 20% or any non zero values. you will see what I mean.

**Comment by selul** [comment]
@contactashish13 but how the users will be able to use zero margin there ?

**Comment by contactashish13** [comment]
I don't get what you mean.

**Comment by selul** [comment]
if the user want to have 0 margin, how can he accomplish this ?

**Comment by contactashish13** [comment]
I didn't say he cant. I said that if he provides zero, it will be used. But it will not be displayed in the text box.

**Comment by contactashish13** [comment]
@selul infact if the user leaves the margin as 0px or 0% it stays. 

![image](https://cloud.githubusercontent.com/assets/12953439/19189712/1952d8f8-8cb7-11e6-8a3a-549f25a17b86.png)

**Comment by pbworksro** [comment]
@contactashish13 Please take a look https://drive.google.com/file/d/0B7SHyn5Ns9GUUmdJOGZEd0R3NGc/view?usp=drivesdk

**Comment by pbworksro** [comment]
​I verified and found that if one of margin's value is not preceded by the percent symbol, this cause the issue. Margin fields must accept values without percent symbol.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/106
