### ISSUE TITLE
Clicking on Advanced Options breaks the block

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/visualizer#1051]
### Description

This issue is happening again, in the **3.10.4** version.
The original issue >> https://github.com/Codeinwp/visualizer/issues/1010

![image](https://github.com/Codeinwp/visualizer/assets/52494172/a389c646-1501-43de-81d1-4c54c2754f05)

### Step-by-step reproduction instructions

1. Create a clean instance with Neve and Visualizer 3.10.4
2. Import a chart from the Onboarding
3. Open the editor with that chart
4. Select the chart and click on the Advanced Options tab

### Screenshots, screen recording, code snippet or Help Scout ticket

https://github.com/Codeinwp/visualizer/assets/52494172/1dfe8638-09e3-41df-8244-fb8bdb4fa95b

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@girishpanchal30 I can still replicate the issue with the PR, you can check here:

```
 Admin area URL: https://onboarding-vis.s4-tastewp.com/?page_id=7
 Username: irinel 
 Password: TzzfL2bzfqg 
```

**Comment by girishpanchal30** [comment]
@irinelenache Fixed with the latest commit, please check with the latest build zip.

**Comment by irinelenache** [comment]
@girishpanchal30 Now everything works fine, thank you 👍
