### ISSUE TITLE
Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by jrandyanderson** [Codeinwp/visualizer#1054]
### Description

Upon upgrading to PHP 8.1, I received this PHP Deprecation notice while visiting the customizer page:

`[11-Nov-2023 06:07:52 UTC] PHP Deprecated: Automatic conversion of false to array is deprecated in /dom43717/wp-content/plugins/visualizer/classes/Visualizer/Source/Query/Params.php on line 326`

### Step-by-step reproduction instructions

1. Go to WP Admin
2. Go to Customizer

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've removed the deprecated functions from a plugin, and I believe they are not required now.
Ref: https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the issue is fixed by the PR 👍
