### ISSUE TITLE
Preview button on wordpress.org

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#1071]
### What problem does this address?

Let's try to add Live Preview button (Playground) for Visualizer plugin - 

https://meta.trac.wordpress.org/ticket/7251#comment:77
https://gist.github.com/soderlind/9bfce2ba83215125f92994f97b5c1702

Example of plugin that has it already - https://wordpress.org/plugins/jobbnorge-block/

### Will this feature require documentation? (Optional)

None

**Comment by Soare-Robert-Daniel** [comment]
@vytisbulkevicius Here is a demo you can test for the preview: https://jsfiddle.net/c132gptw/

This will set up the visualizer plugin and redirect you to the plugin dashboard, where you have the onboarding process. 

However, we need help with the onboarding after step 2. At step 3, a page refresh is done, which resets the onboarding step; thus, we are always stuck at step 3.

Video: 

https://github.com/Codeinwp/visualizer/assets/17597852/6e1d7fc8-ff47-4c76-ad45-73b7f1c0a3cf

We need to fix the onboarding process.
