### ISSUE TITLE
Chart not visible in SiteOrigin Accordion

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/visualizer#1075]
### Description

A user reported that the Visualizer Pie Chart is not visible in the accordion.

ref: https://wordpress.org/support/topic/pie-chart-front-end-not-showing-chart-on-page/#post-17399697

### Step-by-step reproduction instructions

1. Go to Visualizer and create a Pie chart
2. Copy the chart's shortcode
3. Install SiteOrigin Page builder and SiteOrigin Widgets Bundle
4. Go to Plugins > SiteOrigin Widgets and activate Accordion widget
5. Go to a page and insert Accordion widget from SiteOrigin
6. Inside one of the tabs, insert Visualizer shortcode
7. Update the page and check the changes

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1680" alt="image" src="https://github.com/Codeinwp/visualizer/assets/86592992/580acc3f-bd1c-4a44-8430-4b23432edd16">
<img width="1664" alt="image" src="https://github.com/Codeinwp/visualizer/assets/86592992/ff737597-a30d-486b-a9cf-23420accd191">

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

If you have everything set up can you quickly check if it works with this PR?
https://github.com/Codeinwp/visualizer/pull/1074

**Comment by AndreeaCristinaRadacina** [comment]
@vytisbulkevicius Yes, everything works well. 💡
