### ISSUE TITLE
Chart not showing on Safari Windows

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#110]
I used browser stack @selul seems to work on safari mac.

**Comment by selul** [comment]
@UVLabs can you tell me more details about what exactly is not working, maybe a screencast ?

**Comment by fadil-0786** [comment]
Hi, 

I am actually having an issue whereby the graph isn’t showing in safari browser. Other than that, everything works perfectly. I tested on another computer and i still got same issue

http://151.80.145.44/gamma.multimicro.fr/index.php/investor-relations/share-information-2/ 

In the console, the following error appears: 

TypeError: 'undefined' is not an object
render.js:17TypeError: 'undefined' is not an object (evaluating 'new gv.DataTable')
ReferenceError: Can't find variable: MutationObserver
notebook.pngFailed to load resource: the server responded with a status of 403 (Forbidden)
render.js:230ReferenceError: Can't find variable: MutationObserver
4render.js:17TypeError: 'undefined' is not an object (evaluating 'new gv.DataTable')


thank you

**Comment by fadil-0786** [comment]
apparently it does work on safari for mac as per @UVLabs . but on my end, for safari on windows, the graph doesnt show.

will gladly send you any details if needed!

thanks

**Comment by selul** [comment]
@contactashish13 can you please have a look ?

**Comment by contactashish13** [comment]
@selul safari for windows has been discontinued by apple for a few years now so I don't think any web component technology will work on that.

**Comment by fadil-0786** [comment]
@contactashish13 can you provide some details to support your explanation?

thank you.

**Comment by contactashish13** [comment]
@fadil-0786 https://discussions.apple.com/thread/7639618?start=0&tstart=0

**Comment by fadil-0786** [comment]
thank you very much @contactashish13 

i think we can therefore consider this ticket as closed.
