### ISSUE TITLE
css x-axis 

### ISSUE THREAD

**Issue by fadil-0786** [Codeinwp/visualizer#111]
Hi,

Can you please advise how to css my graph below:

http://151.80.145.44/gamma.multimicro.fr/index.php/investor-relations/share-information-2/ 

I would like to modify the x axis in order to put more spaces between the dates.

Thank you.

**Comment by fadil-0786** [comment]
any help on this issue please?

**Comment by selul** [comment]
@contactashish13 do you know any workaround here ?

**Comment by contactashish13** [comment]
@selul not really

**Comment by selul** [comment]
@fadil-0786 a workaround i see is to remove the sidebar from the page and make the chart bigger in width. this will make the space between dates bigger.

**Comment by fadil-0786** [comment]
no, sorry, removing the sidebar isnt an option as it is needed on this page to navigate to other subsection.

**Comment by contactashish13** [comment]
@fadil-0786 the other way is to swap the x and y axis if thats a possibility.

**Comment by fadil-0786** [comment]
no, cant swap as well @contactashish13 

but one thing a friend of mine tried to do is the following

$('svg g g text').each(function( index ) {
    if (index % 2 === 0) { $(this).hide(); }

    });

we tried to hide every second date from the x-axis

but sadly, this didnt work out.

maybe you guys will have a better luck!

**Comment by fadil-0786** [comment]
this piece of codes worked in chrome console, but not in the codes because i think the graph codes are loaded last, so my codes have no effect.

**Comment by fadil-0786** [comment]
hello,

any other idea please?

it would be nice if i get a quicker solution

thanks

**Comment by selul** [comment]
@fadil-0786 how did you added the code to the website?  can you try to do it again and i will check why is not working ?

**Comment by fadil-0786** [comment]
@selul code is in /var/www/gamma.multimicro.fr/wp-content/plugins/visualizer/js/render.js and also in theme main.js

**Comment by selul** [comment]
i've messaged you on support email in order to fix this out
