### ISSUE TITLE
check responsive issue

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#112]
@contactashish13 can you check this issue: 

> 
> Here's the path I take to get the charts to break in accordion:
> 
> 1. Open the Age-Based Aggressive accordion - charts show fine
> 2. Open the Age-Based Moderate accordion - charts show fine
> 3. Open the Age-Based Conservative accordion - charts show fine
> 4. Open the Age-Based Aggressive accordion again - charts are all shifted to the right and the width is larger than before.
> 
> When I look at the code, the charts are responsive so they have a dynamic width. That width is set correctly on the first opening of each accordion, but then not set on other times they are opened. It seems to be random, as I open the rest of the toggles the charts sometimes resize and sometimes don't. This site is much more obvious: https://test.brightdirections.com/investments/age-based/
>  
>

**Comment by contactashish13** [comment]
@selul can you send me the credentials for this site on upwork?

**Comment by contactashish13** [comment]
@selul fixed on the site. PR: https://github.com/Codeinwp/visualizer/pull/115

**Comment by selul** [comment]
@contactashish13 i see travis is failing, can you please check ?

**Comment by contactashish13** [comment]
@selul done
