### ISSUE TITLE
Create & publish animated icon for Visualizer

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#1125]
### What problem does this address?

To improve attraction to the plugin we can add animated icon as we tried for other products.

### Will this feature require documentation? (Optional)

None

**Comment by vytisbulkevicius** [comment]
![visualizer-logo](https://github.com/Codeinwp/visualizer/assets/36594177/646ae942-cab5-424f-ba03-a1ff394a1bd7)

This is the version to add.

**Comment by preda-bogdan** [comment]
This was updated.
