### ISSUE TITLE
Using Decimals and custom edits breaks vertical labels

### ISSUE THREAD

**Issue by kernicus** [Codeinwp/visualizer#113]
[Consomer Price Index percent change.zip](https://github.com/Codeinwp/visualizer/files/593050/Consomer.Price.Index.percent.change.zip)

Using the attached CSV file I created a standard line graph. The left side vertical labels appear ok until I go to advanced settings and make changes. Any ideas are appreciated. 

Thanks
Kernicus

**Comment by selul** [comment]
@contactashish13 can you have a look ?

**Comment by contactashish13** [comment]
@kernicus can you please mention what changes you made? A screenshot of the resulting graph or a URL to it would help.

**Comment by kernicus** [comment]
![screenshot 2016-11-17 14 36 49](https://cloud.githubusercontent.com/assets/1682754/20404576/6eea9990-acd3-11e6-8bf2-a46077ecee9c.png)

I think i just set the chart title perhaps but it seems to happen for anything I changed once in the advanced settings tab.

**Comment by contactashish13** [comment]
@kernicus under Vertical Axis Settings -> General Settings -> Number Format, if you specify #.# (hash dot hash), it should show the correct labels

**Comment by kernicus** [comment]
perfect. thanks.
