### ISSUE TITLE
import csv 500 error

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#114]
@contactashish13 when i try to import this csv to have on Y the time and on x the date i get a 500 error on the ajax request for uploading the csv . here you have a screencast to outline this: 

https://drive.google.com/file/d/0B8cbkQkB9Ybnc3BCdnNnZmdqVFk/view 

and here you have the csv attached  
[Example.txt](https://github.com/Codeinwp/visualizer/files/594463/Example.txt)

**Comment by contactashish13** [comment]
@selul it does not work because the timeofday does not specify the timezone so it should be 8:40:00+00:00 instead of 8:40:00 PM

**Comment by selul** [comment]
so if we edit the csv like this it should be fine no ?

**Comment by contactashish13** [comment]
the attached will work fine
[Example.txt](https://github.com/Codeinwp/visualizer/files/594563/Example.txt)

**Comment by selul** [comment]
great, thanks
