### ISSUE TITLE
Edit no longer available in the free version

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/visualizer#1151]
### Description

Users reported that they can no longer edit their charts after the update.

ref: https://secure.helpscout.net/conversation/2597422525/418824?viewId=931544

### Step-by-step reproduction instructions

1. Select the Visualizer in the left hand menu
2. Click the gear icon under that graph to edit/update.

### Screenshots, screen recording, code snippet or Help Scout ticket

![image](https://github.com/Codeinwp/visualizer/assets/86592992/a89e1083-2e7d-4fac-b838-e1e849d8ad45)

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/no-longer-edit-bar-charts/#post-17757595

**Comment by vytisbulkevicius** [comment]
I can't replicate this issue, @AndreeaCristinaRadacina were you able to replicate it?

Even if I create bar chart with the old version of the plugin, I update plugin then I can still edit the free chart.

@GrigoreMihai since you worked on this, do you know what could be the issue?

**Comment by GrigoreMihai** [comment]
@vytisbulkevicius I can not  replicate the issue either. Most likely he is using a pro chart type, but there is no reference of the chart he is using in the ticket. 

From the background of the provided image I think that he is using the column chart which is pro: https://vertis.d.pr/i/duA3cB. 

@AndreeaCristinaRadacina My suggestion would be to get more info from the user regarding the type of chart (and some print screens) he is using to be able to pinpoint an exact issue if there is one.

**Comment by AndreeaCristinaRadacina** [comment]
@vytisbulkevicius @GrigoreMihai I wasn't able to replicate it either, but after seeing multiple tickets on the same topic, I thought it would be better to share this with you.

Regarding the chart type, I am not sure if this should be the behavior, as we didn't mention anything about charts being removed from the free version for the existing users.

I asked the user for the information, I will keep you updated.

**Comment by AndreeaCristinaRadacina** [comment]
@GrigoreMihai, the user from wp.org mentioned he is using bar charts - 
<img width="961" alt="image" src="https://github.com/Codeinwp/visualizer/assets/86592992/cdf2b33c-53d9-4275-b6de-452ee418a117">

Please let me know if there's something else I should do to help.

**Comment by selul** [comment]
fmho it's normal to get multiple users reporting this since we did not had this before.

**Comment by vytisbulkevicius** [comment]
Yes, I think there can be cases where some users had pro charts installed somehow (maybe used pro version before) but if it's really a Bar chart as one user mentioned it shouldn't happen as Bar chart was free and we didn't change it. I see there are 2 users now that reached out about this even though "bar" chart was mentioned it looks like they had column chart in use from that image in the background and if that's true it's expected.

**Comment by AndreeaCristinaRadacina** [comment]
I clarified this with both users. They were using pro charts.
