### ISSUE TITLE
Update the plugin's page on wp.org

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/visualizer#1165]
A user rated Visualizer one-star because he saw multiple data entry options described for the free version, but only manual data was available.
<img width="1110" alt="image" src="https://github.com/Codeinwp/visualizer/assets/86592992/bbd89bd6-bc82-4f29-a649-4476c3649021">

**Comment by selul** [comment]
@harshitarora-in can you have a look to review this to have consistency?

**Comment by harshitarora-in** [comment]
Sure thing! I'll take a look and make the necessary updates.

**Comment by AndreeaCristinaRadacina** [comment]
Thank you, Harshit! @harshitarora-in

The content is updated now. However, I spotted some issues with the demo where charts are not visible:
- https://demo.themeisle.com/visualizer/polar-area-chart

And the like from the Bubble chart is the same as the link for the radar chart:
![image](https://github.com/user-attachments/assets/24aeeeca-e0cf-48a6-9c2c-c7911ef60422)

**Comment by harshitarora-in** [comment]
Fixed, Thank you!
