### ISSUE TITLE
Chats with percentages

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#117]
I tried creating this chart with the bar graph but wasn't able to:

![image](https://cloud.githubusercontent.com/assets/10324144/20652837/b66f62e4-b4d7-11e6-9347-d118d38f03e3.png)

See attachment for csv file, I tried changing it from "number" to "decimal" and "percentage" but it just reverted @selul 
[column.zip](https://github.com/Codeinwp/visualizer/files/615137/column.zip)

**Comment by selul** [comment]
@contactashish13 can you check ?

**Comment by contactashish13** [comment]
@UVLabs it works if you remove the % sign from each row.
