### ISSUE TITLE
Creating a second chart changes the first

### ISSUE THREAD

**Issue by Mara42** [Codeinwp/visualizer#1175]
### Description

If you already have one or more charts on a page and choose to add another, the last one will affect the others. For ex if you have a Pie chart, and right after you want to insert a Table chart, even before clicking save, the first one will be a Table chart too.

### Step-by-step reproduction instructions

1. Make sure to have Visualizer installed and start to create a chart (doesn't matter its type)
2. Save the chart
3. Add another chart right after but with a different type
4. Click create chart 

### Screenshots, screen recording, code snippet or Help Scout ticket

Create a chart and save it
<img width="858" alt="Screenshot 2024-07-26 at 11 22 35" src="https://github.com/user-attachments/assets/46f91445-4887-4ca7-947a-33dd8c7b4e2d">

Create a different chart
<img width="1612" alt="Screenshot 2024-07-26 at 11 22 54" src="https://github.com/user-attachments/assets/20836b6f-4780-44d8-aba7-21f7374b0b48">

Click create chart and watch how the first one also changes
<img width="889" alt="Screenshot 2024-07-26 at 11 23 06" src="https://github.com/user-attachments/assets/9117d68b-65dd-498e-8936-e6fd5dbc8539">

### Environment info

https://pastebin.com/81FJeCUs

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
@vytisbulkevicius this looks an important bug, are you able to replicate this?

**Comment by vytisbulkevicius** [comment]
Yes, I'm able to replicate this, important note that is not mentioned here is that this happens only when editing a page/post on Gutenberg editor and when creating charts directly from Gutenberg editor. It might be a problem introduced when we made changes and retired Gutenberg editor and only left an option to create charts from there.

Also, the chart created doesn't get actually deleted or changed, in the library it exists but on the post/page itself ID is changed.

We still need to fix this behavior of course just sharing some findings.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I've reviewed this issue and fixed it here https://github.com/Codeinwp/visualizer/pull/1178

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 it still happens when I add a new chart on the page. 

test
jKwDwTUfo*CNWn0GYidlLISw
https://snifffood.s4-tastewp.com/wp-admin/

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina It seems I missed the build JS, Please recheck with the latest build zip.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 I downloaded the zip again and tested it, but nothing has changed. Can you please check?

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've tested with fresh instance and it seems working fine for me.
Ref: https://tinyurl.com/287sfduv

You can check here:
https://pedalbird.s2-tastewp.com/wp-login.php
girish / hXRdJsAC3@N9jD5v#z^*fMql

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 I tested it, and it works on your instance. Thank you for sharing!
