### ISSUE TITLE
Issue with commas being used in numbers

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#118]
If the commas are being used in a spreadsheet then the visualizer is ignoring those values. With is fine with normal sheets but Google Spreadsheets add commas to the numbers automatically so it seems to be an issue. @selul

**Comment by selul** [comment]
@contactashish13 can you please check ?

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/121

**Comment by selul** [comment]
@contactashish13 travis is failing, please make sure is passing

**Comment by contactashish13** [comment]
Doesn't seem to be failing because of my changes.

**Comment by selul** [comment]
you are the only one who commited in your fork :D

**Comment by contactashish13** [comment]
The grunt screenshot doesn't tell the reason. Can you please double check?

**Comment by contactashish13** [comment]
@selul 
![image](https://cloud.githubusercontent.com/assets/12953439/21055280/d59c2052-be56-11e6-86e1-8fd1009e06e1.png)

**Comment by selul** [comment]
@contactashish13 strange, i have restarted the build and seems to work ok now.
