### ISSUE TITLE
Series Settings Issue

### ISSUE THREAD

**Issue by dshakya** [Codeinwp/visualizer#119]
I created a bar chart with about 6 series which I can stack up. But when I edit the series through - "Series settings",

- I can open the first series and edit properties such as colour and display

- I cannot open other series as it is wrapped under <a> tag and is linked to : http://icu-project.org/apiref/icu4c/classDecimalFormat.html#_details

- This prevents from assigning "open" class to "section-item" and hence is not editable.

Could you please provide a fix for this one?

**Comment by dshakya** [comment]
This is kind of solved without testing the side-effects for now. I commented out renderFormatField from _renderSeries function not being able to troubleshoot what the problem is as the first series seems OK but not the subsequent ones.


` protected function _renderSeries( $index ) {
		self::_renderSelectItem(
			esc_html__( 'Visible In Legend', 'visualizer' ),
			'series[' . $index . '][visibleInLegend]',
			isset( $this->series[ $index ]['visibleInLegend'] ) ? $this->series[ $index ]['visibleInLegend'] : '',
			array(
				''  => '',
				'0' => esc_html__( 'No', 'visualizer' ),
				'1' => esc_html__( 'Yes', 'visualizer' ),
			),
			esc_html__( 'Determines whether the series has to be presented in the legend or not.', 'visualizer' )
		);

		// $this->_renderFormatField( $index );

		self::_renderColorPickerItem(
			esc_html__( 'Color', 'visualizer' ),
			'series[' . $index . '][color]',
			isset( $this->series[ $index ]['color'] ) ? $this->series[ $index ]['color'] : null,
			null
		);
	}`

**Comment by selul** [comment]
@contactashish13 can you have a lok

**Comment by contactashish13** [comment]
@selul fixed this in the PR
