### ISSUE TITLE
remove footer banner

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#120]
@contactashish13 i would like to remove the footer banner with the pro info for the 3 more charts available in the visualizer modal and add the 3 images of the premium charts in the charts list but the images will be disabled and will redirect on click to the pro version version. Also you can add a specific css class to the disabled charts in order to style them lately.

**Comment by contactashish13** [comment]
@selul do you want the same functionality on the library page as well where the types of charts are listed? The chart types in the pro can be redirected to the pro url?

**Comment by selul** [comment]
Yes, please

Pe 9 dec. 2016 05:40, "contactashish13" <notifications@github.com> a scris:

**Comment by contactashish13** [comment]
@selul PRs: https://github.com/Codeinwp/visualizer/pull/121 and https://github.com/contactashish13/visualizer-pro/pull/1

**Comment by selul** [comment]
@contactashish13 i get this in the add media window: 

https://drive.google.com/a/vertistudio.com/file/d/0B8cbkQkB9YbnQ1FCYVkwWHctUzQ/view?usp=drivesdk

See the dropdown with objects strings

**Comment by selul** [comment]
@contactashish13 also with the code from visualizer repo, development branch, and with visualizer-pro, production branch, i get this: https://drive.google.com/a/vertistudio.com/file/d/0B8cbkQkB9YbnSzJXbzNyVnFEUW8/view?usp=drivesdk

**Comment by contactashish13** [comment]
@selul I never use the add media window so forgot about it. Have pushed changes in. PR: https://github.com/Codeinwp/visualizer/pull/122

There are changes in the pro as well so prod pro and dev free will not work.
