### ISSUE TITLE
Gauge: No way to format scale as percent

### ISSUE THREAD

**Issue by rgorski** [Codeinwp/visualizer#130]
When creating a gauge that indicates a percent, the min and max values need to be zero and one, but there is no way to format these as percent. This UX can be confusing to users.

For preference, updating the "Number Format" in General Settings to be a Percent would also cause the scale values to read as percent.

![screen shot 2017-01-31 at 5 09 21 pm](https://cloud.githubusercontent.com/assets/14044277/22486611/337f18dc-e7d8-11e6-902e-75a6938c203a.png)

**Comment by selul** [comment]
For the moment this is not on our priority list but we will postpone for later iterations. You can always hook to the plugin core and achieve this if you are interested
