### ISSUE TITLE
Font not inherited from body in IE11

### ISSUE THREAD

**Issue by dshakya** [Codeinwp/visualizer#131]
Hi,

I left the default font field blank as I am using Google font for my site. As a result, there is a in-line style of font-family="". This is not a problem with Chrome and Firefox and displays the font inherited from body.

But in IE, it doesn't and displays the default font of the browser making it look ugly. Is there a way to work around it and set the font style only if it has been selected in the Advance settings? This seem to solve the problem when there is no in-line style.

**Comment by selul** [comment]
@dshakya for the moment isn't too much traction for this feature to develop in the next iteration.
I think you can achieve this by hooking to the plugin core and do this.
