### ISSUE TITLE
test import from url

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#141]
@contactashish13 as with the new layout changes, please test the Import from url -> one time is working properly. 

This will behave like the previously import from web feature.

also, please make a phpunit test for this scenario.

**Comment by contactashish13** [comment]
@selul I'm trying to get the latest changes and I get many conflicts. I havent changed anything at my end

Auto-merging languages/visualizer.pot
CONFLICT (content): Merge conflict in languages/visualizer.pot
Auto-merging js/render.js
CONFLICT (content): Merge conflict in js/render.js
Auto-merging css/frame.css
CONFLICT (content): Merge conflict in css/frame.css
Auto-merging classes/Visualizer/Render/Page/Data.php
CONFLICT (content): Merge conflict in classes/Visualizer/Render/Page/Data.php
Automatic merge failed; fix conflicts and then commit the result.

**Comment by selul** [comment]
@contactashish13 you can try now, if is still not working, you can delete the fork and clone again.

**Comment by contactashish13** [comment]
@selul I had to fork the clone again. And actually nothing is working. The previous made charts do not load and a new chart cannot be created because it never renders. I see the code I had fixed for the bug on http://www.bluestonecm.com/wp-admin/upload.php?page=visualizer has been merged incorrectly also. Looks like this will be a major release :)

**Comment by selul** [comment]
@contactashish13 strange thing, can you please check what issue could be ?

**Comment by contactashish13** [comment]
@selul looks like something is very wrong with js/render.js https://github.com/Codeinwp/visualizer/commit/db490458e3c45fc76a7442bff8df7ca8835f3c9e#diff-05aaf1f7b3e768c9abe28e85f5fe955b. If I replace it with the previous version, everything works perfectly. I'm sure render.js would not need any changes for the new UI but can you confirm?

**Comment by selul** [comment]
yes, you are right, it wont, we can use the good version then.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/144

**Comment by selul** [comment]
@contactashish13 the build is failing.

**Comment by contactashish13** [comment]
@selul that is because it needs a valid URL to upload the file from. I'm using localhost from my dev instance  and that obviously does not exist for the build. I cannot use the dynamic WP instance because WP_TESTS_DOMAIN points to example.org and the file upload fails from there

**Comment by selul** [comment]
@contactashish13 let's use a file resource,i.e the sample.csv and load it using server path not url.

also, dont we have any helper method or class to create chart without using raw wordpress functions ? I would like to use as much as possible the methods from visualizer and not rebuild us the logic inside the test class

**Comment by contactashish13** [comment]
@selul this is testing for file upload then not for url upload

> let's use a file resource,i.e the sample.csv and load it using server path not url.

**Comment by selul** [comment]
@contactashish13 yes i know, but if you have any other suggestion we can try. i dont know if this can help but if you want to give it a try you are welcome: 

https://docs.travis-ci.com/user/hosts

**Comment by contactashish13** [comment]
@selul i'm marking this test as skipped till we can find a solution

**Comment by selul** [comment]
@contactashish13 please use abspath until we find a solution for this. also you have not answered regarding the test questions, cant we use some helper methods/functions to create chart. The current solution is not too elegant

**Comment by contactashish13** [comment]
@selul I've added the test case for import file. We can use that till we find a solution. In that I've also used visualizer methods for creating the chart

**Comment by selul** [comment]
@contactashish13 i see the tests are still falling

**Comment by contactashish13** [comment]
@selul its fine now. I don't run travis so I can only check once I've issued a PR. Will take care to make sure the build succeeds before letting you know :)

**Comment by selul** [comment]
@contactashish13 yes, would be perfect, thanks :D

**Comment by selul** [comment]
@contactashish13 here is a mirror of the repo:

**Comment by selul** [comment]
@contactashish13 using a fresh wordpress i get a blank popup when adding a new chart. can you check ? 

I'm using the current development version and latest wp
