### ISSUE TITLE
Unable to edit a chart

### ISSUE THREAD

**Issue by bigneilc** [Codeinwp/visualizer#149]
Hi, I've created some charts ok but when trying to edit them from the library the popup page is blank. The archive indicates this might be a conflict with another plugin but I don't know how to identify this. Any ideas? Great plugin by the way. 

Thanks.

**Comment by selul** [comment]
@bigneilc you can disable one by one each of your plugin until you find the problematic one.

If this does not work, you can try to revert to the default theme.
