### ISSUE TITLE
Update copyright year.

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/visualizer#163]
As a customer pointed out here: https://secure.helpscout.net/conversation/353187450/131130/?folderId=212390

We should update the copyright year.

**Comment by contactashish13** [comment]
@selul should I make this dynamic and default to the current year?

**Comment by selul** [comment]
yep.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/194

have removed closures as well

don't know why wraith is failing in the build
