### ISSUE TITLE
add maps key setting in the geomap type

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#174]
@contactashish13 let's add the Google Maps API settings for geomap data type in order to prevent this error from triggering: 

`"Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascri`

**Comment by contactashish13** [comment]
@selul I don't seem to get the error in the console (on both admin and front end) so I'm not sure how to test this.

**Comment by selul** [comment]
@contactashish13 i remember you fixed something on user end. this is the ticket: 
https://secure.helpscout.net/conversation/323649523/126383/?folderId=212390

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/175

I can't replicate the error on my localhost or on the sandbox but I've tested with console logging. Can you please verify?
