### ISSUE TITLE
Add Value to datapoint

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#177]
Currently, you can only view data of a data point when you either hover, or click on the point, you can set that option in the general settings of the chart. There is however no way to have the datapoint value always shown for bar charts or line graphs, this is more common with bar charts

An example can be seen here where the value is shown at the tip of the bar: 

http://graficas.es/review-asus-strix-1080ti-oc/

**Comment by selul** [comment]
@UVLabs yes, this can be done from the Advanced Settings, focus datapoint setting.
