### ISSUE TITLE
Many debugging errors

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#178]
While I was testing with 4.8, discovered there are many debugging errors when you update the fields. @selul

**Comment by selul** [comment]
@contactashish13 can you have a look, test with wordpress 4.8 beta.

**Comment by contactashish13** [comment]
@HardeepAsrani can you please mention what kind of errors and where did you see these errors? Were these in the console or the error.log file? Could you attach a sample too?

**Comment by contactashish13** [comment]
@HardeepAsrani i'm testing with beta2 and got only one error. can you please mention more details as requested earlier?

**Comment by HardeepAsrani** [comment]
Not appearing now. Looks like it was related to the above commit. Once I cloned that branch it worked perfectly. Thanks!
