### ISSUE TITLE
issue with codeinwp blog

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#186]
@contactashish13 i have an issue with visualizer displaying charts inside the popup. 

On this page: 

https://www.codeinwp.com/blog/best-wordpress-hosting/

If you click avg. load time icon, you should see a popup with the visualizer chart inside, instea there is an empty div. 

Here you have a screencast which outline this: 

https://drive.google.com/file/d/0B8cbkQkB9YbnSExyMS12NWliOGs/view

Let me know if you manage to find out the issue.

**Comment by contactashish13** [comment]
@selul seems like the google visualizer scripts are not being loaded. Could be because of a JS error that occurs before the scripts load. Are you able to show charts on any other page or is this the behavior throughout the site?

**Comment by selul** [comment]
yes, on other pages is working ok, for instance here: https://www.codeinwp.com/blog/best-web-hosting-for-small-business/

**Comment by contactashish13** [comment]
@selul i don't see any graphs on https://www.codeinwp.com/blog/best-web-hosting-for-small-business/

**Comment by selul** [comment]
![image](https://user-images.githubusercontent.com/3330746/27785334-ef44067e-5fe5-11e7-8742-e999accece5c.png)

**Comment by contactashish13** [comment]
@selul Looks like the links to load the chart popup are no longer there on https://www.codeinwp.com/blog/best-wordpress-hosting/

**Comment by dascalescuro** [comment]
@contactashish13 the links and icons are back, it was an editing mistake.
please let me know if you can see them now.

**Comment by contactashish13** [comment]
@dascalescuro thanks, I can see them now.

@selul can you create a separate page for this where I could test? It could be a problem with the lightbox-type component that shows the pop up.

**Comment by selul** [comment]
Would be more usefull if i provide you admin acces, either sftp or wp
dashboard

Pe 3 iul. 2017 22:55, "contactashish13" <notifications@github.com> a scris:

**Comment by dascalescuro** [comment]
@contactashish13 are you able to test this? :)
please let me know if you need anything to troubleshoot the problem with the lightbox.
thanks

**Comment by contactashish13** [comment]
@dascalescuro I was waiting for @selul to give me admin access to the site to help with the troubleshooting. Can you please provide this access?

**Comment by selul** [comment]
@contactashish13 you can try ti_parrot with -=TKH76ql2B)!zyGi

**Comment by contactashish13** [comment]
@selul I'm not sure I understand how the chart icon appears because I don't see anything when I edit the post.

**Comment by selul** [comment]
@contactashish13 yes, this is done from an external service where we create the popup. 
 if you need sftp access let me know.

**Comment by contactashish13** [comment]
@selul sure, anything that would help me :)

**Comment by selul** [comment]
host: 104.197.69.102
user: codeinwpblog
password: jqRHhHwcIs7Fiud
port: 53855

**Comment by dascalescuro** [comment]
@selul @contactashish13 was this one solved or anything added?

I didn't update the plugin but while checking the issue I noticed that sometimes the visualiser shortcodes are loaded.

Please check the video: https://www.useloom.com/share/9306fb61397d4b7fa8be4a476e78d066

**Comment by contactashish13** [comment]
@dascalescuro this is indeed strange. I tried on IE as well as chrome and it did not work. @selul I accessed the SFTP but don't know what to look for :) can you please explain the process?

**Comment by selul** [comment]
@contactashish13 i dont know either. the wordpress instance is in the public folder, how about our assumption that the assets file are not loaded, are they or not ?

**Comment by selul** [comment]
@contactashish13 any luck ?

**Comment by contactashish13** [comment]
@selul i meant if you could explain how the chart icons appear even though there is nothing in the markup. I dont know where to start tracing this issue from.

**Comment by ineagu** [comment]
Hey, the chart icon is added like this : 

<a href="#" class="fa fa-line-chart manual-optin-trigger" style="color:black" data-optin-slug="glzh3evrh7bse9p7rvdz" aria-hidden="true"></a>

then optinmoster based on the slug, open the popup. Then in the popup we have this : https://www.dropbox.com/s/36mnu3cpmy6f97o/Screenshot%202017-07-19%2011.10.04.png?dl=0

**Comment by selul** [comment]
@contactashish13 why you have waited 5 days for a reply from my side when the last message from the conversation is mine ? 

If you have an issue and something blocks you moving further you need to clear this as soon as possible and not wait for me to ping you and see how is going. 

Let's avoid this kind of back and forth in the future please.

**Comment by contactashish13** [comment]
@selul it would help to have a conversation about this on slack

**Comment by selul** [comment]
@contactashish13 sure, ping me when you want to talk.
