### ISSUE TITLE
add actions buttons 

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#192]
@contactashish13 i would like to add a setting in the Advanced tab area, General settings, called Action buttons which will have 4 checkboxes ( Print, excel, csv, copy ).

When this will be enabled, we will show something like this.
![image](https://user-images.githubusercontent.com/3330746/29155055-e9e503d4-7da1-11e7-953c-8a1a452688a9.png)
 , which you can find here: https://wpdatatables.com/ 

The behavirour will be pretty much the same, but in our case, the print action will not print the cart, and will print the table with the values.

**Comment by selul** [comment]
@contactashish13 by default all checkboxes will be unchecked.

**Comment by contactashish13** [comment]
@selul the image you attached in the post seems to be missing. can you please attach again?

**Comment by selul** [comment]
@contactashish13 you can check now the message.

**Comment by contactashish13** [comment]
@selul 

* these checkboxes will be in the advanced settings tab for each chart?
* if so, checking the boxes will enable the links in the library?

**Comment by selul** [comment]
@contactashish13 the link will be displayed on the frontend, in the upper area of the chart, you can check in the website i gave you. 
And yes, those will be in advanced settings for each tab.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/195

**Comment by selul** [comment]
@contactashish13 in the admin area, when i click Create Chart i get this `Uncaught ReferenceError: Clipboard is not defined` in the console and the chart is not created.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/197

**Comment by selul** [comment]
@contactashish13 now i get this when i have all the actions buttons enabled: 

![image](https://user-images.githubusercontent.com/3330746/29313408-8fa32e6c-81c2-11e7-8052-63d543b232a3.png)

I think you have not added the js file as the vendor folder is ignored by git. 

Ignore the console log error as that is from the theme.
 
you can add the js in the js folder, make a vendor folder an put it there.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/198
