### ISSUE TITLE
Edit screen is blank

### ISSUE THREAD

**Issue by mhjp** [Codeinwp/visualizer#20]
Hi.. just loaded your plugin. Super easy to get going, much appreciated. The only issue I have is when I go into the Vizualizer library and click the edit icon at the bottom of any graph, a blank popup screen appears and nothing ever appears. Have tried it in 3 different browsers.

Thanks in advance for the help. Mike

**Comment by devonalex** [comment]
Yes i have the same problem.  I switched off all of my other plugins, but the problem remained

**Comment by sneike** [comment]
Michael, thank you so much for your trick!! It works and it is super useful! Finally I can edit my charts!
Thanks!
