### ISSUE TITLE
database import

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#217]
@contactashish13 i would like to work on a new feature for handling database import, similar as import from wordpress works, but a bit more SQL oriented. 

We will work first on the free version, next iteration will add features for pro version also. 

The intent is to dynamically build queries and display charts according to the result.
A raw mockup will be: https://xd.adobe.com/view/e87e95e6-1938-4ed7-85dc-6be25611a6dd 

Let's have a quick chat first and after i can setup the list of specifications.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/223

1. The UI needs lots of work by some CSS guru :)
2. The chart data is refreshed using the cron
3. I've created unit test for this but strangely its not working so I've skipped it for the time being

**Comment by selul** [comment]
@contactashish13 i dont get the 2nd point, isnt the data fetched live from the db ?

**Comment by selul** [comment]
@abaicus can you play around with this feature, see how is looking and do some magic with design ( improve )  ?

**Comment by abaicus** [comment]
👍 Sure!

**Comment by selul** [comment]
@contactashish13 can you reply to my last question ?

**Comment by contactashish13** [comment]
@selul no, to reduce the load on the db I've added the ability for users to specify a refresh time and on the basis of that the data is refreshed. Do you want me to add another option for 0 hours that will fetch data live?

**Comment by selul** [comment]
yes, if you could apply a wordpress filter to that value and the default to be zero.

**Comment by contactashish13** [comment]
@selul have added an option for this.

**Comment by selul** [comment]
@rohittm can you help me test this feature, you can find this on the database-support branch. 

Let me know what you have tested, how the things were working and what problems did you encounter.

You can make a doc to gathering all the data.

**Comment by rohittm** [comment]
@selul here's the report of what I tested: https://docs.google.com/document/d/1CdNChHm48PTWIgP-9mBKSq9RF1HCwT7pLzHz4aPjZGQ/edit?usp=sharing

**Comment by selul** [comment]
@contactashish13 can you have a look at the issues.

**Comment by contactashish13** [comment]
@rohittm can you please add in more details as to when you clicked the Save button or the Cancel button or when you clicked the what control/feature? The report does not make this obvious. It might be best to add another page to this report and in there list down step by step the actions you took and what was the problem.

**Comment by rohittm** [comment]
@contactashish13 I have updated the doc. Until step 10, everything works fine. The problem that I faced was from step 11. If there's still anything you aren't able to understand, let me know. I'll try explaining in details.

**Comment by contactashish13** [comment]
@rohittm I'm not sure your installation is working properly or using the correct version of plugin. It has been quite a few releases since we removed the "chart types" screen when you click on edit but your install seems to be showing that screen for some reason. 

Also, I don't see a Cancel button. The commit for that contained revision control as well. If you are saying revisions are being created, then for some strange reason I don't see the Cancel button. 

Looks like the plugin version you are using is outdated or something else is wrong. Please recreate the issue on poopy.life if you can.

**Comment by rohittm** [comment]
@contactashish13 Let's just forget the previous tests, and I did a fresh install in poopy.life as you suggested. Here, I took wp_posts table and wp_posts.ID and wp_posts.post_date columns for both the axis of chart.

Now, I find this error (and, in this video, I have stated all the steps, I did): 
https://drive.google.com/file/d/1upyg_6mhaGYdUbnGHUFf_fmfNT2r-G8t/view?usp=sharing

Also, what I tried talking about previously was this case:
https://drive.google.com/file/d/1CQ8NeYNIiuH4mR4z2TKirFvrUZOJts9y/view?usp=sharing

1. I created a new chart, with wp_posts table and wp_posts.ID and wp_posts.post_author as axis.
2. Saved the chart, and clicked on edit again. You can see the default chart showing up unless I click the **Import from database** option, and create query.

Let me know if there's something not understood in the above videos. Thanks.

**Comment by contactashish13** [comment]
@rohittm the problem was that date or string columns always need to be on the X axis. In this case, the post ID was on the x axis. This is similar to how import from WP works. The code was already taking care of automatically switching string type column to the x-axis but did not handle this switching for date columns.

Also, a "live" chart was not being fetched live in the library; it was being fetched like a cached chart. I've fixed that as well.

Please test using the PR: https://github.com/Codeinwp/visualizer/pull/258

cc @rodica-andronache

**Comment by rodica-andronache** [comment]
@contactashish13  I tested a bit too, and I can see the problem suggested by Rohit. after creating a new chart with the import from db, and try to edit it, it gets the default values, not the ones we saved. 
Plus, I don't understand how the db infos are pulled from the db.
these are the options I selected https://prnt.sc/jaeqru
this is what I got https://prnt.sc/jaer1r
with this chart https://prnt.sc/jaerni
this is after i tried editing it https://prnt.sc/jaes1x
and this is my db https://prnt.sc/jaet6d

@rohittm could you please also test this too? with more cases, like different tables, and all those conditions https://prnt.sc/jaeu82 and make sure everything is ok? Please write in a doc all the cases you tested.
😀

**Comment by contactashish13** [comment]
@rodica-andronache I was finally able to reproduce this bug and fix it.

@rohittm please test this as well.

**Comment by rohittm** [comment]
@contactashish13 I tested again what I tested [here](https://github.com/Codeinwp/visualizer/issues/217#issuecomment-383371172) and this is what I got according to the posts I made:
![screen shot 2018-05-18 at 21 52 53](https://user-images.githubusercontent.com/3204558/40246360-16b53e8e-5ae6-11e8-8a1e-aea71c304109.png)

@rodica-andronache I tested your case as well, and it seems to be working fine as well.

I tested few more cases with other conditions like:
![screen shot 2018-05-18 at 21 56 53](https://user-images.githubusercontent.com/3204558/40246466-7863475c-5ae6-11e8-9c32-e9f06e8fa0fc.png)
The results and the charts worked fine:
![screen shot 2018-05-18 at 21 57 42](https://user-images.githubusercontent.com/3204558/40246485-8d90a714-5ae6-11e8-8929-5e5f65eebb6b.png)
and like: 
![screen shot 2018-05-18 at 22 00 18](https://user-images.githubusercontent.com/3204558/40246575-e82b156a-5ae6-11e8-9a8d-6c35a6cf6aa8.png)
which produces:
![screen shot 2018-05-18 at 22 00 24](https://user-images.githubusercontent.com/3204558/40246621-06bee498-5ae7-11e8-9b1a-555770b585e6.png)

and many more minor cases, overall, I can't find any more bugs. Everything works fine for me 👍

**Comment by rodica-andronache** [comment]
@contactashish13 some things are not related exactly to this task but I have some questions :)
At first, when you install the plugin, go to the Visualizer Library, and you select a type of chart for e.g Gauge https://prnt.sc/jkcyj6 and after that, you click Add new, always the default selected chart type is Line https://prnt.sc/jkcz0x . Is that correct? I find it confusing.

What I tested, I added a pie chart, Import from database, and I selected the wp_posts table, with the ID and the author columns. The result I got is this https://prnt.sc/jkcxdb. Is it normat to have those duplicated rows? 

Plus, when I clicked to see the chart I got ' Pie chart should have a first column of type string ' https://prnt.sc/jkd0nh which is ok , but when I click on the Back button , there is just an empty box https://prnt.sc/jkd18d . Also, I think there is a small typo 'Pie chart should have **the** first column of type string'

I tested the same fields from the database, with a Line chart, and everything was ok until I clicked Create Chart, which didn't show any chart. Only after I refreshed the page, it showed the created chart.

**Comment by rodica-andronache** [comment]
@contactashish13 regarding the first thing, isn't it possible to do it? I mean, when you click on Add new, to make it as default value, what he has previously selected. I see it's in the URL maybe you can grab it from there? I think it would make sense. Let me know your thoughts :)

For the second thing, can't we remove the duplicates? I suppose that in the chart the duplicates are not used. Does it make sense or am I missing something? :D 

Thanks

**Comment by contactashish13** [comment]
@rodica-andronache first one can be done.

second one, I don't see the point. The query is going to be built by the user and if they want to remove duplicates then can add a group by clause.

**Comment by rodica-andronache** [comment]
@contactashish13 thanks for the fix for the first thing 👍 

for the second one, what I mean, is that I think there might be a problem with how the query is created. 
This is what I selected https://prnt.sc/jmefdh so, a single table, with 2 columns, ID and author .
This is the database https://prnt.sc/jmefpu and what I think it should be the result https://prnt.sc/jmefpu
And this is what it displays https://prnt.sc/jmeflk. ( every row is duplicated )
Let me know if it makes sense now.

For the Back button, I think we shouldn't remove it, as it's important. In my example, as a user, I wouldn't really know exactly what type of columns I need to select, and I might find myself in that situation where I get that error 'Pie chart should have a first column of type string. '
Clicking Back should bring me back to the previous screen, where I was selecting things in the db, so I can now try to select things based on the error I got.

The last thing, I can reproduce it anymore either

**Comment by rodica-andronache** [comment]
@contactashish13 you previously said "for the problem with the back button, I am able to replicate it." I tried now,but I see that you removed the back button?
If so, please bring it back :) the problem was that when that button was clicked it brought me to an empty screen, instead of the previous screen, where the query is constructed.

For the duplicated fields, we can leave it like that, if you say that's how it's supposed to work :)

**Comment by contactashish13** [comment]
@rodica-andronache which branch are you testing with?

**Comment by rodica-andronache** [comment]
@contactashish13 sorry, I missed this :) I tested with the database-support branch.
And I tested now, once more, and for example I now chose the wp_options table > option_name column, and I added a condition option_name to be equal to "theme_mods_zerif-pro"
and I got a bunch of results:
https://prnt.sc/kbrc64 https://prnt.sc/kbrcdv
I think all the options, don't think the Where clause was taken into consideration in the query.
Could you please check?

**Comment by contactashish13** [comment]
@rodica-andronache queries for tables that did not have a corresponding child table had a problem which I've fixed. I've tested with tables that have and do not have a relationship with a child table. PR: https://github.com/Codeinwp/visualizer/pull/285

**Comment by rodica-andronache** [comment]
@contactashish13 thanks, that's working fine now for me. Ionut also did a short test and here is his feedback https://docs.google.com/document/d/1CdNChHm48PTWIgP-9mBKSq9RF1HCwT7pLzHz4aPjZGQ/edit

**Comment by contactashish13** [comment]
@rodica-andronache does something more need to be done here?

**Comment by rodica-andronache** [comment]
@contactashish13 sorry, I forgot to mention :) For now, I couldn't find any more issues, but I honestly don't have many interesting scenarios that I can think of to test.
And we want to promote this feature after we add it in the plugin. For that, we would need some scenarios with charts examples, to showcase how useful this option is.
Could you please think of some ideas for this, and provide screenshots of how you've achieved the charts?
Some ideas examples: 
daily number of requests using pirate forms
pie chart with the top authors posting
daily pageviews using a plugin
but you can try to think to some more interesting/useful if you can 👍

**Comment by contactashish13** [comment]
@rodica-andronache I can think of many scenarios as below but have no active site with data to back it up or to create charts from. Maybe the themeisle blog page etc. has the data?

If WooCommerce is activated (I don't know if WooCommerce already has charts for these purposes):
- Number of products ordered per day
- Products ordered the most on a daily basis

Pirate forms
- Notifications per day, per form
- Notifications per form

WPPR
- Number of comments per review
- Highest to lowest rating of reviews

WP
- Comments per post
- Popularity of authors on the basis of comments per author

ROP (I don't think ROP updates the post with any stats but if that's in the pipeline then this can be useful)
- Post title vs. number of times it is shared on an account

**Comment by contactashish13** [comment]
@cosmin-serbanescu @abaicus could you please help?
