### ISSUE TITLE
chart from WP data UX

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#228]
@selul this was again very confusing and I thought is broken since I was trying to add stuff in the input, since the input doesn't work at all until I choose a CPT, I would recommend to either hide the input initially if there is no CPT selected, or to pre-select a CPT and add headers to selectors so people know what they can change into.

**Comment by ineagu** [comment]
https://www.dropbox.com/s/7ta1xsjhdf5u5o6/Screenshot%202018-02-19%2018.59.26.png?dl=0

**Comment by ineagu** [comment]
It was also impossible for me to understand how I can use it, so I think is better when users select that option to preload a useful use-case based on posts. seems that I cannot get post count based on status for e.g or again I don't understand how to use it.

**Comment by selul** [comment]
adding mock data by default sounds like a good plan.

**Comment by selul** [comment]
I moved it to the pro repo https://github.com/Codeinwp/visualizer-pro/issues/95
