### ISSUE TITLE
Add an Add chart button

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#229]
@selul what do you think about adding an add chart button in tiny mce, that will auto-open media dialog with charts pre-selected? like: https://www.dropbox.com/s/4lk40uvfwilqq8f/Screenshot%202018-02-19%2019.05.29.png?dl=0 .

Not sure if we do this now, but would be useful that when a user open this and there are no charts to direct him to the new chart tab : https://www.dropbox.com/s/z0kxr9x6zgrozim/Screenshot%202018-02-19%2019.07.56.png?dl=0 .

**Comment by selul** [comment]
@contactashish13 can we tackle this ?

**Comment by contactashish13** [comment]
@selul I'm not sure I understand the sequence of actions. Users can use the add media button to embed existing charts or create charts. Can you please clarify what is required?

**Comment by selul** [comment]
yes, but i would like to have a separate button in the editor for charts also, same as Feedzy does.

**Comment by contactashish13** [comment]
@selul 
1. will the tinymce button load the same window that the add media button does?
2. the add media button loads a window that has no "insert chart" button. will the tiny mce button also lack this button? if not, should the insert chart button be placed for both?

**Comment by selul** [comment]
1. yes
2. yep, will be ideal for both i think

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/234

1) The add media popup had bugs which caused pagination and chart type selection to not work. Have fixed these.
2) I have added a tinymce button that triggers a click of the add media button.
3) I'm unable to make changes to the backbone code so only the Visualizer tab shows.

**Comment by selul** [comment]
@contactashish13 i have managed to open the tab using: 

```
	                        frame = wp.media({
					frame:'post',
					state:'visualizer'
				});
				frame.open( );
```

All should be fine now.
