### ISSUE TITLE
Unable to perform any other option after clicking "Import from other chart" option

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/visualizer#230]
@selul @contactashish13 

Whenever clicking on "Import from other chart" option, The user is unable to click on any other ABOVE options. It can click on the options below it but now on the above ones. Here's the working: 
![visualizer](https://user-images.githubusercontent.com/3204558/36394905-6315da3a-15dc-11e8-8526-ca7e0425f170.gif)

Tested on Firefox, Chrome, and Safari. Is it only me?

**Comment by selul** [comment]
@contactashish13 can you check ?

**Comment by contactashish13** [comment]
@rohittm the GIF you have attached in issue seems to be incomplete. Can you mention the steps in text so that its easy to replicate?

Currently this does not seem to be a problem and could be specific to your instance.

**Comment by contactashish13** [comment]
@selul I have fixed this assuming "import from other charts" is a pro-only feature. PR: https://github.com/Codeinwp/visualizer/pull/231

@rohittm in the future, it will be more helpful if you can provide specific conditions to reproduce this issue e.g. it was not a geo chart specific issue and it only occurred when free was active and pro was inactive. These things will help reduce TAT.

**Comment by rohittm** [comment]
Sure @contactashish13 , I'll keep that in mind.

**Comment by selul** [comment]
@rohittm nice catch.
