### ISSUE TITLE
add insert button in media popup

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#236]
@contactashish13 will be ideal to have an insert chart button which will insert the shortcode code into the editor. 
Also, if we are doing this, we will need to tweak the listing charts into the media popup, allowing users to select them. 
The UI of how the selected chart will look will be similar to how the selected image is now in the WordPress media.

**Comment by selul** [comment]
@contactashish13 can't we localize using -> https://codex.wordpress.org/Function_Reference/wp_localize_script 
We can use the same handle as the js script you used to add the butotn.

**Comment by contactashish13** [comment]
@selul oh yes! For some reason I thought view.js was being included from backbone. Have implemented this.
