### ISSUE TITLE
Issue with non-English text

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#240]
Someone reported an issue with the Hebrew language in Charts. Google has some options to load locale in Charts, like this:

`google.charts.load('current', {packages: ['corechart'], language:'ja'});`

Now that should fix it in the front-end, but if you put down some text in Editor that we have, it also messes it.

@selul

**Comment by selul** [comment]
@contactashish13 can we use the blog locale for editor and charts frontend?

**Comment by contactashish13** [comment]
@selul partially solved in https://github.com/Codeinwp/visualizer/pull/244

PR for adding locale support to editor: https://github.com/Codeinwp/visualizer-pro/pull/101

I tried searching for publicly available CSVs in hewbrew but in vain. @HardeepAsrani can you share the file?

**Comment by contactashish13** [comment]
@selul have tested with the customer's Hebrew file but I'd recommend testing with as many different languages as possible. PR: https://github.com/Codeinwp/visualizer/pull/245

**Comment by contactashish13** [comment]
@rodica-andronache 

PR: https://github.com/Codeinwp/visualizer/pull/257

I'm reopening this so that this can be conclusively tested with different Unicode languages.

I'm attaching a file with as many languages as I could think of. More languages can be added and this can be used for testing.
[mix.txt](https://github.com/Codeinwp/visualizer/files/1934210/mix.txt)

CC @Vishakha-Patel @UVLabs

**Comment by rodica-andronache** [comment]
@rohittm  please test this, and post here a report of all the cases you tested and the results 😀

**Comment by rohittm** [comment]
@contactashish13 I'm unable to import CSV you provided. Here are the steps, I did (did that on both Local & poopy.life):

1. Created new WP instance.
2. Cloned [issue-240](https://github.com/contactashish13/visualizer/tree/issue-240) branch of your visualizer fork.
3. Created a new chart, and selected **Import data from file** option.
4. chose mix.csv, and it is not successful.

Here's the video: https://drive.google.com/file/d/17ojBtnkbvj3sTQMuUoX1mN4VnUwEDKwU/view?usp=sharing

Whereas, when I switch to 'master' branch, it seems to work. Here's the video: https://drive.google.com/file/d/1SF9OViXc74ksNIjWnMCdBzgbniq1IE3l/view?usp=sharing

**Comment by contactashish13** [comment]
@rohittm did you run composer?

**Comment by rohittm** [comment]
@contactashish13 So dumb of me, I missed that 😅. So yes, I tested the following:

1. The CSV data you provided [here](https://github.com/Codeinwp/visualizer/files/1934210/mix.txt) and all the data in col 1.
2. Changed headings in row 1 of CSV with non english text (all the languages used in csv).

Both the scenarios worked fine for me.
