### ISSUE TITLE
load frontend assets when not needed

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#241]
@contactashish13 @selul I can see we are still loading : <script type='text/javascript' src='https://themeisle.com/blog/wp-content/plugins/visualizer/js/lib/clipboardjs/clipboard.min.js?ver=3.0.6'></script>, even if there are no charts in the article.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/242

We may have to take a look at all plugins that support shortcodes as this behavior could be prevalent.
