### ISSUE TITLE
Add animations to chart

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/visualizer#251]
@selul We can add animations to the charts. Like the one's here: http://www.jqplot.com/examples/barLineAnimated.php . We can have something similar to this.

Ref.: https://secure.helpscout.net/conversation/555897475/158639/?folderId=212390

**Comment by marcosybarraa** [comment]
+1

**Comment by HardeepAsrani** [comment]
It's actually part of Google's Chart API: https://developers.google.com/chart/interactive/docs/animation

**Comment by rodica-andronache** [comment]
@contactashish13 I think this can be a nice pro feature 👍  what do you think? Could you please investigate this a bit? If it would make sense/can be implemented/how long it would take

**Comment by rodica-andronache** [comment]
yes, that sounds great 👍

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/visualizer/pull/274 and https://github.com/Codeinwp/visualizer-pro/pull/116

PS - I don't understand (and I am unable to fix) the travis build failure for pro.

**Comment by rodica-andronache** [comment]
@contactashish13 it fails because of the phpunit https://prnt.sc/k4gjf6, I guess from the change you've made. I don't know much about it, just wanted to show you that, in case you don't have access to see the travis results

**Comment by selul** [comment]
@contactashish13 i see the tests are failing with the latest PR -> http://prntscr.com/k4gn2i

**Comment by contactashish13** [comment]
@rodica-andronache I can see the travis results but they should not fail as they are passing on my instance. That's why I said I'm unable to fix them.

**Comment by selul** [comment]
@contactashish13 have you tested with the master version of the lite version and your fork version of the pro?

**Comment by contactashish13** [comment]
@selul thanks.

@rodica-andronache please merge my changes in https://github.com/Codeinwp/visualizer/pull/272/ as my commit in https://github.com/Codeinwp/visualizer/pull/272/commits/56af70ff56fbf7ce1ff9fe2b296e23974804ce5e will resolve the failing test cases.

**Comment by selul** [comment]
@contactashis13 wont this affect users with old lite and new pro ?

**Comment by contactashish13** [comment]
No, because the check for is_admin() to load the front end module only fails in the test cases. That check is anyways incorrect and the front end module should be loaded all the time or it will fail in ajax calls.

⁣
