### ISSUE TITLE
[Feature Request] Add Both % and Value to Pie Slice

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#252]
@contactashish13 it's possible to add just the percentage and just the value, we can maybe have another option to have both the percentage + the value in the chart

https://themeisle.com/index.php?gf-download=2018%2F04%2FScreen-Shot-2018-04-18-at-12.09.00.png&form-id=1&field-id=19&hash=542c4d2d125fca81dd8d253da1af34dcc1298a9c5c67ebd0b3e29076791b3ab9

**Comment by contactashish13** [comment]
@rodica-andronache @UVLabs PR: https://github.com/Codeinwp/visualizer/pull/256

**Comment by rodica-andronache** [comment]
@rohittm can you please add this feature in the documentation?

**Comment by rohittm** [comment]
@rodica-andronache Here it is: https://docs.themeisle.com/article/885-how-to-display-both-value-and-percentage-in-slice-of-pie-chart
