### ISSUE TITLE
Missing Docs and Screenshot fix

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/visualizer#254]
@rodica-andronache I am listing the missing docs and incorrect screenshots as per our conversation in [wp-product-review/#275](https://github.com/Codeinwp/wp-product-review/issues/275)

### Missing Docs:

- None

### Images with weird focused area.

- [x] https://docs.themeisle.com/article/597-create-chart
- [x] https://docs.themeisle.com/article/602-how-can-i-edit-a-chart
- [x] https://docs.themeisle.com/article/600-delete-chart
- [x] https://docs.themeisle.com/article/598-clone-chart
- [x] https://docs.themeisle.com/article/607-how-can-i-populate-data-from-google-spreadsheet

I'll be adding the correct screenshots, and revert back soon.

**Comment by rohittm** [comment]
@rodica-andronache check the screenshots on all the above docs and let me know if there is any thing that needs to be edited.

**Comment by rodica-andronache** [comment]
thank you @rohittm  😉
