### ISSUE TITLE
Data is being fetched from remote source every single time a chart is shown

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#255]
@rodica-andronache while testing https://secure.helpscout.net/conversation/558545011/158903?folderId=1362294 I seem to have found a major bug. It appears that whenever a chart is loaded, it repopulates data from its source - even if the source is a remote URL. This means that if I have a chart that loads from a remote URL **one time**, whenever I view the chart it is effectively fetching the data from the URL **repeatedly**. It is **not** changing the data in the database but fetching from the URL for every rendering of the chart.

I see similar behavior for scheduled import. 

@UVLabs can you confirm if you see the same behavior?

**Comment by rodica-andronache** [comment]
@contactashish13 indeed I think there is a problem, you can have a look.
What I have tested: Created a pie chart, imported new data with the One time import, and after that, I updated the file and indeed the chart is **updating again**. I suppose it should update just one time, as the name is saying.
If I updated the chart with the Manual Data option, it seems to not updating again from the remote file, so in that case, is ok.

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/visualizer/pull/261

**Comment by rodica-andronache** [comment]
@rohittm could you please test #261 with both the "One time import" and "Schedule import option" options? And make sure you test by changing the remote file.
Let me know how you tested this and what results you got? 😀

**Comment by rohittm** [comment]
@rodica-andronache @contactashish13 I tested by adding and updating the file: https://rohitmotwani.com/data.csv on poopy.life

Both "One time import" and "Schedule import option" options are working fine for me.
