### ISSUE TITLE
Hide few selected columns from CSV

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/visualizer#262]
@rodica-andronache There should be an option to hide few columns and not display them in the charts/tables without actually deleting it from the source CSV.

Here's the HS ticket: https://secure.helpscout.net/conversation/563950682/159444/?folderId=212390

**Comment by rodica-andronache** [comment]
@contactashish13 could you please take a look on this? Isn't this possible using the Manual Data option? Like creating the chart from the CSV and after that just edit the chart in the manual mode ( and remove any field you don't want from the csv ) ? Or I'm missing something?

**Comment by contactashish13** [comment]
@rodica-andronache yes, this is possible. I'm not sure why the user did not try that.
