### ISSUE TITLE
Provide the PNG URL of the rendered chart in the console

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#267]
ref https://secure.helpscout.net/conversation/599170994/163481

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/visualizer/pull/268

**Comment by rodica-andronache** [comment]
@contactashish13 I'm not sure about this. Neither that it's ok to have this always displayed in the console for each chart, nor that this is what she wanted. Could you please check with her, to see if that's what she really wanted? :)

**Comment by contactashish13** [comment]
She did not say no to my suggestion and shared the pirate details. I assume that's a yes.

**Comment by rodica-andronache** [comment]
@contactashish13 you can check again with her :) Not sure, we should add this in the plugin

**Comment by contactashish13** [comment]
@rodica-andronache have now added this in a global array which users can access if they wish to.

**Comment by rodica-andronache** [comment]
@contactashish13 I think it's better like this indeed ( let's also see if the user is also finding this helpful ).
But I tested this with some previously created charts and I got this: render.getImageURI is not a function https://prnt.sc/k1imd0

**Comment by contactashish13** [comment]
@rodica-andronache apparently not all charts support this method. Have added a warning for them.

**Comment by contactashish13** [comment]
@rodica-andronache have reopened this with https://github.com/Codeinwp/visualizer/pull/273
