### ISSUE TITLE
Shortcodes are not rendered in an Ajax callback

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/visualizer#286]
I tried with Hestia's new blog settings.
If you choose to display the whole content instead of the excerpt for each post on the blog and you enable infinite scroll feature if a post on the second page has a shortcode of the visualizer, that shortcode will not be rendered, it will be displayed just as plain text. 
I tested it with pirate forms shortcode and it works as expected so it's not a Hestia related issue.

**Comment by rodica-andronache** [comment]
@contactashish13 you can take a look at this. The problems are mentioned here https://github.com/Codeinwp/hestia-pro/issues/1507 
 https://prnt.sc/kbs3vb
And you can test with the development branch of hestia. In Hestia Pro, in customizer, we added a Blog settings panel, where you can find the options that Cristi mentioned

**Comment by contactashish13** [comment]
@rodica-andronache are the problems mentioned here: https://github.com/Codeinwp/hestia-pro/issues/1507#issue-320601368? 

@cristian-ungureanu can you please list down the exact steps to reproduce this issue?

**Comment by rodica-andronache** [comment]
@contactashish13 what you need to do is, create a table chart with visualizer and add the shortcode in a post. After that, get the development branch of Hestia Pro, and test on the blog page with the different layout options you can find in customizer > Blog settings

**Comment by contactashish13** [comment]
@rodica-andronache @cristian-ungureanu the instructions are not very clear as I have no background context of this. Here is what I understood and did and cuold not reproduce the problem:

- Create 2 charts, one pie and one table
- Add them to a post
- Activate dev branch of hestia pro
- Go to the post
- Customize the page using the customizer
- Change layout in blog settings to any of the 3 options

Can you please list down the exact steps clearly?

**Comment by contactashish13** [comment]
@cristian-ungureanu @rodica-andronache can we close this if this is no longer an issue?
