### ISSUE TITLE
TGMPA plugin shows misleading dependency

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#288]
![image](https://user-images.githubusercontent.com/12953439/43567025-18350e94-964e-11e8-9567-a52dee63419d.png)

@selul I think this is because of how we tend to "hijack" an existing TGMPA class to avoid a conflict. Do you think this behavior is correct?

CC @rodica-andronache

**Comment by selul** [comment]
@contactashish13 without the hijack is this working fine ?

**Comment by selul** [comment]
if this is caused by the hijack i think we can drop it and use it as tgmpa recommends. or at least have a fail-safe mechanism.

**Comment by contactashish13** [comment]
@DanyCaissy can you check if this is still relevant and if it is not, remove this?
