### ISSUE TITLE
Not enough columns given to draw the requested chart

### ISSUE THREAD

**Issue by csbeck** [Codeinwp/visualizer#29]
I'm getting this error when I attempt to create a new chart by linking to a Google spreadsheet.

I have a Google spreadsheet with the following:
2 columns and 6 rows
row 1 has: year, dollars
row 2 has: string, number
the next 4 rows show a year and a dollar amount

It appears that I created the spreadsheet as the directions specify. Can anyone explain why I'm getting this error?

Thanks! Chris

**Comment by ozonia** [comment]
Hi.
I have the same problem. 
Can you share a link to a spreadsheet that has the correct data format ?
Regards.

**Comment by csbeck** [comment]
I never got a response. I believe I dropped the functionality. I don't even remember what I was doing it for. Client probably dropped the requested functionality. So I'm really no help for you. Sorry!

**Comment by ozonia** [comment]
Hi csbeck!
Thanks for your reply.
Finally I chose to buy a premium plugin that works perfect (http://goo.gl/MGR0ZT) plus it's very cheap!
Regards.
