### ISSUE TITLE
date format not working

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/visualizer#291]
Added Date format to a column - http://prntscr.com/kejrfp.

But it is not showing the format in the front end:
![image](https://user-images.githubusercontent.com/29881234/43673833-e0e1893c-97e6-11e8-9494-aaee38fa2180.png)

The format is taken from - http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax.

Forum: https://wordpress.org/support/topic/datetime-format/#post-10557913

@selul @contactashish13

**Comment by contactashish13** [comment]
@Vishakha-Patel in such cases please provide the input data as well - CSV or whatever source.

**Comment by contactashish13** [comment]
@Vishakha-Patel please test with https://github.com/Codeinwp/visualizer/pull/287

**Comment by Vishakha-Patel** [comment]
@contactashish13 

It does not seem to be working for me. The code looks like this at my end for render.js:

![image](https://user-images.githubusercontent.com/29881234/43676320-6f7ddebe-980c-11e8-96ee-4a5b8a031391.png)

**Comment by contactashish13** [comment]
@Vishakha-Patel I tested with that PR and it seems to work pretty well. 

![image](https://user-images.githubusercontent.com/12953439/43677113-44c2ffc0-981a-11e8-925a-1e2b52d9dc89.png)

**Comment by Vishakha-Patel** [comment]
@contactashish13 

Yes, it worked after clearing cache and re-logging to the website.
