### ISSUE TITLE
Adding logo / images into charts.

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#303]
A client on HS was asking if his/her company logo can be inserted into charts.

Ticket link -> https://secure.helpscout.net/conversation/679760604/170885?folderId=212385.
Example -> http://prntscr.com/l3hmy3.

I'm thinking it would be a nice-to-have feature.

**Comment by contactashish13** [comment]
@SilviuDinu this can be done using JS as below. 

```
jQuery('.visualizer-front').append(jQuery('<div class="vim" style="position: absolute;width: 100px;height: 100px;bottom: 0;right: 0;"><img src="https://www.browser-watch.com/wp-content/themes/bluenews/images/logo.png"></div>')).css('position','relative');
```

Since this is not a core plugin feature, I guess we can put this on the back burner.

**Comment by ineagu** [comment]
good doc idea as well.

**Comment by SilviuDinu** [comment]
link to the guide -> https://docs.themeisle.com/article/953-adding-logo-image-into-charts
Thanks @contactashish13 @ineagu
