### ISSUE TITLE
Integrate https://www.datatables.net as new table type

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#307]
see tablepress, wpdatatable, https://barn2.co.uk/wordpress-plugins/woocommerce-product-table/

**Comment by contactashish13** [comment]
I'm thinking of using https://github.com/filamentgroup/tablesaw or https://github.com/fooplugins/FooTable and no longer use table charts as the options there are very limited.

Combining this issue with #306, we can start using one of the above frameworks for a new table chart type and deprecate google table charts in pro (eventually getting rid of them).

@selul let me know what you think.

**Comment by selul** [comment]
yes, seems interesting, maybe @HardeepAsrani knows some frameworks too. 
Also, might not be that urgent to change this, we can do this in phases, like first move to free the table chart and then change maybe the engine.

**Comment by contactashish13** [comment]
@selul yeah but my worry is that people would have created a table and then we will say oh its deprecated. They might not like that especially because it might not be easy to migrate from one engine to another. That is why I would prefer to introduce the free users to the new engine. What do you think?

**Comment by ineagu** [comment]
makes sense for me, we can see what engine tablepress is using as well

**Comment by ineagu** [comment]
seems like they are using this: https://www.datatables.net

**Comment by selul** [comment]
@contactashish13 yep, you're right.

**Comment by ineagu** [comment]
Idea for plugin 
name : Visualizer - Tables and Charts Manager for WordPress

**Comment by HardeepAsrani** [comment]
There’s also https://www.ag-grid.com/

Uriahs posted about it on Slack. We can also take a look here.

**Comment by HardeepAsrani** [comment]
It’s surely powerful: https://www.ag-grid.com/example.php

**Comment by contactashish13** [comment]
PRs: https://github.com/Codeinwp/visualizer-pro/pull/133 and https://github.com/Codeinwp/visualizer/pull/324

- This integrates with datatables. I chose that because we are already using it while showing results below the SQL Editor (#217) and it seems to be quite popular and lightweight.
- For want of a better name, I'm calling the new chart **Table (New)** and the old one **Table (Old)** or **Table (Deprecated)**. Alternative suggestions are welcome.
- Some options are there in free and advanced options are added in pro.
- Previously we were tied down to google API but now we can add any library.

@HardeepAsrani can you test this a bit when you get a chance?

**Comment by contactashish13** [comment]
@selul 

- in http://prntscr.com/lm304d the scrollbars are there because the table is not responsive by default and you have 6 columns. If you choose that option, the scrollbars will disappear.
- Media popup is not displaying the table. - can you explain this?

**Comment by selul** [comment]
1) Yes, I know about this, I was saying to add the overflow hidden to that grid cell in the listing page, for me is looking bad after I add that table chart. I know that on frontend is looking fine, i was saying about the admin listing. v
2) Add a post, go to the content editor, add media, chart is not present there.

**Comment by contactashish13** [comment]
@selul have addressed these issues.
