### ISSUE TITLE
import from json (use rest routes as import sources)

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#308]

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/389. This currently only supports JSON endpoints but can be extended to XML endpoints as well.

This is a demo of how it works: https://drive.google.com/file/d/1M6zjvzEerd_5QB66d_0ccqz3EROkt_J2/view

For some JSON endpoints such as `https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.json`, sometimes the first few elements of the relevant array might contain extraneous data that needs to be ignored. For that, the filter `visualizer_json_include_row` can be used to ignore such rows and only show rows with correct data.

@selul can you please share your feedback?

PS - the PR is failing because of WPCS which I will fix shortly.

**Comment by ineagu** [comment]
a usecase we wanted here is to have a chart for uptimerobot data for posts ( just so you have another example )

**Comment by contactashish13** [comment]
@ineagu @selul can you share a sample URL that I can test with?

**Comment by selul** [comment]
@contactashish13 i've added the details on slack

**Comment by contactashish13** [comment]
@selul @ineagu this is how it would look by using the filter provided in the implementation:

`
add_filter( 'visualizer_json_args', 'visualizer_json_args', 10, 2 );
function visualizer_json_args( $args, $url ) {
	if ( $url === 'https://api.uptimerobot.com/v2/getMonitors' ) {
		$args = array(
			'method' => 'POST',
			'headers' => array(
				'cache-control' => 'no-cache',
				'content-type' => 'application/x-www-form-urlencoded'
			),
			'body'	=> array(
				'api_key' => '',
				'format' => 'json',
				'logs' => '1'
			),
		);
	}
	return $args;
}
`

![image](https://user-images.githubusercontent.com/12953439/55793850-78108200-5ae1-11e9-85e8-0cca3c0fd4a4.png)

**Comment by selul** [comment]
@contactashish13 not very helpful this one, we need something where we can plot the response time, i.e http://prntscr.com/n9imgt for the individual monitor. 

Tweaking with filters the request is a good start, we can add doc for this as I think it will be many users who will want to use rest endpoints with Authentications mechanisms, headers and so on.   
Furthermore, we can link the doc in the area where they set up the endpoint in visualizer. 

What do you think?

**Comment by contactashish13** [comment]
@mileamadalin this is a major new feature that will be released as part of v3.2.0.  Here are some resources that will help you understand this feature:

- https://drive.google.com/file/d/1M6zjvzEerd_5QB66d_0ccqz3EROkt_J2/view
- https://docs.themeisle.com/article/1052-how-to-generate-charts-from-json-data-rest-endpoints
- https://docs.themeisle.com/article/1043-visualizer-how-to-extend-rest-endpoints-with-json-response

**Comment by mileamadalin** [comment]
@contactashish13 Thank you! I have shared those informations with the Support team

**Comment by ineagu** [comment]
@contactashish13 here I believe authentification is required by most of the services, requiring users to code for that seems too complicated, @selul thoughts?

**Comment by selul** [comment]
@ineagu I have no idea how we could cover a good amount the authentication mechanisms that most of the APIs uses. 

@contactashish13 maybe you can do some research on services like iftt, zapier that might abstract those things and see how we can have a slim version of this?
