### ISSUE TITLE
The link to the premium packages leads to 404 Not found page.

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#310]
When attempting to create a premium type of chart (table), clicking on it should open the Pricing page for the packages, instead it opens a Not found page.

The behaviour can be seen here -> https://share.vidyard.com/watch/aCB3nu6cqzjJ7uw2z1Pkbq

**Comment by contactashish13** [comment]
@selul the URL it opens now is http://themeisle.com/plugins/visualizer-charts-and-graphs-pro-addon/. Maybe a 301 redirect can be added to go to the right page?

**Comment by ineagu** [comment]
added 301
