### ISSUE TITLE
Axis Text Position is reversed

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#313]
In charts that have Horizontal/Vertical Axis Settings, the Text Position in **Horizontal/Vertical Axis Settings > General Settings > Text Position** are reversed. If you change Horizontal Axis, it changes Vertical, and vice-versa.

@contactashish13

**Comment by HardeepAsrani** [comment]
Same goes for Colors in that same section.

**Comment by HardeepAsrani** [comment]
Also:

Horizontal/Vertical Axis Settings > Grid Lines > Count are reversed.

**Comment by contactashish13** [comment]
@HardeepAsrani for https://github.com/Codeinwp/visualizer/issues/313#issuecomment-432402820, please check https://github.com/Codeinwp/visualizer/blob/master/js/render-google.js#L160

for https://github.com/Codeinwp/visualizer/issues/313#issuecomment-432423936, I don't see this problem. Can you share a video?

PS - this will be fixed as part of #312

**Comment by HardeepAsrani** [comment]
I’ve made a video but it won't explain much either.

Basically, Horizontal Grid Lines is a part of vAxis settings, while Vertical Grid Lines are a part of hAxis settings.

The lines are Horizontal but axis is Vertical, so it should be a part of Vertical Axis Settings.
