### ISSUE TITLE
loading improvements

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#315]
@contactashish13 @selul it seems to me that google charts loader is a bit in a hurry to load and it bringing a lot of js/css/requests over, can we have an option to delay/defer/lazy-load charts?

e.g : https://www.codeinwp.com/blog/best-wordpress-hosting/

**Comment by ineagu** [comment]
I am talking about those, seems like defer + async should help : https://www.dropbox.com/s/ohkpdhftx0tkhsd/Screenshot%202018-10-26%2021.52.18.png?dl=0

**Comment by contactashish13** [comment]
note to self: this can be done using `script_loader_tag`: https://matthewhorne.me/defer-async-wordpress-scripts/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/390
