### ISSUE TITLE
Sidebar messed up in Gauge chart

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#316]
The sidebar looks messed up in this chart only. Once you click on General Settings, other options show up.

<img width="1678" alt="screen shot 2018-10-25 at 1 41 11 am" src="https://user-images.githubusercontent.com/2649903/47458418-1be9c800-d7f7-11e8-811c-793922cfc761.png">

**Comment by contactashish13** [comment]
closing this as this has been mentioned in https://github.com/Codeinwp/visualizer/issues/312
