### ISSUE TITLE
Table Chart Issues

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#318]
Will post any issues I find with Table Chart here:

- We're using Pagination enable/disable option where we set boolean value in `pagination` property. This property isn't supported by the Table chart, according to Google Chart.

It supports `page` property that supports `enable`/`disable` values: https://developers.google.com/chart/interactive/docs/gallery/table

Can this be updated? If it's an issue with the version of API we're using then I can add some condition to do backward compatibility support, if not then can we update this?

@contactashish13 @selul

**Comment by contactashish13** [comment]
closing this as this chart type is now deprecated
