### ISSUE TITLE
Pie Chart Offset doesn't work

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#319]
Pie Chart has Offset and Color options in Slice Options, where Offset takes its value from the color field because the code: https://github.com/Codeinwp/visualizer/blob/413ccc353e22146d298c2b19aa0cb36ca112718e/classes/Visualizer/Render/Sidebar/Type/Pie.php#L189

It's a one line change, and I can include it in with Gutenberg, or maybe an earlier if @contactashish13 is planning on a release before that? :smile:

**Comment by contactashish13** [comment]
closing this and will solve as part of https://github.com/Codeinwp/visualizer/issues/312
