### ISSUE TITLE
How do I make my page have 4 graphs displayed as a 'dashboard'

### ISSUE THREAD

**Issue by ajr2183** [Codeinwp/visualizer#32]
This may be a super simple Wordpress oriented question, so I apologize if this is the wrong place to post this, but can anyone tell me how I adjust the placement of my graphs so that I can make the page look like a real dashboard?

For example, have 2 graphs side by side, above 2 additional graphs side by side?   I feel like this would be done by editing the html, but all I see when I add the graph is "[visualizer id="11"]".  How do I edit the placement of that?

VERY MUCH APPRECIATE ANY GUIDANCE HERE!

![dashboard example](https://cloud.githubusercontent.com/assets/11141455/6317018/872ce268-b9f2-11e4-8ed7-d265bf06b1e4.png)

**Comment by verosaka** [comment]
try encapsulating it in table fields

<table>
<tr><td>[visualizer id="11"]</td><td>[visualizer id="11"]</td><td>[visualizer
id="11"]</td></tr>
<tr><td>[visualizer id="11"]</td><td>[visualizer id="11"]</td><td>[visualizer
id="11"]</td></tr>
<tr><td>[visualizer id="11"]</td><td>[visualizer id="11"]</td><td>[visualizer
id="11"]</td></tr>
</table>

I hope this helps
ᐧ

On 21 February 2015 at 21:28, ajr2183 <notifications@github.com> wrote:

> This may be a super simple Wordpress oriented question, so I apologize if
> this is the wrong place to post this, but can anyone tell me how I adjust
> the placement of my graphs so that I can make the page look like a real
> dashboard?
>
> For example, have 2 graphs side by side, above 2 additional graphs side by
> side? I feel like this would be done by editing the html, but all I see
> when I add the graph is "[visualizer id="11"]". How do I edit the placement
> of that?
>
> VERY MUCH APPRECIATE ANY GUIDANCE HERE!
>
> [image: dashboard example]
> <https://cloud.githubusercontent.com/assets/11141455/6317018/872ce268-b9f2-11e4-8ed7-d265bf06b1e4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madpixelslabs/visualizer/issues/32>.
>



-- 
Rubén Sánchez.
Verosaka Representaciones, C.A.
RIF:J-29613291-7
www.canalexplorador.com
verosaka@gmail.com
Twitter: @verosaka
Linked In <http://ve.linkedin.com/pub/ruben-sanchez/4/131/807>
Of:(+58)212-576.3892
Cel:(+58)414-113.7093
Direccion: Av. Universidad,Centro Parque Carabobo, Nivel 1, Local 130.
La Candelaria./ Caracas 1060Ciudad: CaracasEstado: DCPais: Venezuela

NOTA CONFIDENCIAL: La información contenida en este E-mail es confidencial
y sólo puede ser utilizada por la persona o la compañía a la cual está
dirigido y/o por Verosaka Representaciones, C.A.. Si usted no es el
receptor autorizado, cualquier retención, difusión, distribución o copia de
este mensaje esta prohibida y será sancionada por la ley. Si por error
recibe este mensaje, favor reenviarlo y borrar el mensaje recibido
inmediatamente.
Gracias-
Sugerencias <http://lweb.es/publicidad/anuncio.php?tacos=10&tipo=angosto>
