### ISSUE TITLE
Decimals digits cut on Candlestick

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/visualizer#326]
@contactashish13 On Candlestick chart, we don't have these features http://prntscr.com/lj0igd 

https://www.dropbox.com/s/fla4hc710zkmk4z/Screenshot%202018-11-28%2014.48.31.png?dl=0 

I saw on wp.org that one of our customers asked for this. Do you think we should be included here as well?

**Comment by contactashish13** [comment]
@mileamadalin can you please add the wp.org link as well so that I can understand what exactly is required?

Both X and Y axes have formatting options available so I'm not sure what the user wants.

**Comment by mileamadalin** [comment]
@contactashish13 here is the link from the wp.org ticket: https://wordpress.org/support/topic/decimals-digits-cut/

**Comment by contactashish13** [comment]
@mileamadalin the link does not have any screenshots. Maybe support team should always ask for screen shots so that things are clearer. Please close this once you read this unless there is more clarity on this.
