### ISSUE TITLE
Doughnut chart

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/visualizer#327]
@contactashish13 We some suggestions to add doughnut chart on our plugin. 

![donut_chart](https://user-images.githubusercontent.com/6906834/49153849-9a1e1a80-f31f-11e8-8318-e7f0abff2641.png)

I like it and use it some time myself on docs, what do you think? Can be integrated in the future in Visualizer?

**Comment by contactashish13** [comment]
@mileamadalin donut is already part of visualizer. It is a pie chart with the value of `pieHole` > 0. https://developers.google.com/chart/interactive/docs/gallery/piechart#making-a-donut-chart

If you feel you need more options on the basis of the options Google supports, can you suggest them? Maybe we can add them as part of pro.

**Comment by mileamadalin** [comment]
@contactashish13 Thank you for clarifications. I have checked and is working pretty good; the only problem is that if the pie is too thin, the percentage cannot be seen. Please see the image attached: 

https://www.dropbox.com/s/y28mdcigf6cupiy/Screenshot%202019-01-30%2014.13.26.png?dl=0

And here is a short video: https://www.dropbox.com/s/k2q2jufrjsnw998/Screen%20Recording%202019-01-30%20at%202.15.22%20PM.mov?dl=0

I think the percentage should be displayed outside the chart after 0.7 (0.7 included)

Let me know if you need more details.

**Comment by contactashish13** [comment]
@mileamadalin that option is not available on https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options so the user will just have to reduce the piehole. please close this once you read this.
