### ISSUE TITLE
add new Table chart to Gutenberg

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#331]

**Comment by contactashish13** [comment]
@HardeepAsrani try to target this for 3.3.0

**Comment by HardeepAsrani** [comment]
@contactashish13 When are you planning to release 3.3.0?

**Comment by contactashish13** [comment]
mid to end of june. You can check the date on the milestone as well: https://github.com/Codeinwp/visualizer/milestone/11

**Comment by contactashish13** [comment]
released as part of 3.3.0
