### ISSUE TITLE
update screenshots

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#333]
@contactashish13 @sab2ina would be good to update those + add more screenshots, all the same size, even some with gutenberg : https://www.dropbox.com/s/ji01cnngofaxxop/Screenshot%202018-12-03%2010.11.48.png?dl=0

**Comment by sab2ina** [comment]
@dascalescuro can you help?

**Comment by dascalescuro** [comment]
sure, I just want to know if we are doing this across the product: product page, demo page, wp.org page, docs.

if yes, I can prepare the screenshots and implement them where needed, except for the docs where I would need help.

**Comment by sab2ina** [comment]
We can start with the ones of WP.org and then update the others as well.

**Comment by dascalescuro** [comment]
Let me know if these screenshots work for wp.org: https://drive.google.com/drive/folders/16qDQigWe3JJTT69tVsMTXBMSyh8NOshB?usp=sharing

**Comment by contactashish13** [comment]
@sab2ina are these screenshots for packaging into the plugin? 

@dascalescuro I don't seem to have access to them.

**Comment by sab2ina** [comment]
@contactashish13 yes, they should go in the _Screenshots_, under Description here https://wordpress.org/plugins/visualizer/

I shared the folder with you, let me know if you have access. We can add even more if some features are missing 👍

**Comment by contactashish13** [comment]
Can we add the following as well?

1. An image for the new table chart that can be used in the types selection popup (right now I'm using the same image as that for the Google table chart)

2. A screenshot of the new table chart

3. Screenshots for the pro features

**Comment by sab2ina** [comment]
@contactashish13 please feel free to add those as well, Claudiu is off for a parental holiday atm

**Comment by contactashish13** [comment]
@sab2ina 

> 1. An image for the new table chart that can be used in the types selection popup (right now I'm using the same image as that for the Google table chart)

I cannot update/create the sprite for this. We can wait till he gets back.

As for the other screenshots, are they just screenshots (Ctrl+PrtSc) or are they enhanced in some way?

Currently, I do not see any images for the pro features. Is it recommended to add those or should we restrict these to free features only?

**Comment by contactashish13** [comment]
@sab2ina can Claudiu address this if he is back? Also, I don't have access to wp.org to update the plugin's assets so this can be routed through @selul

**Comment by contactashish13** [comment]
@sab2ina can we close this if this has been done?

**Comment by sab2ina** [comment]
it's not done, as far as I see. 
Please create & upload the screenshots as you see fit.

**Comment by selul** [comment]
I suggest the next action plan: 

1. @SilviuDinu can prepare the screenshots with @contactashish13's guidance for each of the use cases. I suggested Silviu because he started to be more involved in Visualizer's support side. 
2. Once @contactashish13 you approve them, share the zip with me via Slack and I can upload them directly to wporg. 

@contactashish13 can you let me know if that's good to you and get in touch with @SilviuDinu to let him know about the details.

**Comment by contactashish13** [comment]
@selul sounds good. @SilviuDinu ping me on slack if you have any confusion about the use cases and we can discuss.

**Comment by SilviuDinu** [comment]
@contactashish13 sure, will get right to it and let you know as soon as I need help.

**Comment by contactashish13** [comment]
Closing this as this was done
