### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#335]
This comes when you view the plugin in Gutenberg:

`Warning: A non-numeric value encountered in /var/www/html/wp-content/plugins/visualizer/classes/Visualizer/Module/Admin.php on line 219`

Something related to: https://github.com/Codeinwp/visualizer/blob/33ee9a286b3623285160e341c8e14210d13e7cbe/classes/Visualizer/Module/Admin.php#L219

@contactashish13

**Comment by Vishakha-Patel** [comment]
+1
https://secure.helpscout.net/conversation/722953475/174985?folderId=212385

**Comment by contactashish13** [comment]
@Vishakha-Patel can you test with the new release 3.1.1?

**Comment by contactashish13** [comment]
@Vishakha-Patel does not happen with 3.1.1. If it does for you, please share a video.

**Comment by contactashish13** [comment]
I was able to reproduce this.
