### ISSUE TITLE
Adding New table chart is not working

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/visualizer#341]
User: "Hello. When i add new the table it now just spin's and will not open. This is happening only for that new chart. After i updated the plugin." 

Ticket: https://secure.helpscout.net/conversation/721721019/174851/

@contactashish13

**Comment by contactashish13** [comment]
@Vishakha-Patel have you checked with 3.1.1 as mentioned on Slack?

**Comment by Vishakha-Patel** [comment]
@contactashish13 is working now after 3.1.1.

Thanks.
