### ISSUE TITLE
Add links to documentation

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#352]
* link to https://docs.themeisle.com/article/728-manual-configuration

@Vishakha-Patel @HardeepAsrani can you mention any other documents that we can link to from within the plugin such as the above?

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/visualizer/pull/353

**Comment by Vishakha-Patel** [comment]
Maybe these three: 
https://docs.themeisle.com/article/773-how-to-change-colour-of-graphs-in-visualizer
https://docs.themeisle.com/article/774-how-to-change-width-and-height-of-a-chart-in-visualizer
https://docs.themeisle.com/article/607-how-can-i-populate-data-from-google-spreadsheet

**Comment by dascalescuro** [comment]
on the topic of links, @contactashish13 , I think this one is not working properly: 
![image](https://user-images.githubusercontent.com/12775984/50680130-34ecd180-100f-11e9-81eb-a08cdbc1aeab.png)

maybe we can send to the respective documentation: https://docs.themeisle.com/article/607-how-can-i-populate-data-from-google-spreadsheet
