### ISSUE TITLE
Fatal error with interaction with SSH SFTP

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/visualizer#354]
A user reported us that he had a PHP fatal error when he used our plugin Visualizer with SSH SFTP Updater plugin: https://wordpress.org/plugins/ssh-sftp-updater-support/ 

This bug was reported on their side as well, and they said that: visualizer calls the WP_Filesystem API wrongly, ignoring when error codes are returned, and instead of carrying on with operations that can’t work (and cause a crash).  You can find more details here: https://wordpress.org/support/topic/php-fatal-error-call-to-a-member-function-stat-on-a-non-object/ from what I saw they already tried to fix it, but didn't work and seems that the issue is from our side. 

Ticket link: https://wordpress.org/support/topic/fatal-error-with-interaction-with-ssh-sftp-updater-plugin/

**Comment by contactashish13** [comment]
@mileamadalin I am unable to reproduce this by using that plugin. I'm not getting any errors in my log file either. Please try to reproduce this bug at your end and share the steps.

**Comment by mileamadalin** [comment]
I will close that. I wasn't able to replicate it with the latest version of plugins and WordPress.
