### ISSUE TITLE
Scheduled import not working

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/visualizer#356]
Visualizer charts are not auto updating from Google spreadsheet changes.

Charts do update if I re-enter Google spdsht URL into One-time Import field But scheduled import not working. 

Ticket: https://secure.helpscout.net/conversation/739604519/176559?folderId=948378
https://secure.helpscout.net/conversation/739217466/176504?folderId=212385

cc: @contactashish13

**Comment by contactashish13** [comment]
@Vishakha-Patel have you been able to reproduce this on your dev instance?

**Comment by Vishakha-Patel** [comment]
@contactashish13 Yes. I tried to fetch a sheet and run cron multiple times to see if it updates the chart. But it does not. 

To double check, the same happened with Poonam's instance.

**Comment by contactashish13** [comment]
@Vishakha-Patel the customer clearly states 

> There is a new option called Scheduled Import under Import Data from URL that requires Business Version. Would this solve problem?

he is not using scheduled charts. How can this be a bug? :)

In the other ticket, I can't even login. Have you tried to log in and verify the customer's assertion?

cc @mileamadalin 

I have tried it on my local instance and it works perfectly. Please share a test instance (not the customer's) where you feel this is not happening. First we need to make sure we all are on the same page and concur on a bug.
