### ISSUE TITLE
Markers not visible when set to display mode in Geo map.

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/visualizer#359]
When setting the display mode the Geo Map to 'Markers' it would only display a blank map.
See here -->> https://prnt.sc/m7b1li
It works fine when set to auto or regional mode -->> https://prnt.sc/m7b232

Ticket: https://wordpress.org/support/topic/map-markers-not-showing-anymore/#post-11059333

**Comment by contactashish13** [comment]
@purplecodes please check the chrome console for any errors. If there is an error, please try to use another API key.

I have mentioned this before to the support team. CC @mileamadalin

**Comment by purplecodes** [comment]
@contactashish13 
Thanks, I have used @mileamadalin API key and it worked like how it should be.
https://prnt.sc/mbwbv0

**Comment by contactashish13** [comment]
@purplecodes I'm confused :) Is this still an issue or is this okay now?

**Comment by purplecodes** [comment]
All good now, thanks.
@contactashish13
