### ISSUE TITLE
Custom series format values for pie chart

### ISSUE THREAD

**Issue by WillNeill** [Codeinwp/visualizer#36]
Hi, 

Is it possible to implement the custom format pattern for series values on pie chart segments? At the moment, the values are simply raw data.

It would be good to provide options like Bar Charts:

"Enter custom format pattern to apply to this series value, similar to the ICU pattern set. Use something like #,### to get 1,234 as output, or $# to add dollar sign before digits. Pay attention that if you use #% percentage format then your values will be multiplied by 100."

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/193
