### ISSUE TITLE
Undefined index: id in \visualizer\classes\Visualizer\Gutenberg\Block.php on line 124

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#362]
@HardeepAsrani this error is seen in the logs by following these steps:

1. Have existing charts in a post
2. Use gutenberg to add a new visualizer block
3. click on display an existing chart
4. check logs

when the error is seen, the value of `$attr` is 
```
Array
(
    [route] => showCharts
)
```

**Comment by HardeepAsrani** [comment]
Worked just fine for me, wasn't able to reproduce this on the latest development branch. Can you send a video or something so I can make sure I'm doing it right? @contactashish13

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/366
