### ISSUE TITLE
HTML Code For Pie Chart

### ISSUE THREAD

**Issue by vlindsa** [Codeinwp/visualizer#37]
Hey,

I created a pie chart in WP with your plugin. It provides a shortcode to add to a page or post. But how can I get the actual HTML code so that I can add it to our Revolution Slider? Also, is there a way to make it when a user hovers over each "slice" or pie chart section, a description shows instead of a number or title?

Love the plugin!

Thanks

**Comment by selu91** [comment]
hey,

Revolution slider must support the shortcode rendering in order to use it. There is no html to use there as the content si dynamic. 

Thank you !
