### ISSUE TITLE
demo feedback: Chart type examples, header image and shortcode text

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/visualizer#372]
Hey @contactashish13,

Came across some Visualizer demo enhancement ideas that can help us showcase better. 

1. It is interesting, how different varieties (features) of single chart type is showcased here - http://extensions.megamain.com/interactive-maps-charts-graphs/column-chart/. We can also showcase the same.

2. Shortcode Information: On chart pages like https://demo.themeisle.com/visualizer/timeline-chart/, https://demo.themeisle.com/visualizer/combo-chart/, I think the shortcode is not relevant information as it changes website wise. We can remove it.

Or we can write a short description instead of "You can render the timeline chart by using this shortcode:". short description Example: "You can find such a shortcode for your chart at Media > Visualizer Library"

3. Header images are pixelated:
![image](https://user-images.githubusercontent.com/29881234/51784603-6752a000-2171-11e9-8c03-bdf29f06e26b.png)

![image](https://user-images.githubusercontent.com/29881234/51785090-bbad4e00-2178-11e9-8ba9-f18bc54bfc4d.png)

Instead, we can also use a different image that is common for all Or longer images that don't pixelate.

cc: @selul

**Comment by selul** [comment]
@Vishakha-Patel would you like to beautify a bit the demos for viz, by implementing your ideas? I can setup you the access and @contactashish13 can help you with any guidance that you need.

Is not something urgent, but if you have some time to do them, I'm sure you will do a great job.

**Comment by Vishakha-Patel** [comment]
Sure!. Would like to give it a try.

**Comment by contactashish13** [comment]
@DanyCaissy could you please review these suggestions and see if they can be implemented?

**Comment by DanyCaissy** [comment]
@contactashish13 @Vishakha-Patel I did update these recently, I've added some missing charts, and on each page, I've added more text and more varied examples.

If you want to improve them more and you have time, feel free to do so.
