### ISSUE TITLE
Need help for Visualizer Plugin features!

### ISSUE THREAD

**Issue by Ankita-Popli** [Codeinwp/visualizer#38]
Hey!

This plugin is very nice. It is very easy to make a graph through it. But there are some points on which I need some help & suggestions.

1. Is there any option of adding more than 1 chart on same page. I want to add 8 charts per page on 30 pages.

2. How can I give 100% width to graph area. It reduces area of key when open on small screen.

3. The plugin is not showing key for 0% data.

4. How to align Graph & Key in middle.

5. Is there any option of writing keys on the bottom of graph instead of right.

**Comment by selu91** [comment]
Hey,

In the latest version of the plugin, you are able to use all the features requested. 

Thank you !
