### ISSUE TITLE
Not working with Modern Events Calendar Lite

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/visualizer#385]
@contactashish13 Visualizer plugin is having a conflict with the Modern Events Calendar (https://wordpress.org/plugins/modern-events-calendar-lite/) plugin. The issue is happening across all browsers. When I click the edit pencil to edit a chart, the popup window is an empty white box, there is no content in it. I get this error in the browser console: “Unchecked runtime.lastError: The message port closed before a response was received. upload.php?page=visualizer:1”.

https://wordpress.org/support/topic/plugin-conflict-with-modern-events-calendar/

**Comment by contactashish13** [comment]
@poonam279 this is a problem with the code of that plugin, specifically https://plugins.trac.wordpress.org/browser/modern-events-calendar-lite/trunk/app/libraries/factory.php#L247, which is written incorrectly. Commenting out that line makes our plugin work.
