### ISSUE TITLE
Charts not showed in the right category, and examples issues

### ISSUE THREAD

**Issue by JuJJuJ** [Codeinwp/visualizer#39]
I noticed a some bugs with the Visualizer:

The created charts are not showed in the category as expected: if you create a bar chart, then you go in the bar category, you won't find it, but only in the "All" category.
When you create a chart that has an example (here, the chart bar, with the example with populations in some cities), you won't be able to delete the examples titles. I made one chart to view the audience of our webradio, and I still have "population" when I hover a bar... Same thing for the legend, so I have to hide it...

Thanks for your help.

Best.

![visualizer-bug](https://cloud.githubusercontent.com/assets/3116780/8398022/e55828fa-1de0-11e5-97d5-5d46a46d407e.jpg)
![visualizer-bug02](https://cloud.githubusercontent.com/assets/3116780/8398023/e55a3262-1de0-11e5-9044-34994ea3c179.jpg)
![visualizer-bug03](https://cloud.githubusercontent.com/assets/3116780/8398021/e5552c36-1de0-11e5-82f4-a14471fc2bf8.jpg)

**Comment by contactashish13** [comment]
* It will be available under Column not Bar. 
* To increase thickness of bars, the CSV file should not contain multiple series with empty data. It is assuming the value is zero. The CSV should contain one series only.
* The legend cannot be edited. It takes the title from the title of the series.
