### ISSUE TITLE
remove (Lite) from the plugin name

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#391]
change `Visualizer: Tables and Charts Manager for WordPress (Lite)` to `Visualizer: Tables and Charts Manager for WordPress`

**Comment by contactashish13** [comment]
@selul should the URL and the name change on https://themeisle.com/plugins/visualizer-charts-and-graphs-lite/ as well? One of the many names the plugin has is `Visualizer Lite: Tables & Charts`. Maybe all names should become identical?

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/392

**Comment by selul** [comment]
@contactashish13 , yes the name should be consistent, we should update themeisle.com page, we will adress it in the redesign.

**Comment by contactashish13** [comment]
@selul you mentioned this might impact the license check. can you check that?

**Comment by selul** [comment]
@contactashish13 it should be ok now.
