### ISSUE TITLE
Download Excel and CSV issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/visualizer#402]
@contactashish13 we have a bug with downloading the excel data from chart on internet explorer and edge. 

A customer reported the issue here: https://secure.helpscout.net/conversation/835993203/187167?folderId=212385

Vishaka and I succeeded to replicate the customer issue, and l will attach a few videos to show the problem: 

1. You can download the excel file on Safari: 

https://www.dropbox.com/s/mxm2n0q734ismb3/Screen%20Recording%202019-04-27%20at%2012.22.52%20PM.mov?dl=0

2. You cannot download the excel file on IE

<img width="1398" alt="Screenshot 2019-04-27 at 12 44 37 PM" src="https://user-images.githubusercontent.com/6906834/56847875-4160a700-68ea-11e9-9c9e-9a04da4e492a.png">

Here I have waited for two minutes without any success. The page remains blocked in this loading loop. 

3. Here is how the issue can be reproduced: 

- Enable "Edit" from selecting Advanced > Frontend Actions and ticking the Excel box.

A short video: 

https://www.dropbox.com/s/qwkoasjrl071wl2/Screen%20Recording%202019-04-27%20at%2012.48.58%20PM.mov?dl=0

I have tested with Line, and Pie charts and both have this issue. 

Let me know if there is anything else we can help with. cc: @Vishakha-Patel 

Visualizer Pro version: 1.8.1
Visualizer Lite version: 3.1.2
WordPress version: 5.1.1
PHP version: 7.2.0

Windows 10 and latest version of IE 11

**Comment by contactashish13** [comment]
@mileamadalin During my testing, I found that the option for CSV also had the same problem.

PR https://github.com/Codeinwp/visualizer/pull/403 solves these issues. Please test and confirm. cc @Vishakha-Patel 

PS - its usually good practice to test similar/related functionality as well to check if they are buggy or not e.g. all the 4 front end actions.

**Comment by mileamadalin** [comment]
@contactashish13 The issue was fixed with the new version.

Thank you @Vishakha-Patel for confirmation.
