### ISSUE TITLE
Export data?

### ISSUE THREAD

**Issue by chrisTX972** [Codeinwp/visualizer#41]
I have lost the original csv data file that I used to create my graphs. Can you recommend a way to export the data?  I have tried searching the database tables but I can't find the data for Visualizer.  I have limited skill with database management... on a learning curve. If you can help me export my graph data in csv format, I would be very appreciative.

Thank you

**Comment by contactashish13** [comment]
do you want this in the free or the pro version?

**Comment by selu91** [comment]
the free would be ok.

**Comment by verosaka** [comment]
Hello, most of times csv data is the result o an union query, you have to
know the relations involved in the data, create a query, execute it and
export it to a csv file with the export utility of your query tool.
I hope this helps.
Greets.
ᐧ

On 11 May 2016 at 04:13, contactashish13 <notifications@github.com> wrote:

> do you want this in the free or the pro version?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/visualizer/issues/41#issuecomment-218391682>
>



-- 
Rubén Sánchez.
Verosaka Representaciones, C.A.
RIF:J-29613291-7
www.canalexplorador.com
verosaka@gmail.com
Twitter: @verosaka
Linked In <http://ve.linkedin.com/pub/ruben-sanchez/4/131/807>
Of:(+58)212-576.3892
Cel:(+58)414-113.7093
Direccion: Av. Universidad,Centro Parque Carabobo, Nivel 1, Local 130.
La Candelaria./ Caracas 1060
Ciudad: Caracas
Estado: DC
Pais: Venezuela

NOTA CONFIDENCIAL: La información contenida en este E-mail es confidencial
y sólo puede ser utilizada por la persona o la compañía a la cual está
dirigido y/o por Verosaka Representaciones, C.A.. Si usted no es el
receptor autorizado, cualquier retención, difusión, distribución o copia de
este mensaje esta prohibida y será sancionada por la ley. Si por error
recibe este mensaje, favor reenviarlo y borrar el mensaje recibido
inmediatamente.
Gracias-
Sugerencias <http://lweb.es/publicidad/anuncio.php?tacos=10&tipo=angosto>

**Comment by selu91** [comment]
@contactashish13 please add the security check nonce.

**Comment by contactashish13** [comment]
done

**Comment by selu91** [comment]
@contactashish13 can you remove the export btn and add it here: 

http://prntscr.com/ba7ejq 

Also please use a proper icon for this from /images/ui-icons.png, whatever you think it fits.
