### ISSUE TITLE
Add new banner and logo

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/visualizer#417]
Let's update Visualizer logo & bananner for WP.org https://wordpress.org/plugins/visualizer/

Files can be found here:
https://drive.google.com/drive/folders/15KMzvbOx66et-WkSXIlFA99pX0emnGRM?usp=sharing

**Comment by sab2ina** [comment]
I don't have access in the Feedzy and WPPR repos, their banners should also be changed.

**Comment by ineagu** [comment]
cc @contactashish13

**Comment by sab2ina** [comment]
I think only @selul has access to WP.org

**Comment by selul** [comment]
I'm adding them now

**Comment by selul** [comment]
@sab2ina done.

**Comment by sab2ina** [comment]
ty
