### ISSUE TITLE
Confusing behavior of horizontal/vertical grid lines on bar/column charts

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#418]
A user on HS wanted to remove the grid lines of his charts (the horizontal ones) and it looks like the option of changing the number for the grid lines or their colors doesn't seem to be working as expected. 

I have also tested this on my end -> https://embed.vidyard.com/share/dcrqfr54b3yqG6qWiJ3qwM?

it looks like changing the color for the minor grid lines is working, but for the main ones it's not. Also, choosing how many grid lines to display on your chart doesn't seem to be working for any of them. Update: changing the number for minor grid lines to 0 is working, but changing it for anything else like 1 is not working as expected. Example -> https://embed.vidyard.com/share/KvimZd68S2nxW6277Tp3bg?

Maybe I misunderstood how this feature works, but if I did, and the user did, maybe a diiferent or clearer explanation / approach would be better to consider in the future.

**Comment by rodica-andronache** [comment]
+1 I find this confusing also ( if it's not a bug )
![download](https://user-images.githubusercontent.com/3266155/72063250-197f6b00-32e2-11ea-8f8f-4314b71d2761.png)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/665 changes the behavior according to the documentation on https://developers.google.com/chart/interactive/docs/gallery/columnchart#configuration-options and https://developers.google.com/chart/interactive/docs/gallery/barchart#configuration-options.

- `minorGridlines.count` has been deprecated from the old behavior.
- `gridlines.count` has changed its behavior
- **Vertical gridlines show on the vertical axis and parallel to horizontal axis. Horizontal gridlines show on the horizontal axis and parallel to vertical axis** so column charts will display vertical gridlines and bar will display horizontal gridlines. The definition is confusing and important.

While testing this also found a problem with the `View Window` feature. 

@DanyCaissy @rodica-andronache it might be a good idea to test all the settings in both the library and block editor and create a separate issue for all problems that are uncovered.

**Comment by rodica-andronache** [comment]
@contactashish13 

- [ ] Not sure about the `Axis Text Color` options. They look to apply differently than all the other options from the Vertical/Horizontal tabs.

The one from vertical tab applies to horizontal, and the one from horizontal applies to vertical. Is that ok?
![download](https://user-images.githubusercontent.com/3266155/76758216-f49bee00-6791-11ea-9ba7-2172787f50a6.png)

- [ ] for `Minor Grid Lines`, how could I make them appear? I've tried multiple numbers and didn't manage to see them.

![download (1)](https://user-images.githubusercontent.com/3266155/76758408-4e041d00-6792-11ea-8a97-71292310f5ac.png)

- [ ] for all options, I see you are using placeholders ( for e.g. for the Minor Grid Lines it's 0 ), and I think that can create confusion. I have the feeling that's the current value for that field. I think we should either have that as a default value or not have it at all, as it doesn't help, from my point of view.

**Comment by contactashish13** [comment]
@rodica-andronache I've pushed changes in for (1). For (2), the minor grid lines are showing in your screenshot - the ones that do not have a number e.g. 100,000 is a minor grid line. A value of 0 should disable it (and it does on the block editor. If it does not, this needs a separate issue. (3) definitely needs a separate issue as it may affect some fields adversely.

Another issue that needs to be addressed separately (and first tested/verified) is some settings don't go from the library to the block editor e.g. color of minor grid lines resets to default in the block editor. Maybe its the same case vice versa for some fields and needs to be tested comprehensively.
