### ISSUE TITLE
DataTables: Scrolling doesn't work properly

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#424]
ScrollCollapse doesn't work. We need to have a `scrollY` property which is only applied when `scrollCollapse` is enabled.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/429

**Comment by HardeepAsrani** [comment]
@contactashish13 I merged this to my branch and `Scroll Collapse` is still not working while it seems you've removed the other three option. Is that correct or I'm just missing something?

**Comment by HardeepAsrani** [comment]
Updated the ticket about the scrollCollapse issue we discussed.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/455

Have addressed horizontal and vertical scrolling. Merged into 3.3.0
