### ISSUE TITLE
In the library, table thumbnail makes the options hidden/unclickable

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/visualizer#427]
In the free version of Visualizer, Table thumbnail options are almost hidden because of image overlap.

See here -->> https://snag.gy/4pyqnA.jpg

Tested all other graphs, only happens with the Table graph.
The issue seems to go away when the Pro version is activated.

Tested with Poonam and was able to replicate the same issue.
Visualizer v3.2.1
WordPress 5.2.1

@contactashish13

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/428

**Comment by radu-themeisle** [comment]
[+1](https://secure.helpscout.net/conversation/897490616/194335/)
