### ISSUE TITLE
Add option for interpolateNulls = True

### ISSUE THREAD

**Issue by kal001** [Codeinwp/visualizer#43]
Hi,

I am using your plugin to test displaying 5 temperatures acquired from 5 different temperature sensors, and stored in a mysql database.
Each point passed to the plugin consists of a timestamp, and 5 values. Each of the values can either be null, or a temperature.
Google chart allows you to define interpolateNulls = True (which is false by default), in order for the graph to look as an interpolate line, and not a collection of dots.

Take a look at this live example produced with your plugin to see what I mean: http://www.lourenco.eu/novo-grafico/

![image](https://cloud.githubusercontent.com/assets/6324630/9862684/558e7c26-5b32-11e5-9324-5f8f094168ab.png)

If rendered with interpolateNulls = True it is:
![image](https://cloud.githubusercontent.com/assets/6324630/9862708/82f6cbdc-5b32-11e5-8eff-92650e45e112.png)

Can you add an option to specify interpolateNulls = True, or is there any other way to do it?

Regards,
FL

**Comment by selu91** [comment]
@kal001 using the scatter chart type wont fix the issue ? 

Thank you !

**Comment by kal001** [comment]
Meanwhile, I solved the problem. Thanks.
FL

2016-01-04 11:40 GMT+00:00 Marius Cristea <notifications@github.com>:

> @kal001 <https://github.com/kal001> using the scatter chart type wont fix
> the issue ?
>
> Thank you !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/visualizer/issues/43#issuecomment-168653883>.
>



-- 
FL
fernando.lourenco@lourenco.eu

**Comment by selu91** [comment]
you're welcome !
