### ISSUE TITLE
Gauge chart shows JS warnings

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/visualizer#431]
User reported that all the Gauge chart that he created shoes JS warnings when inspecting the element.

Sample URL: https://absr-research.com/commodity-analytics/
Ticket: https://secure.helpscout.net/conversation/877745181/191762/

I was able to replicate the issue on my own site.
https://snag.gy/hY2CQi.jpg

@contactashish13

**Comment by mileamadalin** [comment]
@contactashish13 Do you think that it's something we can fix in the future? I mean, even if are not errors (fatal errors) maybe we can improve them.

It looks like the warning that appears is caused by images that we load for the chart from render-google.js, but not sure why that's happening.

**Comment by contactashish13** [comment]
@mileamadalin @purplecodes these are warnings that indicate that the chart cannot be converted into a static image. These warnings are useful when someone wants to use the static chart image and then wonders why they cannot use it. These are warnings and can be ignored.  

@mileamadalin please close when you read this.
