### ISSUE TITLE
Central African countries do not show a Tooltip

### ISSUE THREAD

**Issue by IosifGabriel** [Codeinwp/visualizer#438]
Description:
Democratic Republic of the Congo, South Sudan,  Republic of Congo do not show a ToolTip

How to reproduce:
1.Make a geochart
2. import from the file below, because it has all the countries. 

Expected behaviour:
All countries should show a ToolTip

Current behaviour:
Central African countries do not show it.

Reference:
http://prntscr.com/oc1b40

link for csv.
[https://docs.google.com/spreadsheets/d/e/2PACX-1vR4ggLN9Xm5Ol5x01K0_AwvPSbttwUfjPUHhQaY6UQ3WIPsGa4XWzn3g7d-osHJsOwSomGMgz9kb7zZ/pub?output=csv](url)

Technical info
WordPress version: 5.2.2
Version: 1.8.3

**Comment by IosifGabriel** [comment]
https://secure.helpscout.net/conversation/893757886/193921?folderId=212385

**Comment by contactashish13** [comment]
@IosifGabriel can't do much about this. Seems to be an issue with Google: https://github.com/google/google-visualization-issues/issues/2488.
