### ISSUE TITLE
Chart not resizing according to the window zoom factor with the TwentyNineteen WordPress themes

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#441]
After testing the ChartJS implementation in Visualizer, I've noticed a weird behavior related to the zoom factor.

With the Google Charts, the charts are resizing according to the zoom factor of the browser window, no matter which theme i'm using. -> https://embed.vidyard.com/share/TgngzYiQXmLvFeudwMKhYQ?

After creating a chartJS chart:

- The chart resizes correctly if I am using Hestia, Zelle/Zerif, ShopIsle, Neve -> https://embed.vidyard.com/share/KvwfKGCXoqe2eL8XtntEQH?

- The chart does NOT resize correctly if I am using Twenty Nineteen -> https://embed.vidyard.com/share/ZR7AL9RDFu7q4Er7Lmymh7? 

#373

**Comment by contactashish13** [comment]
@DanyCaissy TwentyTwenty theme works well. I suppose this is because of improvements in WP 5.3. We can forget about TwentyNineteen. Please test and remove if no longer a concern.

**Comment by DanyCaissy** [comment]
@contactashish13 It works fine in 2020.

I think it could still be worth fixing (there might still be a lot of users using the older theme) but only if you think it would be an easy fix, otherwise, you can close this ticket.

**Comment by contactashish13** [comment]
Closing this till someone actively using a TwentyNineteen theme raises this as an issue.
