### ISSUE TITLE
Date format in Visualizer

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#451]
Having some issue with the date format. Right now we format the dates like this:

`return moment( data ).format( fromFormat, toFormat );`

And that code doesn't really work. I tried the classic integration and the format doesn't work. When building the Gutenberg part, I tried this and it seems to work just fine:

`return moment( data ).format( toFormat );`

I'm sure there are reasons why we use a `from` parameter but it doesn't seem to work. So far I'm keeping the Gutenberg integration part same as Classic (so both of them equally don't work)

@contactashish13

**Comment by contactashish13** [comment]
@HardeepAsrani it works as expected

![image](https://user-images.githubusercontent.com/12953439/61434554-e3c18100-a953-11e9-8a2b-a865251333df.png)

**Comment by HardeepAsrani** [comment]
Seems to work now. I think there was some issue in the date format before.
