### ISSUE TITLE
Display the legend vertically below the chart

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#470]
A user wanted me to note her feature request about the Legend placement.

Currently, you can place the legend below the chart, but it's horizontal like this -> http://prntscr.com/olw63y and like this -> http://prntscr.com/olw6e8

So, the user wanted to display them vertically (one below the other) just like an `<ul>` html list.

**Comment by contactashish13** [comment]
@SilviuDinu this can be done through CSS manipulation but there is no support for this in the API. You can add examples for this in the documentation.

**Comment by SilviuDinu** [comment]
@contactashish13 I investigated this and couldn't find a general way to do it through CSS. It only works with **transform: translate;** property and you need to add <br> in the HTML to add spaces. I don't think it's worth adding this in the docs since it's just this client asking about it.

Did you have something else in mind when you mentioned CSS manipulation? Maybe there is a tool or something that I am not familiar with.

**Comment by contactashish13** [comment]
@SilviuDinu yes, you can use that and then add padding/margins. You can close this if this is not a generic issue
