### ISSUE TITLE
Export/Import Chart + Settings

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#475]
I don't know if anyone has suggested this but we should also allow users to export/import a chart with all the settings.

But this is just an idea and also only worth doing if users have requested for this. If not then we can let it just float.

**Comment by contactashish13** [comment]
isnt this the same as https://github.com/Codeinwp/visualizer-pro/issues/170?

**Comment by DanyCaissy** [comment]
Closing as duplicate
