### ISSUE TITLE
Add links to survey

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#479]
https://app.asana.com/0/1129400186358085/1131896478970676/f

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/480 adds the surveys to the support page as well as the below box in the library page when only free is being used.

![image](https://user-images.githubusercontent.com/12953439/62407646-592a8400-b5d9-11e9-89a7-81e8e0729bce.png)

@DanyCaissy could you please add the appropriate verbiage?

![image](https://user-images.githubusercontent.com/12953439/62407816-57ae8b00-b5dc-11e9-89dd-9c5302a9ba9d.png)

**Comment by DanyCaissy** [comment]
@contactashish13 

### Answer a few questions for us to help us improve the product

We're always looking for suggestions to further improve Visualizer, if you'd like to help us, please fill out this [survey]. 

[For Free users only] If your feedback is especially helpful and we choose to do an interview with you to discuss your suggestions, you will even gain a yearly membership for free for your trouble.
