### ISSUE TITLE
JSON import: Provide some support for authentication out of the box

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#481]
https://github.com/Codeinwp/visualizer/issues/308#issuecomment-489554678

**Comment by contactashish13** [comment]
For basic authentication, we can ask the user to provide 
- username/access key
- password/access secret

The header in basic auth would be called `Authorization` with value of `Basic base64(username:password)`

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/550 provides support for basic authentication.

![image](https://user-images.githubusercontent.com/12953439/66464539-d7ede280-ea9c-11e9-8bee-03ad3ce4d2d4.png)

@DanyCaissy can you test this as well?

**Comment by DanyCaissy** [comment]
@contactashish13 How would I test this?

**Comment by contactashish13** [comment]
@DanyCaissy you can test it as follows:

- create a few posts on the instance
- check that you are able to access the WP API on the browser - `<siteurl>/wp-json/wp/v2/posts`
- install https://wordpress.org/plugins/wp-rest-api-authentication/ and enable basic authentication
- check that you are **not able** to access the WP API now without authentication (you can confirm by using the postman extension on chrome if you wish)
- in visualizer provide the credentials as mentioned in the configuration screen of the wp-rest-api-authentication plugin along with the URL as `<siteurl>/wp-json/wp/v2/posts`

It would also be good to test out a variety of JSONs (without authentication) that provide results in different formats. The ones I've tested are:
- http://swapi.co/api/people
- http://swapi.co/api/people?format=json
- https://api.exchangeratesapi.io/latest

**Comment by DanyCaissy** [comment]
@contactashish13  Got it. I've tested this and the auth works fine for me. I've also tested some of the endpoints you've mentioned and noticed a couple issues:

1) https://i.imgur.com/N9NQ28x.png Might be planned on another ticket already, but the 'save and show chart' is at the bottom right now (below the scrollbar) and very easy to miss, the other show chart button (on the right) does not apply the changes. We should put the save and show chart on the right menu instead to increase visibility and consistency.

2) On /api/people (and probably all others), if we exclude all fields, which is that way by default, we have a JS error: https://i.imgur.com/1kjPCSl.png. We should try to catch it and notify the user instead.

3) on /api/people I also could not parse vehicles: https://i.imgur.com/vvnvmOJ.png

**Comment by contactashish13** [comment]
@DanyCaissy 

1. It don't think its a good idea to shift the button to the right frame as that will make UX even more complicated with 2 action buttons being on the left and one on the right. Maybe we can take that up when we revamp the UX. For the time being I've added a text message.

2. Fixed

3. Fixed

**Comment by contactashish13** [comment]
@DanyCaissy please let me know when you have tested this.

**Comment by DanyCaissy** [comment]
@contactashish13 These are fixed

**Comment by DanyCaissy** [comment]
Oops didn't mean to close.

**Comment by contactashish13** [comment]
@DanyCaissy I've come around to your way of thinking about the button. It helps address #556 as well.  PR: https://github.com/Codeinwp/visualizer/pull/563

**Comment by rodica-andronache** [comment]
@contactashish13 the import from JSON doesn't work anymore (tried without authentication for now). I've tried with the version on production and it worked well, so it must be related to the new changes
https://www.loom.com/share/00b40d107a9242ecae9f24941eb27b55

**Comment by rodica-andronache** [comment]
@contactashish13 if you can help me, I couldn't fully understand how to test the authentication.
I followed your steps until I made sure `<siteurl>/wp-json/wp/v2/posts` is not accessibile anymore.
But I don't understand which JSON I would need to test. There should be a JSON file on my wp instance, right? If so, how did you do that? I can't upload a JSON file on my WP due to security reasons. Thanks

**Comment by contactashish13** [comment]
@rodica-andronache to upload a file on my dev instance I merely copy a file. I don't know what method you are using but if it is your dev instance you have full control over it.

You don't need a file to test authentication. You need to use the wp json url, that's all - that is the source.

**Comment by rodica-andronache** [comment]
@contactashish13 in the end, Marius helped me with this, so I managed to test it.
There are 2 things that don't work for me:
1. Before entering the user and password, the notice for http://wordpress.local/wp-json/wp/v2/posts sais "This does not appear to be a valid JSON feed.", while the feed is correct, in Postman. The notice should be about the authentication missing.
2. After I clicked on Create Chart, all the values disappeared from the chart.
https://www.loom.com/share/ec35dc4d6bcb447b879b5c0181554309

**Comment by contactashish13** [comment]
@rodica-andronache the plugin does not know that auth is missing - it only knows its not able to parse/access the feed for some reason so it displays that error.

I'm unable to replicate the second error.  I believe it should have been fixed by https://github.com/Codeinwp/visualizer/pull/636. Feeds with and without authentication should display identical behavior. Are they behaving differently for you?

**Comment by rodica-andronache** [comment]
@contactashish13 ok, I think I figured it out. Once I deactivate the https://wordpress.org/plugins/wp-rest-api-authentication/  plugin, the chart loads properly.
