### ISSUE TITLE
Chart does not save if you do not click on show chart in manual data

### ISSUE THREAD

**Issue by IosifGabriel** [Codeinwp/visualizer#482]
**How to recreate:**
Create a new chart
Enter manual data and change it accordingly 
Click create chart.

**Expected behavior**
Save the chart regardless

**Current behavior**
1. It may not save the chart at all if you insert data right when you create it from Add New ( i was able to replicate 3 times out of 5-6 )
2. It does not save the manual data if the chart is the default one and already created

Video of the issue:
Not saving at all -> https://embed.vidyard.com/share/6fXRBQus7EtVnVSFdoL2gS?
When you create it but remains on default then you decide to insert manual data ->https://embed.vidyard.com/share/gmA35pbtUCooTJfcvBajMJ?
Behaving good when clicking show chart -> https://embed.vidyard.com/share/2zoA2ap3H7zcYWrpYyciJC?

Version: 3.2.1

**Comment by contactashish13** [comment]
Closing this as this is not a feature bug but a consequence of the design paradigm. You **have** to click on show chart to save the data.
