### ISSUE TITLE
Link for "create a chart" not working

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#484]
Here: https://i.imgur.com/C9VEzzH.png

There are two issues:

1- The link to create a new chart redirects me to the page I am already in, instead of the page to create a new chart. To reproduce it, just try it out on this page: https://uninterested-capybara.jurassic.ninja/wp-admin/post.php?post=240&action=edit

2- Regarding the notice, I think it should be moved to the selection page: https://i.imgur.com/VWcvkvn.png

Below Visualizer. The reason is, the user might miss the first notice, and get confused on the selection screen.

As for the notice itself, there are a few typos, I think we should modify the text to this:

"ChartJS charts are currently not available for selection here, you must visit the [library], get the shortcode, and add the chart here in a shortcode tag."

**Comment by contactashish13** [comment]
@DanyCaissy this was also fixed by @HardeepAsrani and merged into 3.3.0. can you please test?

**Comment by DanyCaissy** [comment]
This seems good now.
