### ISSUE TITLE
Frontend actions do not save through rollbacks and updates

### ISSUE THREAD

**Issue by IosifGabriel** [Codeinwp/visualizer#492]
Tick boxes in the Frontend do not save through rollbacks and updates. 

Tested both on local and public instance
Video of the issue -> https://embed.vidyard.com/share/6JWLJgPgMfqHbnqMDJN9wF? (all of the charts had the checkboxes activated in the beginning of the video)

Credits for the public instance 
https://rude-ratel.jurassic.ninja/wp-admin/upload.php?page=visualizer
demo
HlLHQ2YDkae3

**Comment by IosifGabriel** [comment]
https://secure.helpscout.net/conversation/926278888/199007?folderId=212385

**Comment by contactashish13** [comment]
@IosifGabriel this has been fixed in 3.3.0. Please test this with the 3.3.0 branch and let me know if this is an issue. The release is due by tomorrow.

**Comment by contactashish13** [comment]
closing this as this has been fixed as part of #468
