### ISSUE TITLE
Charts are not being displayed on Add New

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#494]
A user reported that he can't create a new chart because the page is blank for him.

I have tested too on his end and when I go to Add New from Media -> Visualizer Library I'm getting this screen and a request error in the console -> https://prnt.sc/os3iq8

Ticket link -> https://secure.helpscout.net/conversation/928310597/199188/

This occurs both if the PRO version is activated or not, so the problem comes from the free I think.

cc @contactashish13

**Comment by contactashish13** [comment]
Closing this as this is not an issue and was fixed by the customer on his installation.

PS - @SilviuDinu as discussed, please do not create tickets without going through the entire cycle of troubleshooting.
