### ISSUE TITLE
Issues on multisite install

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#498]

**Comment by contactashish13** [comment]
`customization.js` does not seem to work properly - https://wordpress.org/support/topic/cant-add-or-remove-rows-using-manual-editor/

**Comment by DanyCaissy** [comment]
I do get that error: https://i.imgur.com/PFvS5Ju.png

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/500 fixes issue with https://i.imgur.com/PFvS5Ju.png

**Comment by DanyCaissy** [comment]
I've tested this and could not find the error anymore on multi sites
