### ISSUE TITLE
Ensure consistent and clear documentation across product assets

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#502]
We need to review all the below assets to ensure that they have consistent and clear documentation on what features are part of pro and what are not. From an end users point of view, we may want to assume they can land on any page using a search engine and not necessarily follow a sequential order from one page to another.

We should also make sure the UX makes sense. For example, I have no clue where to find the documentation if I go to https://themeisle.com/plugins/visualizer-charts-and-graphs/ - there should be a button right next to View Demo or Buy Now to make it easier.

- https://wordpress.org/plugins/visualizer/
- https://demo.themeisle.com/visualizer/
- https://themeisle.com/plugins/visualizer-charts-and-graphs/

**Comment by DanyCaissy** [comment]
@contactashish13 Yup I've started working on that, just need to gain access.

**Comment by DanyCaissy** [comment]
I've gained access, I'll keep track of updates on asana.

**Comment by contactashish13** [comment]
I think we should keep track here especially if the people who need to take action will not have access to Asana. If we are going to give them access to Asana then I don't see the point of having 2 platforms. @selul we need to discuss the exact sequence of using Asana and GitHub.

**Comment by DanyCaissy** [comment]
@contactashish13 We can stop using Asana and move things to a github project instead, that's fine with me. Let me know what you think on Slack.

**Comment by contactashish13** [comment]
@DanyCaissy as discussed on slack we can continue to use asana to discuss stuff and then, when we reach a conclusion, use github so that any code changes can be traced back to an issue. If (1) no code change is required and (2) no other person who doesn't have access to asana needs to be assigned a task then we can continue to use asana for that particular task. cc @selul 

We can close this task because I assume it satisfies both (1) and (2).
