### ISSUE TITLE
Long responsive table can overflow on smaller screens

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#503]
This is fairly specific but a user reported this issue, it happens when they create a table with a lot of data, and they check 'responsive', and their screen is smaller. I've included a gif to demonstrate.

![2019-08-19_18-35-39](https://user-images.githubusercontent.com/5183243/63306534-9321a880-c2b0-11e9-8d1a-1db6a8c13fd5.gif)

**Comment by contactashish13** [comment]
@DanyCaissy PR https://github.com/Codeinwp/visualizer/pull/604 fixes this. Can you please test this? The chart will not adjust as you resize - you will have to refresh the screen.

**Comment by DanyCaissy** [comment]
@contactashish13 This is fixed

**Comment by rodica-andronache** [comment]
@contactashish13 tested also with https://github.com/Codeinwp/visualizer/pull/604 and https://github.com/Codeinwp/visualizer/pull/561 and for me is not working, I'm not sure if I'm missing something
https://www.loom.com/share/bdd6939f86ca47b7bd6d38d26c62e4f5

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/616 should fix this.

**Comment by rodica-andronache** [comment]
@contactashish13 it's working well on smaller devices. 
Could it be possible to have the scrolling bars on desktop as well, when there is more content, either horizontal or vertical?

Right now, I have content that is not visible, unless I make the screen smaller
![Screenshot (5)](https://user-images.githubusercontent.com/3266155/72732772-1c5e4380-3b9f-11ea-833f-e1c4572ddcc6.png)

**Comment by contactashish13** [comment]
@rodica-andronache somehow tables with more data do not want to show scrollbars but table with less data can show a horizontal scrollbar

![image](https://user-images.githubusercontent.com/12953439/72782987-40775e80-3c4b-11ea-9882-3c0a4d05164d.png)

Maybe we can keep this for later as an enhancement as the code does not seem to work.

**Comment by rodica-andronache** [comment]
ok, sure
