### ISSUE TITLE
Error adding chart on page

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#506]
https://uninterested-capybara.jurassic.ninja/wp-admin/post.php?post=329&action=edit

Upon trying to add a chart on the page itself, we get this error: https://i.imgur.com/6qE8h9k.png

This seems to be somewhat new, might be due to the latest updates.

**Comment by HardeepAsrani** [comment]
Note for self: It appears to be due to some change in Custom CSS options which don't map nicely with the block.

**Comment by HardeepAsrani** [comment]
I'm not able to reproduce it on my side. I believe it's due to something in Row/Column Settings of Table Block. Can you try and see what in particular causes this?

**Comment by HardeepAsrani** [comment]
@DanyCaissy Can you reproduce this without adding Table Block? I suspect it has to do with the table block.

**Comment by DanyCaissy** [comment]
@HardeepAsrani

**Before adding tables**

The pagination issue happens on this new instance, no table chart was ever created yet: https://i.imgur.com/16R4JOa.png. There are 5 google charts so I shouldn't need to load more to see the 4th and 5th.

This is happening after I created chartjs charts, they mess with the pagination.

**After adding tables**

Once creating one table, adding one to the post, then clicking "add new chart" again on the post, with only one table created, I get this: 
https://i.imgur.com/Kz85nZ8.png

I added a few more default tables and got this afterwards: 
https://i.imgur.com/jPme0es.png

------------------------------------

These happened on this instance, you can create another one and replicate this easily, just create a bunch of charts of all types and add new charts on a post.

https://comfortable-vampire.jurassic.ninja 
WP user: demo WP/SSH password: 39QpNE6I9hq9

**Comment by HardeepAsrani** [comment]
Any updates on the credentials I emailed you? @DanyCaissy :)

**Comment by DanyCaissy** [comment]
@HardeepAsrani I haven't been able to install visualizer pro, I get: 

Unable to create directory wp-content/uploads/2019/09. Is its parent directory writable by the server?

**Comment by HardeepAsrani** [comment]
@DanyCaissy Should be fixed now. It was Docker on Linux so that's why.

**Comment by DanyCaissy** [comment]
I've reproduced it on your instance: https://i.imgur.com/vGwQ9eo.png

Steps to reproduce: Create 5 google charts, create 1 chartjs chart, create 1 table.

Issues: Load more even though it shows 5 charts out of 6. Extra whitespace on chart #15 

On: /wp-admin/post.php?post=1&action=edit

**Comment by DanyCaissy** [comment]
@HardeepAsrani

**Comment by HardeepAsrani** [comment]
I've added the support for flat feeds and headers. @DanyCaissy can you test and check if everything is as it should be?

**Comment by DanyCaissy** [comment]
@HardeepAsrani What do you mean exactly with "flat feeds and headers" ? Is this the right ticket?

**Comment by DanyCaissy** [comment]
This error was fixed since
