### ISSUE TITLE
Increase minimum requirement to PHP 5.6

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#507]
The spreadsheet component requires `"markbaker/matrix": "^1.1` as part of its composer.json and that component is supported only on PHP 5.6 and above. This means that visualizer may cause problems for PHP versions below 5.6

ref https://wordpress.org/support/topic/infinite-spinner-when-trying-to-create-a-chart/#post-11854670

**Comment by contactashish13** [comment]
@selul what do you think?

**Comment by selul** [comment]
Yes, makes sense. Make sure to increase the required php version in the readme.txt file aswell.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/508
