### ISSUE TITLE
For every chart show the last updated date and any error that exists

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#510]
This would help users understand when their scheduled chart was last updated vs. its schedule. This may help in reducing the steps in troubleshooting and maybe help us determine if there is a problem with the cron.

This would also include showing a relevant error if the chart tried to be updated but was not updated because of some error.

**Comment by contactashish13** [comment]
@DanyCaissy what is the UX/UI you suggest for this?

**Comment by DanyCaissy** [comment]
Yes, I think we can have a 'last updated date', in the date('Y-m-d H:i:s') format maybe, and, if there were errors/logs, have a red 'last error' button show up. That could open a popup or something similar to show the last errors.

I think we only need to worry about the last errors, I don't see the point saving older errors, it'd be better not to save them (they'll clog up the database if there are large errors on live updating).

**Comment by contactashish13** [comment]
![image](https://user-images.githubusercontent.com/12953439/64147082-dcd7ca80-ce3c-11e9-95da-f3bd57090af7.png)

This shows how the date updated will look as well as how the last status of the chart will be displayed. In case of an error, the user can click on the X icon to see details. 

@DanyCaissy let me know what you think.

**Comment by DanyCaissy** [comment]
@contactashish13 This seems fine, but I think we have to clarify that this is "last data updated" somehow. Otherwise the user might think this is the creation date, the last date they updated the chart, settings etc.

**Comment by contactashish13** [comment]
@DanyCaissy can you please test this? It would be good to test this in conjunction with scenarios that throw an error just to see if the error is shown here.

**Comment by DanyCaissy** [comment]
@contactashish13 On 3.3.1 I don't see these. Where do you want me to test this?

**Comment by contactashish13** [comment]
@DanyCaissy sorry, I didn't publish the branch. You can test this PR - https://github.com/Codeinwp/visualizer/pull/537 for the next release.

**Comment by DanyCaissy** [comment]
@contactashish13 This seems great

**Comment by rodica-andronache** [comment]
I think it would be a good idea to have a `Last updated:` message before the date
![download](https://user-images.githubusercontent.com/3266155/71903098-034f9e80-316c-11ea-864c-d83e2f230eba.png)

**Comment by contactashish13** [comment]
@rodica-andronache when you mouseover, you see the title as "Last Updated". If we explicitly state Last Updated then we also have to explain what the green tick or the red cross means that is why I tried to keep the UI consistent by using a mousover title instead. Let me know if you still want the text.

**Comment by rodica-andronache** [comment]
@contactashish13 I'm good with that behavior. It is just that for me, no matter what chart I create, using https://github.com/Codeinwp/visualizer/pull/561 the title is empty for the green tick, so nothing appears on mouseover for it. Is there something else I'm missing?
https://www.loom.com/share/9b420b4902a94457a4d9a000ff48ebb1

**Comment by contactashish13** [comment]
@rodica-andronache actually there is no title for the green tick but the red cross gives a title  of 'Click to view the error'

**Comment by rodica-andronache** [comment]
ok, I understand 👍
