### ISSUE TITLE
Add messages to address current UX

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#516]
- on editing manual data, click Show Chart before Save Chart

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/523

**Comment by contactashish13** [comment]
@DanyCaissy till we completely overhaul the UX let me know what all messages you think we need to add that will make the "annoyance" of the current UX a little less. (Ignore the previous notification as it goes to the PR and I'd rather have all possibilities listed down in the issue)

**Comment by contactashish13** [comment]
@DanyCaissy messages that I've added:

![image](https://user-images.githubusercontent.com/12953439/64903725-d1f22500-d6db-11e9-9013-1ab93b97fca7.png)


![image](https://user-images.githubusercontent.com/12953439/64903733-e20a0480-d6db-11e9-9e7b-4da433235423.png)

**Comment by DanyCaissy** [comment]
@contactashish13 

One thing I can think of is the charts which have design modifications that are only visible after saving. There already is a message about it, but it's not very visible, I hadn't noticed it the first time.

We could make that message more visible, akin to your last image.

**Comment by contactashish13** [comment]
@DanyCaissy could you share a screenshot of message that you are referring to?

**Comment by DanyCaissy** [comment]
@contactashish13 Oh, this only happens to tables actually, I think. This:

https://i.imgur.com/Y08aQnf.png

I think ideally we'd find a way for the changes to be reflected right away. In the meantime, bolding the text and adding an icon might make this text more visible.

**Comment by DanyCaissy** [comment]
I've tested and this is fine
