### ISSUE TITLE
Add back Google Table charts

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#524]
https://app.asana.com/0/1129400186358085/1136935251791377/f

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/686 and https://github.com/Codeinwp/visualizer-pro/pull/264 are ready to test. 

I would suggest the following steps to test:
- use an old version of the plugin that supported Google table charts (I think before 3.0.12) and create a few table charts
- upgrade to the latest available version and create a few DataTable table charts
- when you upgrade to this PR all table charts created in the previous steps should be visible/searchable/editable
- all table charts should be insertable/editable in the block editor
- new table charts can be created using either Google or DataTable


PR https://github.com/Codeinwp/visualizer-pro/pull/264 will succeed once free is released.

**Please don't merge the PRs as I need to add cypress tests**

**Comment by contactashish13** [comment]
@rodica-andronache this resolves https://github.com/Codeinwp/visualizer-pro/issues/256 as well.

**Comment by rodica-andronache** [comment]
@contactashish13 the only issue I saw is with `editing old Google Table charts`.

How to replicate it:
- Install & activated https://downloads.wordpress.org/plugin/visualizer.3.1.0.zip
- Create a few table charts
- Update the plugin to the latest version
- Update the plugin to this PR
- Manual edit the Google Table charts created before, with the 3.1.0 version (no matter the editor, Simple, Text or Excel, both in the Gutenberg editor or in the Visualizer library)

What happens is that after save, all the values in the table gets an `Array` before.
![download (1)](https://user-images.githubusercontent.com/3266155/82044114-6a023d00-96b5-11ea-9c60-73c540f4c0bd.png)

Regarding https://github.com/Codeinwp/visualizer-pro/issues/256 I've changed the `Precision `option to `-1` for one of the charts, and I got the same error mentioned in the issue, not sure if I'm missing anything
![Screenshot (6)](https://user-images.githubusercontent.com/3266155/82045934-9e2b2d00-96b8-11ea-9457-71910b210dc3.png)

**Comment by contactashish13** [comment]
@rodica-andronache v3.1.0 did not have google table charts - it had DataTable table charts. Also, google table charts was part of Pro so can you please mention the combination of free and pro you have used?

I believe you typed a precision of `-1` instead of selecting it using the number selector (which will not allow you to go below 0). I have handled that case as well.

**Comment by rodica-andronache** [comment]
@contactashish13 you were right, I wasn't using the right version. 
I've tested again the migration with Visualizer 3.0.12 and Visualizer PRO 1.7.8.

So, what I did is:
1. Install & activated Visualizer 3.0.12 and Visualizer PRO 1.7.8.
2. Create a few table charts
3. Update both plugins to their latest versions
4. Update the plugins to the new PRs

The only 2 issues I've seen are:
1. The old Table Google charts ( created with the old versions ) does not show up when filtering by type or library type.
Here are all the charts
![download (1)](https://user-images.githubusercontent.com/3266155/84251232-be160b00-ab15-11ea-851c-a5a71d07e019.png)
Filtering Google chart tables does not show those charts
![download (2)](https://user-images.githubusercontent.com/3266155/84251298-d554f880-ab15-11ea-92d3-b6a466dfde83.png)

2. If I use the Visualizer block to display any of the charts, and Manul Edit the chart, and click on the Save button, the button doesn't seem to work. It stays in a loading state forever.
![download (3)](https://user-images.githubusercontent.com/3266155/84251325-dede6080-ab15-11ea-8a95-c8c21259ebe6.png)

You can see this here
https://simple-moth.jurassic.ninja/
User: demo
Password: QIfhpw0Aex92oIG3pnXOxvDZ

**Comment by contactashish13** [comment]
@rodica-andronache When the old table charts are upgraded to the new version, an option gets inserted in the options (wp_options) table with a key of `visualizer-upgraded`, which shows the version of the plugin that you had active before upgrading to this new version. I don't see that in the database (I installed phpmyadmin plugin):

![image](https://user-images.githubusercontent.com/12953439/84343619-4fdd5100-abc6-11ea-84b3-5a813c3dfdfb.png)

Maybe this is related to the second problem I fixed below.

You may want to try this again on a new instance (or by using the WP Reset plugin to clear the database). Once you upgrade to this PR, you should see 2 options `visualizer-upgraded` and `visualizer-upgraded-from`.

The second problem should be okay now. It had something to do with the error you see even on the login page:

![image](https://user-images.githubusercontent.com/12953439/84344260-efe7aa00-abc7-11ea-8f45-4cd955f35694.png)

**Comment by rodica-andronache** [comment]
@contactashish13 the second issue was fixed. The first one still persists for me.
I've tried both on my local and on a new Jurassic instance here 
https://certain-hoary.jurassic.ninja/wp-admin/
User: demo
pass: Ok4PTb8DPu$Qi1Md%)P@zt7c
In both cases, filtering charts does not take into account the old Table Google charts.
Here are the two options in both cases:
on jurasssic: https://prnt.sc/syfmbh
on my local: https://prnt.sc/syfrxi

**Comment by contactashish13** [comment]
@rodica-andronache I'm not sure I understand the problem. You can see that the charts have had their types changed and they are visible in the library.

![image](https://user-images.githubusercontent.com/12953439/84620663-34d84d00-aef6-11ea-8d4f-294b4d51424d.png)

**Comment by rodica-andronache** [comment]
@contactashish13 
Here are all the charts
![download (13)](https://user-images.githubusercontent.com/3266155/84750325-cbbf0b00-afc3-11ea-8ba3-e88917395b7e.png)

Filtering Table GoogleCharts does not show the charts created with the old version
![download (14)](https://user-images.githubusercontent.com/3266155/84750351-d24d8280-afc3-11ea-94b9-6ada1902b5c0.png)

**Comment by contactashish13** [comment]
@rodica-andronache The screenshots helped! I've fixed this.

**Comment by rodica-andronache** [comment]
@contactashish13 that's working well now 👍 
Saw another issue which I think is related to these PRs ( tested with the current versions and the issue is not there ).
Similar to https://github.com/Codeinwp/visualizer/issues/688 when creating a `DataTable ` Table chart, insert it in a post using the Visualizer block, and clicking on Advanced Options, the block breaks. 
This happens just for DataTable Table charts, not Google Table charts.
<img width="1572" alt="Screenshot 2020-06-17 at 12 49 10" src="https://user-images.githubusercontent.com/3266155/84883717-8967fd80-b099-11ea-82c6-65153fa52c88.png">

**Comment by contactashish13** [comment]
@rodica-andronache have fixed this.

And also found another problem: in googlecharts formatting of date/number columns does not work in the block editor. I believe it is an issue even with the currently released version.

**Comment by rodica-andronache** [comment]
@contactashish13 I've tested again and everything seems right for me. If you can also fix the conflicts here https://github.com/Codeinwp/visualizer-pro/pull/264 I think we can merge these, if there aren't other things that you think needs to be done.

I didn't get exactly what's the new issue you've mentioned. If there's not something related to this maybe you can add it on git, with more details? 
Thanks

**Comment by contactashish13** [comment]
@rodica-andronache I've fixed the conflicts.

The issue I have found is this. Can you confirm this behavior at your end too? I'd prefer such issues to be created by you as you are able to provide more details than I can.

1) Create any type of core google chart  (line. bar, column etc)
2) Change formatting, which reflects on the chart. Save the chart.
![image](https://user-images.githubusercontent.com/12953439/85981359-b903f780-ba01-11ea-9a19-442e13db6e42.png)
3) Insert that chart in a block
4) Change formatting. It does not change anything. These fields don't seem to work for any chart.
![image](https://user-images.githubusercontent.com/12953439/85981606-1ac46180-ba02-11ea-898a-b141d4205482.png)

**Comment by rodica-andronache** [comment]
@contactashish13 is happening for me too, on the current version as well. I've added it here https://github.com/Codeinwp/visualizer/issues/724

**Comment by rodica-andronache** [comment]
@contactashish13 saw one more thing that I've missed before. In the `Help` tab, the tables are called now `Tabular` instead of `Table`, making the `Video Demo` link to point to a resource that doesn't exist.
![download (17)](https://user-images.githubusercontent.com/3266155/86032156-9264b180-ba3f-11ea-973d-011043bb54f1.png)

How it is in the current released version
![download (18)](https://user-images.githubusercontent.com/3266155/86032191-9e507380-ba3f-11ea-90ef-bfbe4cd333a5.png)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/725 should take care of this.
