### ISSUE TITLE
Combine one time import and schedule import

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#525]
merge the one-time csv import and the scheduled csv import into one as both are effectively the same feature.

![image](https://user-images.githubusercontent.com/12953439/64434562-6d810580-d0de-11e9-861f-52bbb535ec2c.png)

![image](https://user-images.githubusercontent.com/12953439/64434581-7e317b80-d0de-11e9-9418-df6969e77cc1.png)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/543 and https://github.com/Codeinwp/visualizer-pro/pull/210 

@DanyCaissy can you please test this?

**Comment by DanyCaissy** [comment]
@contactashish13 There is "Error during visual comparision job" on the 210. Should I still test now or should I wait for that to be fixed?

**Comment by contactashish13** [comment]
@DanyCaissy yeah that doesn't matter as long as the travis build is successful for any PR. 

![image](https://user-images.githubusercontent.com/12953439/66450136-06f05e00-ea75-11e9-9995-016040cd9152.png)

**Comment by DanyCaissy** [comment]
@contactashish13 

I've installed 543 and 210, however it seems there are issues: https://i.imgur.com/JRKtgfz.png

Only one-time is selectable, andd there is a lock on wordpress

**Comment by contactashish13** [comment]
@DanyCaissy no changes were made for import from wordpress. It might have to do with your license. Can you enable/disable the license (or whatever needs to be done for the license to re-register)?

**Comment by contactashish13** [comment]
@DanyCaissy can you please confirm if this is tested?

**Comment by DanyCaissy** [comment]
This is merged correctly, but I could not import the following file:

https://docs.google.com/spreadsheets/d/e/2PACX-1vQFRe6FW2AalDJ12FcQvhdgAe-uQQH9SutfOIVl7dYc-YtnJAoXJqy8HuQst3Ez2hMtWOqo2xzm9zvS/pub?output=csv

I get "You have entered an invalid URL. Please provide a valid URL.", why is that?

@contactashish13

**Comment by contactashish13** [comment]
@DanyCaissy this should be okay now. Can you please test again? You may want to clear your browser cache.

**Comment by DanyCaissy** [comment]
@contactashish13 This appears fixed now

**Comment by contactashish13** [comment]
@DanyCaissy I'm sure you must have tested this scenario as well but just mentioning it here in case you haven't - 

1. using the previous version, create a scheduled chart and a one time import chart
2. upgrade to this version/PR check that the 2 charts function correctly

**Comment by DanyCaissy** [comment]
@contactashish13  Yes that worked well too.

**Comment by rodica-andronache** [comment]
@contactashish13 tested with https://github.com/Codeinwp/visualizer/pull/561 and https://github.com/Codeinwp/visualizer-pro/pull/212.
With a Personal License, this upsells appears which doesn't look alright as all those options are available in the Personal package, except Live, which I can't see in any package. 
Can you please let me know how this should work? Thanks
<img width="1456" alt="Screenshot 2020-01-14 at 12 30 05" src="https://user-images.githubusercontent.com/3266155/72336838-38a73f80-36ca-11ea-9961-6e88a874556e.png">

**Comment by rodica-andronache** [comment]
I also wasn't able to test the schedule from an online csv file. I've tried the **Each hour** option, an also 6 minutes using this doc, but the chart was not updated.
https://docs.themeisle.com/article/1054-how-to-change-the-schedule-import-interval-in-visualizer
I'm not sure if I'm doing something wrong and how I could test this @contactashish13

**Comment by rodica-andronache** [comment]
In the end, the schedule seemed to work ok. I will let you know if there are other issues with that

**Comment by contactashish13** [comment]
@rodica-andronache I have addressed https://github.com/Codeinwp/visualizer/issues/525#issuecomment-574117125 in PR https://github.com/Codeinwp/visualizer/pull/613

TBH it may be a good idea to summarize here the expected behavior (please compare this against our pricing plans/marketing material and correct it so that there is no confusion. The terminology is also confusing so I'm using plan numbers not names):

- only free active
  - import from url - only one-time (upsell plan 1)
  - import from WP/DB - upsell this feature
- plan 1 active
  - import from url - see all schedules
  - import from WP/DB - only one-time (upsell plan 2)
- plan 2 active
  - import from url - see all schedules
  - import from WP/DB - see all schedules

Question: Do we need live updating of CSVs? That option never existed before. I'm not sure but I believe this was mentioned in one of the cards in Asana but we need to capture everything here and get rid of Asana so that there is one medium for everything.

**Comment by DanyCaissy** [comment]
@contactashish13 @rodica-andronache 

The expected behavior listed above looks fine to me. I think live CSV updates could be added, although 'live' could mean once every minute if necessary. My only worry here is if the CSV import takes longer than the interval, do we handle that case right now?

**Comment by contactashish13** [comment]
@DanyCaissy can you explain with a scenario what you mean by 

> if the CSV import takes longer than the interval

**Comment by DanyCaissy** [comment]
@contactashish13 

If the CSV import is ran every minute but each import takes 2 minutes to run.

**Comment by contactashish13** [comment]
@DanyCaissy currently the least count for refresh is 1 hour. If we add the live option, the refresh will take however long it takes to update.

**Comment by DanyCaissy** [comment]
There shouldn't be an issue then.

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/visualizer/pull/628 and https://github.com/Codeinwp/visualizer-pro/pull/236 add support for live updating of CSVs

**Comment by rodica-andronache** [comment]
updated here https://docs.themeisle.com/article/428-visualizer-charts-and-graphs-documentation/ what's included in each plan to make it easier to understand, for both QA and our users. If there are gonna be changes in the future, we should update that as well
