### ISSUE TITLE
Unable to add charts on front-end on wpsandbox

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#526]
This seems to be specific to wpsandbox instances. We want to use wpsandbox to allow users to try our features before purchasing. Due to that, it might not be reproducible locally.

When adding a chart on the front-end using "display an existing chart", we get this error right away: https://i.imgur.com/wmzFVUh.png

 If you want access to our wpsandbox account to try to recreate this on another instance, let me know.

**Comment by HardeepAsrani** [comment]
@DanyCaissy Can I get access to such sandbox so I can see the setup? If possible, with admin credentials?

**Comment by DanyCaissy** [comment]
@HardeepAsrani That does seem to be fixed on sandbox now

**Comment by HardeepAsrani** [comment]
YES! We did it, finally! :D

**Comment by DanyCaissy** [comment]
Woot woot! Don't get too happy though, the bug gods feed on happiness.
