### ISSUE TITLE
Color changes randomly, is saved even if not saved

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#529]
Comment from a user:

"Column colors change randomly when switching between data editor and chart view. The fun part: The last new colors are automaticaly saved even though I didn't save them"

I did notice this behavior as well.

Desired Behaviour: When a chart is created, the colors are generated randomly in some cases. I think that't fine, however, those colors should be recorded in the json settings and be permanent from then on.

**Comment by contactashish13** [comment]
Closing this as this is a duplicate of https://github.com/Codeinwp/visualizer/issues/517
