### ISSUE TITLE
"Load More" when less than 6 tables

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#532]
I feel like there was a ticket for this before...but I can't find it. Or maybe I just mentioned it on other tickets. If its duplicate feel free to close it.

--

The is a load-more button even when unnecessary: https://i.imgur.com/vxCpq1r.png

Or it will display empty spots. On this screenshot, there are 7 charts, one table, 3 google, 3 chartjs. The chartjs charts are what cause changes to the pagination, even though they should not count (we dont show chartjs charts yet)

ChartJS charts should be disregarded entirely from the front-end plugin.

**Comment by HardeepAsrani** [comment]
It's not possible to fix as the rest route sends 6 posts each time and then we have to display them. Once we implement chartsjs, this should be taken care of.

What do you think @contactashish13? If needed I try to modify and find a way but is this important for now?

**Comment by DanyCaissy** [comment]
@HardeepAsrani When do you think chartjs will be implemented?

The Rest route cannot use a condition to filter out chartjs charts for now?

If chartjs will be implemented within a month, I think this could be ignored. If fixing chartjs is expected to take much longer, I think it'd be worth resolving this first.
