### ISSUE TITLE
Is that possible change default MySQL save location? (1 post)

### ISSUE THREAD

**Issue by JiangWZ** [Codeinwp/visualizer#54]
I am wondering is that possible change default MySQL save location from current wp_fgbw_postmeta and wp_fgbw_posts file to another one (a new one), or even a new database. Which code in which file should I change?

I am very new for the SQL and wordpress plugin, so I will be very grateful if anybody can help me about this.

Many Thanks.

**Comment by selu91** [comment]
Hey,

No, for the moment this is not possible as it is using the wordpress core features.

Thank you for your request
