### ISSUE TITLE
Test with WP 5.3

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#540]
RC1 target date 15 Oct 2019

https://make.wordpress.org/core/5-3/

**Comment by HardeepAsrani** [comment]
Is this only for Gutenberg part or the entire plugin?

**Comment by contactashish13** [comment]
We have discussed this on slack. Here is my verbatim response from there :)

"Only Gutenberg. I'll test the rest"

**Comment by contactashish13** [comment]
@HardeepAsrani as RC1 is out, can you please test and update this issue? @DanyCaissy can you also lend a hand here so that we can be sure everything works on RC1? https://wordpress.org/news/2019/10/wordpress-5-3-release-candidate/

**Comment by HardeepAsrani** [comment]
I've tested and it works fine for me. Can you do it @DanyCaissy to double confirm? Also, make sure to have your browser's console open while doing it. :D

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/557 ups the "tested upto"

**Comment by DanyCaissy** [comment]
@HardeepAsrani @contactashish13 Which PRs would I test here, for both free and pro?

**Comment by HardeepAsrani** [comment]
@DanyCaissy You will have to test this https://github.com/Codeinwp/visualizer/pull/549

You can test it with both Free & Pro. Let me know if you need any help, on Git or Slack. :)

**Comment by DanyCaissy** [comment]
@HardeepAsrani  @contactashish13 

I could not find any difference witih the new WP version. No bugs that I could find.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/568 will be used to release v3.3.2 with just WP 5.3 support
