### ISSUE TITLE
Number Format for Data Series in Column Chart only applied in Chart Preview

### ISSUE THREAD

**Issue by jdcast** [Codeinwp/visualizer#542]
When using Google Charts engine and producing a column chart, the `Chart Settings -> Series Settings -> Number Format` formatter in the chart editor is applied in the `Chart Preview` area in the wp admin panel but is not applied in the final rendered chart in my wp website page when using the following `Manual Configuration`:

```
{
"vAxes": {
          "0": {
            "title": "Notional Advised (bn)", 
            "ticks": [10, 30, 50],
            "titleTextStyle": {"italic": "false"},
            "gridlines": {"color": "light-gray"},
            "maxValue": 50,
            "format": "$#"
          },
          "1": {
            "title": "Clients Advised", 
            "ticks": [10, 30, 50],
            "titleTextStyle": {"italic": "false"},
            "gridlines": {"color": "light-gray"},
            "maxValue": 50
          }
        },
"series": {
          "0": {
            "targetAxisIndex": "0", 
            "color": "#b7d988"
          },
          "1": {
            "targetAxisIndex": "1", 
            "color": "#aedeea"}
        },
"italic": "false", 
"fontName": "Arial",
"fontSize": 16,
"hAxis": {
  "tickColor": "white"}
}
```
 
I've looked for a manual configuration option to get the series' number formatting back, but haven't come across anything in Google Charts' docs: https://developers.google.com/chart/interactive/docs/gallery/columnchart#dual-y-charts

Any ideas or workarounds?

Thanks!

**Comment by contactashish13** [comment]
@jdcast if you remove the `series` portion of the manual configuration, do you see the formatting applied?

```
"series": {
          "0": {
            "targetAxisIndex": "0", 
            "color": "#b7d988"
          },
          "1": {
            "targetAxisIndex": "1", 
            "color": "#aedeea"}
        },
```

**Comment by jdcast** [comment]
@contactashish13 Yes, the formatting is applied if I remove this.  Though, due to client requirements, I need this `series` portion of the manual configuration.

**Comment by contactashish13** [comment]
@jdcast in that case you may need to provide the formatting as part of the manual configuration because that is applied after the rest of the settings have been applied.

**Comment by jdcast** [comment]
@contactashish13 what are the formatting option(s) for this?  As mentioned in my original question, I have so far failed to find any documentation revealing this particular formatting option within Google Charts' docs.

**Comment by contactashish13** [comment]
@jdcast please search for `hAxis.format`  in https://developers.google.com/chart/interactive/docs/gallery/columnchart#configuration-options

**Comment by jdcast** [comment]
`hAxis.format` seems to be have no effect.  However, it seems that the issue I've encountered may be an open item for Google Charts `options`: https://github.com/google/google-visualization-issues/issues/530?

Is it possible to use the `NumberFormat` class from Google Charts in Visualizer?  I'm looking to be able to do what was done in this SO post https://stackoverflow.com/questions/51704424/tooltip-number-formatting-in-google-chart to format the data value in the tooltip.

**Comment by contactashish13** [comment]
@jdcast if you are comfortable with javascript and can see a way to add this in, please feel free. We'd love to know about it. If you feel you can add a generic implementation, you can also create a PR. But we cannot really provide custom code for our free users.

**Comment by contactashish13** [comment]
Closing this as this is not an issue with the plugin but with the API
