### ISSUE TITLE
Add existing features to block editor

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#544]
- import from json
- import from db

**Comment by HardeepAsrani** [comment]
This adds import from db feature https://github.com/HardeepAsrani/visualizer/commit/8abf98c1b81ceeede30bd9e027628c5f37b7115c

**Comment by HardeepAsrani** [comment]
This adds import from JSON feature: https://github.com/HardeepAsrani/visualizer/commit/cc30e162f61e800d114ad5e4b13cfb2d48bb6538

We can test now. cc @DanyCaissy @contactashish13? 

Give these one a throughout testing as they're little complex in terms of data handling so make sure I've missed nothing. :)

**Comment by DanyCaissy** [comment]
@HardeepAsrani 

I was able to import from http://swapi.co/api/people properly.

I could not import from this: https://jsonplaceholder.typicode.com/posts, the error says its not valid json. Is there a reason for that?

Database import was working that I could tell so far.

Whenever I click "import from other charts" I get this error:

Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%2C%20fontColor%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at N (http://wptesting.localdev/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:9:408)
    at q (http://wptesting.localdev/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:10:176)
    at T (http://wptesting.localdev/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:15:496)
    at V (http://wptesting.localdev/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:16:125)
    at Object.forEach (http://wptesting.localdev/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:29:209)
    at Yh (http://wptesting.localdev/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:47:335)
    at Bd (http://wptesting.localdev/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:47:431)
    at Mg (http://wptesting.localdev/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:139:99)
    at Qg (http://wptesting.localdev/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:144:281)
    at Rg (http://wptesting.localdev/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:145:76)

**Comment by HardeepAsrani** [comment]
@DanyCaissy It doesn't work with all JSON imports, so that's not an issue with the block but how the integration works.

Is the website up so I could test it with the chart import? Must be some invalid syntax. Let me know if you can provide me with the instance online so I could try it and see. :)

@contactashish13

**Comment by contactashish13** [comment]
https://github.com/DanyCaissy if a url works with the classic visualizer it should work with the block editor. If it doesn't work with the former, can you please create a new issue so that all such sources can be investigated and supported, if possible.

**Comment by DanyCaissy** [comment]
@contactashish13 This is something that had only happened with this PR.

**Comment by contactashish13** [comment]
@HardeepAsrani please make sure all JSON feeds that work on classic work with gutenberg too.

**Comment by HardeepAsrani** [comment]
@contactashish13 @DanyCaissy That URL also doesn't work with the classic Visualizer editor.

<img width="1680" alt="Screen Shot 2019-11-04 at 12 55 28 PM" src="https://user-images.githubusercontent.com/2649903/68104791-70437f80-ff02-11e9-974e-09cefa878148.png">

**Comment by contactashish13** [comment]
@HardeepAsrani it works with the PR in https://github.com/Codeinwp/visualizer/issues/481 where I added support for many types of JSON feeds. Please try with that and support these.

**Comment by HardeepAsrani** [comment]
@contactashish13 Given that we've changed the default root from `root > results` to `root`, it's causing an issue on older JSON URLs. The error is there in both versions but it's more visible on Gutenberg.

<img width="833" alt="Screen Shot 2019-11-06 at 3 56 07 PM" src="https://user-images.githubusercontent.com/2649903/68290492-09fb6000-00ae-11ea-862e-322484284db1.png">

It's returning Array in the table. While on Gutenberg, it's doing the same along side:

```Notice: Array to string conversion in /var/www/html/wp-content/plugins/visualizer/classes/Visualizer/Render/Layout.php on line 443```

Which is the line adding that array element to the table.

This error is not visible in the classic Visualizer editor but is added to the debug log, so it's happening in both places. I guess we should remove the `root` as default if `root>results` is available.

What do you think?

**Comment by HardeepAsrani** [comment]
@DanyCaissy Yes, that issue was wrong. :)

Now you should be able to use the feed which didn't work previously, like WP Rest's API.

**Comment by DanyCaissy** [comment]
@HardeepAsrani Which PR?

**Comment by HardeepAsrani** [comment]
It's the same PR. You just need to run git pull to pull the latest changes: https://github.com/Codeinwp/visualizer/pull/549

**Comment by DanyCaissy** [comment]
@HardeepAsrani Works fine now
