### ISSUE TITLE
Inconsistency in saving schedule

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#556]
In JSON import, the meta for the schedule is only created when you click on "Save Schedule" while in Database import it is created even if you don't click on Save schedule.

<img width="748" alt="Screen Shot 2019-10-21 at 12 05 36 PM" src="https://user-images.githubusercontent.com/2649903/67181742-1ff4f980-f3fb-11e9-8c85-b9aa347eb353.png">

So one of them is a little inconsistent. @contactashish13

**Comment by contactashish13** [comment]
Closing this as it will be handled as part of https://github.com/Codeinwp/visualizer/issues/481
