### ISSUE TITLE
JavaScript Error before submit or clone

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#558]
Upon creation or duplication of a new chart, there is a JS error that shows up for like 0.5 second. It might not cause any issues but could be looked at: https://i.imgur.com/n9jjzhM.png

**Comment by contactashish13** [comment]
@DanyCaissy the error seems like it is being triggered by some chrome extension you are using. Do you get the error when you disable it?

**Comment by DanyCaissy** [comment]
It was caused by the axe extension. Closing
