### ISSUE TITLE
Adding 'Table' type

### ISSUE THREAD

**Issue by robbie-remote** [Codeinwp/visualizer#57]
Can the Google Chart Tools 'Table' type be added to the Visualizer plugin for WordPress? The 9 chart types are great, I'm wondering about adding a type for basic table visualization of the data.  

    https://developers.google.com/chart/interactive/docs/gallery/table?hl=en

Would it be hard to add this? Is anybody already working on it?

**Comment by selu91** [comment]
Hey,

Thank you for your feedback. We will look to integrate it in the next releases.

**Comment by robbie-remote** [comment]
I started on this feature, and have something partially working but not 
complete. You can see a demo here:

     http://www.robbie-remote.com/?iot_device=1

Look at the table of dates & values (below the fold).

Do you want me to push my changes into this git, when I reach a 
consistent checkpoint?

**Comment by selu91** [comment]
Yes, we would be very greatful if you could.

Thank you !

**Comment by selul** [comment]
Added in the pro version of 1.0.5
