### ISSUE TITLE
block editor embed charts confusion

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#577]
@DanyCaissy when I try to click display an existing chart the current behaviour and message is very confusing : https://www.dropbox.com/s/m6hnvz4g6rdkgan/Screenshot%202019-11-13%2009.37.31.png?dl=0

https://www.dropbox.com/s/m6hnvz4g6rdkgan/Screenshot%202019-11-13%2009.37.31.png?dl=0

There are lots of existing charts and they are not chartsjs based.

**Comment by DanyCaissy** [comment]
@ineagu Are you able to reproduce it on a https://jurassic.ninja/ instance?

I haven't encountered this yet.

**Comment by ineagu** [comment]
I got another error on jurassic : https://www.dropbox.com/s/ud6bk5a0sr9oxon/Screenshot%202019-11-13%2017.40.52.png?dl=0

https://excessive-constrictor.jurassic.ninja will be destroyed in 7 days. Sign out and sign in to get 7 more days.
WP user: demo WP/SSH password: uYmr1Fb53DoD

https://excessive-constrictor.jurassic.ninja/wp-admin/post.php?post=9&action=edit

**Comment by DanyCaissy** [comment]
I thought this might be an instance issue but I was able to reproduce it on another instance.

The steps were just:

1- Create a new jurassic instance
2- install visualizer free from store
3- create a default table
4- create a post
5- attempt to open the gutenberg visualizer view

https://i.imgur.com/HwisNDO.png

@contactashish13 Any idea what might have broken this?

**Comment by contactashish13** [comment]
@HardeepAsrani is this a problem with 5.3?

**Comment by HardeepAsrani** [comment]
Fixed it in https://github.com/Codeinwp/visualizer/pull/582 @contactashish13
