### ISSUE TITLE
Manual data tab to show options for multiple editors

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#579]
https://app.asana.com/0/1129400186358085/1148817325462121/f

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/visualizer/pull/594 and https://github.com/Codeinwp/visualizer-pro/pull/227

These should also take care of #580 for manually edited charts.

There are the following scenarios here:
- old free + new pro - only Excel editor
![image](https://user-images.githubusercontent.com/12953439/69123142-9eaa8880-0ac6-11ea-97f7-fbd343b6d48a.png)

- new free + old pro - only Excel editor
![image](https://user-images.githubusercontent.com/12953439/69123142-9eaa8880-0ac6-11ea-97f7-fbd343b6d48a.png)

- new free + new pro - all 3 editors
![image](https://user-images.githubusercontent.com/12953439/69123356-2abcb000-0ac7-11ea-8b25-96083d801273.png)

- new free only - only 2 editors

@DanyCaissy can you please test?

**Comment by DanyCaissy** [comment]
@contactashish13 This is fine now

**Comment by rodica-andronache** [comment]
@contactashish13 saw a small thing which I think it's related to this issue.
If you have a larger table chart https://prnt.sc/qlscav, and try to edit it in the **Simple** editor, the scroll doesn't allow you to see all the columns in the table https://prnt.sc/qlsbzv

**Comment by rodica-andronache** [comment]
also, tested all the scenarios and in this one: 
old free + new pro - Clicking on View Editor does nothing for me ( does not open the editor ).
I don't think this is a big deal, as they should update both plugins, but thought to share it, in case it can be fixed easily

**Comment by contactashish13** [comment]
@rodica-andronache do you get any error in the console?

**Comment by contactashish13** [comment]
@rodica-andronache this is not something that can be fixed easily.

**Comment by rodica-andronache** [comment]
ok, it's not something big, if it's difficult to fix
