### ISSUE TITLE
add new chart ui pattern

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#581]
@DanyCaissy this ui pattern for me is rather confusing, search/add are completely different actions, I would think the icon means soemthing else, I would rather remove that and add a mockup chart in the list with "add new" , or just remove : https://www.dropbox.com/s/phkqpxad4f9jcwp/Screenshot%202019-11-13%2017.39.59.png?dl=0

**Comment by ineagu** [comment]
feel free to close if don't agree

**Comment by DanyCaissy** [comment]
@ineagu I'm not sure I understand fully. 

When there are no charts of that type the user is invited to create one this way: https://i.imgur.com/9vMxS8c.png

Is that the part that you don't like?

**Comment by contactashish13** [comment]
@ineagu @DanyCaissy are we clear on what this issue is? I'm confused :)

**Comment by rodica-andronache** [comment]
I think it's about this part, which I find confusing also, at first
![download (5)](https://user-images.githubusercontent.com/3266155/71895975-2887e100-315b-11ea-96c2-c42b032b3698.png)

**Comment by DanyCaissy** [comment]
I think for now we could just remove the +. There is already a mockup chart and there is an "add new".

For bigger changes we can wait until we rework that interface.

Thoughts?

@contactashish13 @rodica-andronache

**Comment by rodica-andronache** [comment]
I think it would be a good idea

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/607 removes the + button

**Comment by rodica-andronache** [comment]
#607 is working well for me
