### ISSUE TITLE
DataTable charts - Infinity Pagination

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#585]
If you put 0 or empty in the number of rows per page, you get this: 

https://i.imgur.com/5CGnpss.png

This could be mildly confusing for some users.

Instead, if the value is 0 or empty, we could default it to 1.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/592

**Comment by DanyCaissy** [comment]
Fixed
