### ISSUE TITLE
Breaking Bug- Visualizer prevents creation of new posts

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#586]
Steps:

1- Initialize new wordpress instance
2- Install Visualizer 3.4.0
3- Attempt to create a new post (https://administrative-fin.jurassic.ninja/wp-admin/post-new.php)

Result: https://i.imgur.com/lr5pImh.png

Happened on local and reproduced on jurassic below:

https://administrative-fin.jurassic.ninja 
WP user: demo WP/SSH password: DJTabOdAVBAa

**Comment by contactashish13** [comment]
@DanyCaissy Renaming this as this is an error with testing of 3.4 and not an issue with the current/past plugin version. It does not merit an issue per item. Let's track all instances of this testing here.  I will close all issues related to testing of 3.4.0 and track them here.
