### ISSUE TITLE
Buy Now is not displayed properly

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#587]
On 3.4 free only:

![2019-11-17_18-10-30](https://user-images.githubusercontent.com/5183243/69015796-feeedc80-0997-11ea-9aaf-53b2a7135cb4.gif)

Import from database or wordpress are not showing the "Buy Now" properly.

**Comment by DanyCaissy** [comment]
Happens on other types of charts too, on a new instance with just 3.4.0

**Comment by contactashish13** [comment]
Closing and resolving as per https://github.com/Codeinwp/visualizer/issues/586#issuecomment-554836561
