### ISSUE TITLE
Bubble settings not clear

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#588]
https://i.imgur.com/AKac2z5.png

- I haven't noticed a difference with "sort bubbles by size", is that because the default data doesn't allow to see the change? If so, could we change the default data to make this change visible?
- The sizemax and sizemin don't really seem to work properly, putting any number on sizemax will turn every bubble into the largest bubble available, sizemin does very little. If that's really how it's intended to work, maybe we should add a link that explains these values better.

**Comment by contactashish13** [comment]
@DanyCaissy 

1) I couldn't either. Have added the feature anyways. If you can reproduce on a jsfiddle, let me know.

2) you can check this out if it makes sense: https://developers.google.com/chart/interactive/docs/gallery/bubblechart#configuration-options and let me know what text needs to be added to make it clearer

**Comment by DanyCaissy** [comment]
If there is no bug in the implementation then this is fine, just wanted to make sure.
