### ISSUE TITLE
Visualizer Lite notification when lite is installed

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#589]
https://i.imgur.com/xQXzk9L.png

Both 3.4 and 1.9.2 are installed and this notification appears, it should not appear

**Comment by contactashish13** [comment]
@DanyCaissy this only happens when pro is active and free is either not installed or active. Please use a public instance where this can be reproduced

**Comment by DanyCaissy** [comment]
Of course I know that.

You can reproduce it here:

https://severe-storm.jurassic.ninja/wp-admin/options-general.php
https://i.imgur.com/wxDkVzw.png

https://severe-storm.jurassic.ninja
WP user: demo WP/SSH password: If9aG4hX1NG8

**Comment by contactashish13** [comment]
@DanyCaissy this is because the visualizer plugin is named `Codeinwp-visualizer-43889df`. If you rename it to the correct name, it should not be a problem

![image](https://user-images.githubusercontent.com/12953439/69211059-c95a1700-0b82-11ea-86da-7ad13b5a45d9.png)

**Comment by DanyCaissy** [comment]
@contactashish13 

Ah okay, so this happens due to the way I download the plugin, and it wouldn't happen to a normal user.

I'll close this then.
