### ISSUE TITLE
Charts in library don't load after F5 Refresh (half the time?)

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#591]
![2019-11-17_20-14-31](https://user-images.githubusercontent.com/5183243/69017804-82fd9000-09a9-11ea-8ef3-936c5ea7c971.gif)

Exactly half the time, the charts dont refresh properly after a f5 refresh. a Full reload (ctrl shift R) does the same thing.

This is using the newest version of chrome.

Please fix and test in other browser.

**Comment by DanyCaissy** [comment]
Note:

It might be a specific chart causing it. this page sometimes doesnt load:

https://i.imgur.com/0Js0jCA.png

But this page always loads:

https://i.imgur.com/BNzbz5b.png

**Comment by contactashish13** [comment]
@DanyCaissy There are 2 ways to trace this. Either with logs (in case there is an error in one of the charts) or by deleting each chart you have created and then reloading.

**Comment by contactashish13** [comment]
@DanyCaissy @SilviuDinu was able to reproduce it on an instance with just 1 google chart.

**Comment by contactashish13** [comment]
@DanyCaissy have fixed this in the 3.4.0 branch.

**Comment by DanyCaissy** [comment]
Fixed

**Comment by DanyCaissy** [comment]
I can reproduce this bug again...I'm not sure why it came back. To reproduce it:

https://rising-stork.jurassic.ninja
WP user: demo WP/SSH password: FIoifVIXUztT

Go to this page: https://rising-stork.jurassic.ninja/wp-admin/admin.php?page=visualizer

F5 multiple times, half of the time the charts don't load

**Comment by contactashish13** [comment]
@DanyCaissy I can't reproduce it unless I pressing F5 multiple times a second (which is not what any user would do). If that's not the case, can you provide a screen recording?

**Comment by DanyCaissy** [comment]
@contactashish13 

Ah, it does seem to happen mostly if we refresh quickly. For me, if you refresh within 1 to 2 seconds, it will be loading.

![2019-11-26_10-03-19](https://user-images.githubusercontent.com/5183243/69614819-1a12b980-1034-11ea-9302-1cb572813073.gif)

In that case it is just a minor annoyance.

**Comment by contactashish13** [comment]
@DanyCaissy can you also test wrt https://github.com/Codeinwp/visualizer/issues/600#issuecomment-559020654 as these are related?
