### ISSUE TITLE
change colors of chart values

### ISSUE THREAD

**Issue by selu91** [Codeinwp/visualizer#60]
I would like to have the option to change the color of my values. 
![qq](https://cloud.githubusercontent.com/assets/3330746/12143094/575e019a-b486-11e5-88ef-cfcd1c6cfdbf.jpg)
 (in that example the grey numbers 00 to 23.00)

**Comment by spalinger** [comment]
It's not a bug, it's just not implemented yet. This would be relatively easy to implement.
`hAxis: {textStyle:{color: 'white'},
vAxis: {textStyle:{color: 'white'}`

**Comment by selu91** [comment]
@spalinger thank you for your help.
