### ISSUE TITLE
Having SCRIPT_DEBUG on causes issues in real time update of charts

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#602]
https://wordpress.org/support/topic/chart-does-not-update-after-clicking-save-show-chart-with-script_debug-on/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/605 addresses this.

@SilviuDinu @DanyCaissy can you please test this to make sure it does not inadvertently affect anything else?

**Comment by DanyCaissy** [comment]
@contactashish13 

I am still getting this error with PR605, as per this video:

![2019-12-27_20-14-30](https://user-images.githubusercontent.com/5183243/71516743-a0494680-28e5-11ea-96ad-dbb4185ca904.gif)

This was after adding the debug line and restarting my local wamp:

https://i.imgur.com/dRPGXCr.png

**Comment by contactashish13** [comment]
@DanyCaissy can you test after clearing your browser cache?

**Comment by DanyCaissy** [comment]
@contactashish13 

I've tried multiple ways and browsers but the error always happens to me, even after clearing the cache. 

This is with firefox after clearing cache

![2020-01-04_09-50-53](https://user-images.githubusercontent.com/5183243/71758233-2f52f180-2ed8-11ea-8d4c-c3ee633229ff.gif)

**Comment by contactashish13** [comment]
@Codeinwp/support @mileamadalin need help testing this as well.

**Comment by rodica-andronache** [comment]
@contactashish13 I've tested with https://github.com/Codeinwp/visualizer/pull/605 with `define('SCRIPT_DEBUG', true);` and I also still get that console error each time I click on **Show Chart** after editing the chart even though after clicking **Save Chart** the chart is saved well.
I've tested with multiple types of charts and the same thing happened.

Here's a video of it https://www.loom.com/share/e96654fad8754528ac61e6b4ce710d4d

**Comment by rodica-andronache** [comment]
@contactashish13 this is still happening for me with https://github.com/Codeinwp/visualizer/pull/605

**Comment by contactashish13** [comment]
@rodica-andronache the function is now defined so its strange. did you refresh the cache? Are you getting the same error as in the previous video using the same workflow?

**Comment by rodica-andronache** [comment]
@contactashish13 yes, I get the same error using the same workflow. and I've tried clearing the cache.
I think the error might come from here https://github.com/contactashish13/visualizer/blob/issue-602-1/classes/Visualizer/Render/Page/Update.php#L54
If I remove that line, the error disappears. 
But the chart is still not updated
