### ISSUE TITLE
When new data is imported using csv/url, the manual editor still shows old data

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#610]
After importing data from a CSV file ( without saving the chart ), when you try to edit the chart, the default values appear in the editor, and you lose the imported data. 

Could we at least have a small notice there, in the Manual Data panel, to let users know that they need to first save the chart or something similar?

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/630
