### ISSUE TITLE
Table chart: Error appears when trying to import from JSON

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#611]
I've tried the import from JSON using multiple sources, and I was not able to actually create a chart. All the time I get an error that can be visible in this video

https://www.loom.com/share/bdcdd6298d48457eb939cd88bd081ab3

As a source, I've used http://dummy.restapiexample.com/api/v1/employees

Error explanation: https://datatables.net/manual/tech-notes/4

**Comment by contactashish13** [comment]
@rodica-andronache I believe this happens only for table charts. In other charts JSON feed works as expected.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/614

**Comment by rodica-andronache** [comment]
@contactashish13 I've tried this again with the https://github.com/Codeinwp/visualizer/pull/614, and now is working well to create the chart.
The issue is when you are trying to create a post with that chart, in the Gutenberg editor. The same error appears.
Using the classic editor, displaying the chart is working well.
New video: https://www.loom.com/share/2b3b4ce131ba480f80e65fc8b6e524b8

**Comment by contactashish13** [comment]
@rodica-andronache have address this issue.

**Comment by rodica-andronache** [comment]
@contactashish13 is working well. Feel free to fix the conflicts and merge https://github.com/Codeinwp/visualizer/pull/614
