### ISSUE TITLE
Download charts as images

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#625]
Some users have requested being able to download a png image of the charts they have created.

Let's evaluate adding an "download as png" button. If it's not much harder, export to pdf/other formats could be added.

A few links I found about this:

Google Charts: https://jsfiddle.net/kujxsn7z/
DataTables: https://stackoverflow.com/questions/27041467/jquery-datatable-export-to-png
ChartJS: https://stackoverflow.com/questions/20206038/converting-chart-js-canvas-chart-to-image-using-todataurl-results-in-blank-im

**Comment by contactashish13** [comment]
@DanyCaissy this functionality already exists for charts that support it out of the box. Use the `print` button and see. Charts that do not support conversion into image will instead print the data.

For the time being, we can add another `download image` action and enable it only for those charts that support this. For the remaining, we can add this support at a later date if customers call for it.

Let me know

**Comment by DanyCaissy** [comment]
@contactashish13 Regarding the ones that don't support it directly, could you investigate how feasible it would be to get it to work and how long it might take to do so?

**Comment by contactashish13** [comment]
@DanyCaissy what is not supported out of the box, is not supported by the library so there is nothing we can do to support it without using an external tool, which is an overkill when most of the charts support it. As mentioned earlier, this can be explored at a later date

**Comment by DanyCaissy** [comment]
Okay, if most of the charts support it it should be fine then. For the charts that don't, a greyed/disabled button will be fine.

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/visualizer/pull/690 and https://github.com/Codeinwp/visualizer-pro/pull/265 add this feature. 

- This checkbox will be disabled for Table and Gauge charts (and this checkbox will not appear in the block editor for these chart types).
![image](https://user-images.githubusercontent.com/12953439/81069606-bd2eff80-8eff-11ea-8f65-5ac2284a9ce8.png)

- If this checkbox is checked, the front end will show the action. Clicking that action will download the image prefixed with the chart title or with the chart id if no title has been provided.
![image](https://user-images.githubusercontent.com/12953439/81070205-8ad1d200-8f00-11ea-86ff-31c7fb53cd0c.png)


**Note that travis build for https://github.com/Codeinwp/visualizer-pro/pull/265 will pass after https://github.com/Codeinwp/visualizer/pull/690 is merged with master**

**Comment by DanyCaissy** [comment]
@contactashish13 

I didn't specify that in the ticket so that'd my bad, but could you also add this option on the quickbar in the library?

https://i.imgur.com/85nuUQj.png

**Comment by contactashish13** [comment]
@DanyCaissy added this in the library and have updated the description: https://github.com/Codeinwp/visualizer/issues/625#issuecomment-624055487
