### ISSUE TITLE
Improve pagination on visualizer library

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#626]
There is a limit of 6 charts on the library, however, some users might want to view more charts at a time.

There are two potential solutions for that:

A) Add "ajax pagination", so scrolling down would display more charts.
B) Adding an "items per page" select box, with a default of 6.

If A) is not possible/too cumbersome, we can do B), in that case, we would want the default to be 6 items per page, and upon being changed, the setting should be preserved.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/633

The pagination will be part of `Screen Options`

![image](https://user-images.githubusercontent.com/12953439/73841454-b6311c00-4840-11ea-8b83-19082e8e1053.png)


@DanyCaissy if this works well, please move it to the QA bin

**Comment by DanyCaissy** [comment]
@contactashish13 It works well as far as I've tried.

One thing is that it is not very visible, it's likely most users would not notice it. 

We could put it on the bottom right here: https://i.imgur.com/RsSfvvq.png

**Comment by contactashish13** [comment]
Unfortunately screen options is a WP default and that's how and where it shows. Anyone familiar with WP would know what it is.

**Comment by DanyCaissy** [comment]
That's fine then
