### ISSUE TITLE
Basic filtering/ordering system

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#627]
For users with multiple charts, filtering through them right now or ordering them would be a hassle.

Building a full-fledged filtering system might not be worth it (unless you can find a plugin to do that easily) but a simple system would be much better than nothing.

We could filter with some of the main fields:

* Library used (Any Library, ChartJS, Google Charts, Datatables)
* Date Range (All time, last day, last week, last month, last year)

We could also let the user customize the ordering, let them order by:

Field: Date, Name or Library
Order: Ascending or Descending

Overall if we want to keep it simple it could look like this: https://i.imgur.com/vhKcaxh.png

If there are other fields we should consider for sorting or ordering let me know.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/632

It looks like this: 
![image](https://user-images.githubusercontent.com/12953439/73815107-f2e22080-480a-11ea-90e9-95e358bf4af0.png)

@DanyCaissy can you check if this is what you had in mind? If all is okay, you can move it to the QA bin.

**Comment by ineagu** [comment]
a small note, would be great to show the filters only when the user has > x charts, for 3-4 charts, it would just crowd the admin probably

**Comment by DanyCaissy** [comment]
@contactashish13 

Works great!

One minor thing, can you avoid adding empty parameters in the URL? Ex: "&library&date&source&s".

**Comment by DanyCaissy** [comment]
@contactashish13 

Regarding Ionut's comment. It could be a nice to have but we would have to take into account pagination.

Essentially, the condition would be:

"If all charts fit into a single page (# charts <= perPage) AND there are 6 charts or less", hide the filter menu.

If you think that wouldn't be too troublesome we can add that in.

**Comment by contactashish13** [comment]
@DanyCaissy yeah that can be done but as they are part of different PRs this needs to be added as a separate issue, maybe for the next release (after the PRs are merged)

**Comment by DanyCaissy** [comment]
Alright

**Comment by rodica-andronache** [comment]
@contactashish13 is working well for me as well. If you can fix the conflicts we can merge https://github.com/Codeinwp/visualizer/pull/632

**Comment by contactashish13** [comment]
@rodica-andronache this is ready to go
