### ISSUE TITLE
Unable to Edit a Chart

### ISSUE THREAD

**Issue by adamscott-enfinitas** [Codeinwp/visualizer#63]
Created a chart using CSV upload. Go back to edit, click the edit button and it opens a blank JS window which then does nothing.

**Comment by adamscott-enfinitas** [comment]
Name	Protocol	Method	Result	Content type	Received	Time	Initiator
http://sheptonaircadets.org/wp-content/mu-plugins/gd-system-plugin/js/iframeResizer.map	HTTP	GET	404	text/html		2.83 s	XMLHttpRequest

**Comment by selu91** [comment]
@adamscott-enfinitas it seems there is a conflict with that plugin.

All should go just fine after.

**Comment by adamscott-enfinitas** [comment]
What kind of a response is this, and who said you could close the ticket?!

Adam Scott MInstLM
Technical Director | Enfinitas
m | 07540 050234
uk | 0845 524 0970
us | (405) 708-5678

On 28 May 2016, at 00:01, Marius Cristea <notifications@github.com<mailto:notifications@github.com>> wrote:


@adamscott-enfinitas<https://github.com/adamscott-enfinitas> it seems there is a conflict with that plugin.

All should go just fine after.

-

**Comment by selu91** [comment]
Hello,

The problem is caused by another plugin, gd-system-plugin, and it should work just fine after you disable it.

If you still have problems you can reopen the issue.

Thank you !
