### ISSUE TITLE
Allow apostrophes in charts

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#637]
If I add it in the `Text editor`, it gets transformed in a `double quote`
![download (2)](https://user-images.githubusercontent.com/3266155/74156948-0da80100-4c20-11ea-9975-3c7001255e6e.png)
![download (3)](https://user-images.githubusercontent.com/3266155/74156955-139de200-4c20-11ea-9abb-ffa06c820174.png)

and in the `Simple editor`, it gets transformed into `\'`
![Screenshot (2)](https://user-images.githubusercontent.com/3266155/74157052-447e1700-4c20-11ea-8360-510fe5ff79f8.png)
![Screenshot (3)](https://user-images.githubusercontent.com/3266155/74157074-5364c980-4c20-11ea-81a7-871e797d7831.png)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/641
