### ISSUE TITLE
update Tested up to

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#642]
![Screenshot](https://user-images.githubusercontent.com/3266155/74441583-c36d8c80-4e78-11ea-924d-1399961b7580.png)

**Comment by contactashish13** [comment]
I think something went wrong with the release. Last updated was updated when WP 5.3 came out so it can't go back to 3.4.0. Can you please check?

**Comment by rodica-andronache** [comment]
@contactashish13 it's because the readme.txt file is not valid, due to those `**` https://github.com/Codeinwp/visualizer/blob/master/readme.txt who weren't there in the previous version. Not sure how the file gets generated. Do you have any idea?

**Comment by selul** [comment]
@contactashish13 you broke it with this commit https://github.com/Codeinwp/visualizer/commit/363d9241da8e630e1fbf2fc470d674b93d86df44#diff-eb6b6c90251ab33cee784713c451e6d8

@rodica-andronache I will commit with the proper readme.txt on the SVN repo
