### ISSUE TITLE
Can't modify animation parameters for Gauge Chart

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/visualizer#648]
According to the [documentation](https://developers.google.com/chart/interactive/docs/gallery/gauge) I should be able to write the following JSON configuration and be able to change the animation duration and the easing for the Gauge Chart.

`{ "animation": { "duration": 5000, "easing": "inAndOut"} }
`
However, nothing happens when I add this code to Manual Configuration.

If I add something like: 
`{"max": 85, "animation":{"duration": 5000, "easing": "inAndOut"}}` Only the maximum value is changes to 85, but that's all.

There is no error or anything, just nothing happens.
I'm not sure if I'm doing this wrong but I would appreciate your advice here.

**Comment by contactashish13** [comment]
@SilviuDinu can you also mention what you expect the behavior to be when you set those parameters? I hope you are aware that animation happens on page load, not when you view the chart.

**Comment by SilviuDinu** [comment]
@contactashish13 I would expect the behavior to be like on this fiddle -> http://jsfiddle.net/73wztez3

**Comment by contactashish13** [comment]
@SilviuDinu Can you explain this in the context of "I hope you are aware that animation happens on page load, not when you view the chart."

> The duration should not affect the chart loading time, just the transition to the value itself

**Comment by SilviuDinu** [comment]
@contactashish13 from your explanation, I understand that no matter what modifications I would bring to the animation, it won't be visible for me, as it happens during page load.

However, does this apply as well even if the chart is placed in the topside of the page (aka I can see the chart all the time even during a refresh)?

**Comment by contactashish13** [comment]
@SilviuDinu it should work then, especially if you increase the duration to something large such as 25000 to see the animation.

**Comment by SilviuDinu** [comment]
@contactashish13 it doesn't seem to work. I've created a video with my steps -> https://share.vidyard.com/watch/VF4V59AZngiVbXZdVFKd9n?

**Comment by contactashish13** [comment]
@SilviuDinu animations on gauge don't work. That is the reason it does not have animation related tab in the settings either unlike other charts.

https://developers.google.com/chart/interactive/docs/gallery/gauge says 

![image](https://user-images.githubusercontent.com/12953439/74643423-b1eaf400-519a-11ea-9554-529f67e92f4c.png)

**Comment by SilviuDinu** [comment]
Okay, I understand now. It makes sense why the other options were working, but not the animations.
Thanks!
