### ISSUE TITLE
Gutenberg block error

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#651]
Didn't manage to find a pattern for when this happens, but sometimes after creating more charts, I get this error in the Gutenberg block "This block has encountered an error and cannot be previewed"
![Screenshot (2)](https://user-images.githubusercontent.com/3266155/74747733-1035d680-5270-11ea-8d00-a8bc163dac62.png)

```
react-dom.min.js?ver=16.9.0:103 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%2C%20fontColor%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Pc (react-dom.min.js?ver=16.9.0:66)
    at react-dom.min.js?ver=16.9.0:76
    at T (react-dom.min.js?ver=16.9.0:87)
    at ph (react-dom.min.js?ver=16.9.0:218)
    at lh (react-dom.min.js?ver=16.9.0:126)
    at O (react-dom.min.js?ver=16.9.0:121)
    at ze (react-dom.min.js?ver=16.9.0:118)
    at react-dom.min.js?ver=16.9.0:53
    at unstable_runWithPriority (react.min.js?ver=16.9.0:26)
    at Ma (react-dom.min.js?ver=16.9.0:52)
```

**Comment by contactashish13** [comment]
@rodica-andronache I believe this would also show an error in the console. Can you paste it to the original post? @DanyCaissy have you seen this behavior before or can you reproduce this?

**Comment by rodica-andronache** [comment]
I've tried to add the console error. If you have access to the demo, you can check it here https://demo.themeisle.com/visualizer/wp-admin/post.php?post=325&action=edit

**Comment by DanyCaissy** [comment]
I wasn't able to reproduce this

**Comment by rodica-andronache** [comment]
@DanyCaissy you couldn't replicate this on the demo https://demo.themeisle.com/visualizer/wp-admin/ ? I've tried again on the page you've created for Bubble chart and the same thing happens for me. Let me know. I saw you created the charts using shortcodes, not the Gutenberg block

**Comment by DanyCaissy** [comment]
@rodica-andronache Oh right yes. The gutenberg editor never worked for me on the demo site, even on previous versions. Likely something got corrupted.

**Comment by contactashish13** [comment]
@DanyCaissy please share a scenario of how to replicate this on a fresh instance. I cannot debug/fix this on the demo site. If you come across a particular pattern that will help

**Comment by DanyCaissy** [comment]
@contactashish13 I was never able to reproduce this on another instance.  This has been a long-standing issue on the demo site for multiple versions.

@rodica-andronache How should we proceed in that case?

**Comment by rodica-andronache** [comment]
I've tried on other instances and couldn't replicate it either. I thought it might be related to a multisite, but that wasn't the issue either. It's probably related to the demo setup, but if you can't do anything about it, I guess we can close it for now
