### ISSUE TITLE
add documentation for bubble charts to readme

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#656]
related to #567 

I don't see this in the readme so it may be a good idea to add.

**Comment by DanyCaissy** [comment]
@contactashish13 Added in #658

**Comment by rodica-andronache** [comment]
@DanyCaissy I think you also need to update the `readme.txt` file.
And it might be a good idea to disable comments here https://demo.themeisle.com/visualizer/bubble-chart/ as it doesn't look good, and it's the same on the other pages

**Comment by DanyCaissy** [comment]
@rodica-andronache This is done
