### ISSUE TITLE
Table Chart - Number of rows per page placeholder

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#660]
`Number of rows per page` has `10` as a placeholder, but not as a default value, so when you enable pagination, that number is not taken into consideration, making things confusing.
I would suggest to either remove that placeholder or make it as a default value for the field.

![Screenshot (2)](https://user-images.githubusercontent.com/3266155/75975553-6302c580-5ee1-11ea-9027-0bb03832dd59.png)

**Comment by DanyCaissy** [comment]
Closing, will be handled as part of https://github.com/Codeinwp/visualizer/issues/668
