### ISSUE TITLE
Cork City (Ireland) not visible in Geo Map

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/visualizer#672]
Cork City which is part of Ireland is not visible in the Geo map.
https://snipboard.io/IpBwSC.jpg

Steps to replicate:
1. Open **Visualizer Library** > **Add New**
2. Selected **Geo** map and imported the data below:
https://www.dropbox.com/s/sx9x6vziy1k1eus/Dataset_%20SARS-Cov-2%20-19%20Recovered%20cases%20Globally%20by%20JHU%20CSSE%20-%20Sheet4%20%281%29%20%281%29.csv?dl=0
3. From **Advanced** > **Map Settings**
**Region**: IE
**Resolution**: Provinces
4. **Save Chart.** Cork City is not visible, see the previous screenshot. Tried with an API, the issue is the same.

Ticket: https://secure.helpscout.net/conversation/1114826493/220913?folderId=1692628

**Comment by contactashish13** [comment]
@purplecodes not a problem with the plugin: https://github.com/google/google-visualization-issues/issues/2087. Use the code `IE-CO`.

In the future please make sure you try this on a jsfiddle as most of these problems can be resolved at your end faster.
