### ISSUE TITLE
Gutenberg: does not display any Google Chart and throws a console error

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#674]
When you try to insert a chart, it shows as this:

![image](https://user-images.githubusercontent.com/12953439/78001009-bc300e80-7352-11ea-8bd8-6aa404dd533c.png)

with a console error

![image](https://user-images.githubusercontent.com/12953439/78000845-8428cb80-7352-11ea-9b56-97f44d7e9aa6.png)

This is happening with the last released version (and 2 versions previous) as well.

Can check on:
https://registered-weevil.jurassic.ninja 
WP user: demo 
WP/SSH password: mjredzZ8bTZ0

**Comment by contactashish13** [comment]
It looks like an error with the google charts API but I'll need confirmation. @HardeepAsrani can you please check?

**Comment by contactashish13** [comment]
a rebuild as part of #673 fixed it. very strange!

**Comment by rodica-andronache** [comment]
tested also with the current version, on both wp 5.3 and wp 5.4 and it worked well

**Comment by contactashish13** [comment]
@rodica-andronache I believe this has been released. If so, can you please close this if no longer an issue?
