### ISSUE TITLE
bulk activation of plugin aborts activation of subsequent plugins

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#679]
tested in reference to https://wordpress.org/support/topic/bug-in-plugin-activation/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/680

**Comment by rodica-andronache** [comment]
@contactashish13 
tried testing this PR and it's not working for me. Let me know if I'm missing anything https://www.loom.com/share/57c7fd4a1ec24639a058cd766a4cbce7

**Comment by contactashish13** [comment]
@rodica-andronache it continues to work for me. I'm on WP 5.4. Can you share a public instance where this can be reproduced?

**Comment by rodica-andronache** [comment]
https://economic-seahorse.jurassic.ninja/wp-admin/
user: demo
password: ZjUsM@NxNdHwzN(wsR$7ublu
Try to activate at the same time Holly Dolly, Visualizer, and WooCommerce. 
WooCommerce does not get activated

**Comment by contactashish13** [comment]
@rodica-andronache I've changed the methodology and it should work anywhere.

**Comment by rodica-andronache** [comment]
@contactashish13 from your last commit I understand that even when bulk activating more plugins, I should still be redirected to Visualizer's Support page. Is that correct? Because for me, that's not happening. All plugins are activated, but I'm not redirected to Visualizer's page

**Comment by contactashish13** [comment]
@rodica-andronache it will happen only if you activate the plugin first. If the plugin was already activated, it will not redirect you.
