### ISSUE TITLE
Direct integration with google spreadsheet

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#687]
https://developers.google.com/chart/interactive/docs/spreadsheets

Users can directly integrate with their spreadsheets instead of exposing those spreadsheets as a CSV. They can do this by using the google query language. This is already supported in the code since #374 

@DanyCaissy can you review https://docs.themeisle.com/article/607-how-can-i-populate-data-from-google-spreadsheet as a starter and see if it complete? You can also suggest changes if you find the implementation can be improved

**Comment by DanyCaissy** [comment]
@contactashish13 Can you clarify the intent of this ticket? I feel like it's discussing multiple different things.

**Comment by contactashish13** [comment]
@DanyCaissy it is discussing only one thing and that is direct integration of a google spreadsheet using GQL. Have you tried reading the documentation and following the steps there to see how it work? If not, I would suggest that as the first step. This ticket is more about enhancing the documentation and making it more apparent than anything to do with code.

**Comment by DanyCaissy** [comment]
@contactashish13 As per those instructions it doesn't seem to work for me. What step am I missing?

[GQL.zip](https://github.com/Codeinwp/visualizer/files/4653929/GQL.zip)

**Comment by contactashish13** [comment]
@DanyCaissy you are trying to use the query on an HTML instead of using it on the CSV. You may want to read [this section](https://developers.google.com/chart/interactive/docs/spreadsheets#query-source-ranges) and see the example URL they have used vs. the one you are using.

**Comment by DanyCaissy** [comment]
@contactashish13 If I follow the steps in the document to the letter, it does not work.

Step 2 says NOT to choose CSV:

**Step 2
In the new dialog, you need to click the "Start publishing" button. A link to the published item appears in the publishing dialog. Do not choose Choose "CSV (comma-separated values)" type.**

If I use web-page, as per the documentation, it does not work. The URL is correct:

https://docs.google.com/spreadsheets/d/e/2PACX-1vSjH7yfLC8x6mtS5LDLMNecIj0J9lEA4uo3WoVEiF16dB1INbVLPCFb6bpt1xX18dlTE6bO8Z5OhC3a/pubhtml/gviz/tq?tq=Select%20A%2CB&tqx=out:csv

**Comment by contactashish13** [comment]
@DanyCaissy which part of the document https://docs.themeisle.com/article/607-how-can-i-populate-data-from-google-spreadsheet do you feel is incorrect?

**Comment by DanyCaissy** [comment]
@contactashish13 I'm not sure since I can't get it to work the way it is explained. Please provide a video of the whole process and I'll adjust the documentation accordingly.

**Comment by contactashish13** [comment]
@DanyCaissy I've tried this by following the document and I see the problem.

The URL that is generated once you publish the file is of the form `https://docs.google.com/spreadsheets/d/e/<alphanumeric>/pubhtml`

and the URL that is generated when you click the share button (in the below image) 
![image](https://user-images.githubusercontent.com/12953439/83722100-05a22000-a65a-11ea-8c45-6d9127298411.png)

is of the form `https://docs.google.com/spreadsheets/d/<alphanumeric>/edit?usp=sharing`. 

Notice the difference between `/d/e/<alphanumeric>/` and `/d/<alphanumeric>/` forms.

So the `gviz/tq?tq=<QUERY>&tqx=out:csv` has to be added to the second URL not the first one.

Here are some URLs to understand this better:
- [file I published to the web](https://docs.google.com/spreadsheets/d/e/2PACX-1vQ4i9fotZakkRkTXOIOjw3oJjwHeoqzn49OVU-tYjRPJqTm2cP3JNKhPTYczpgS9DcqBJDFWBvaALnD/pubhtml)
- [URL that is generated when I clicked the share button](https://docs.google.com/spreadsheets/d/13kdHq-cTtWcYcc1B66sayPBh_atOIy8vM9_2R0IkSUc/)
- [the URL to use to use GQL (let's say for selecting column A only)](https://docs.google.com/spreadsheets/d/13kdHq-cTtWcYcc1B66sayPBh_atOIy8vM9_2R0IkSUc/gviz/tq?tq=SELECT%20A&tqx=out:csv)

**Comment by DanyCaissy** [comment]
@contactashish13 Ah yes that seemed to be the issue. I didn't expect the URL to be different this way. I've updated the documentation now as to avoid this potential issue.
