### ISSUE TITLE
Gutenberg: "Advanced Options" on certain charts break

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#688]
Possibly related to https://github.com/Codeinwp/visualizer/issues/675

### Description:

Clicking "Advanced options" on the block editor, for certain chart types, results in "the block has encountered an error".

This only happens on Timeline and Bubble charts as far as I could reproduce.

### How to reproduce:

1- Create a timeline chart and a bubble chart
2- Create a new post
3- Add both charts to the post via gutenberg
4- Click "Advanced options" on the right when the chart is selected

### Expected behaviour:

The chart is displayed properly

### Current behaviour:

The block breaks: https://i.imgur.com/2OC57l0.png

### Reference:

Video reproducing the issue: 
[advanced-settings.zip](https://github.com/Codeinwp/visualizer/files/4572508/advanced-settings.zip)

Console Error: https://i.imgur.com/JU8PzYX.png

### Technical info

Wordpress Version: 5.4.1
Visualizer Version: 3.4.2 + 1.9.2

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/695 addresses this.

@DanyCaissy as suggested in a couple of earlier issues as well, it will be good to compare each setting for every chart between gutenberg and the library. For example, in this issue Bubble Settings was missing from gutenberg. We should aim to fix all these discrepancies in one go under one single issue.

**Comment by rodica-andronache** [comment]
@contactashish13 if you can please fix the conflicts here https://github.com/Codeinwp/visualizer/pull/695 I think we can merge it

**Comment by contactashish13** [comment]
@rodica-andronache done.
