### ISSUE TITLE
Gutenberg: Make UI more intuitive when a chart is missing

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#691]
### Description:

If you add a chart to a post, and that chart later gets deleted, it'll look like this in the editor: 

https://i.imgur.com/tn7GhlF.png

This looks as if the chart is loading or that there might be an issue with our plugin, as opposed to the chart not existing.

I'd suggest just displaying a simple message within the box instead. The message could say:

"This chart is not available, it might have been deleted. Please delete this block and resubmit your chart"

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/694

![image](https://user-images.githubusercontent.com/12953439/81644514-86983e00-9445-11ea-9272-be3e322aae63.png)
