### ISSUE TITLE
Conflict with Modern Events Calendar plugin

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#697]
### How to reproduce:
1. Install MEC plugin and visualizer. Activate both.
2. Go to the library and click on Add New
3. You get a blank screen.

### Expected behaviour:
The chart selector screen should not be blank.

### Current behaviour:
As chart selector screen is blank.

### Reference:
- https://wordpress.org/support/topic/blank-screen-when-trying-to-add-a-new-chart/
- https://wordpress.org/support/topic/plugin-conflict-with-modern-events-calendar-2/

### Technical info
* WordPress version: any
* Plugin version: 3.4.3

Specifically https://plugins.trac.wordpress.org/browser/modern-events-calendar-lite/trunk/app/libraries/factory.php#L247, which, if commented out, makes the conflict disappear. You can contact their support to seek a fix for this.

This was marked as `wontfix` in https://github.com/Codeinwp/visualizer/issues/385 but we should investigate if there is a way to fix this or at least warn the users.

Ticket on MEC support forum: https://wordpress.org/support/topic/conflict-with-visualizer-tables-and-charts-plugin/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/698 shows an alert message when a conflict is detected.

**Comment by rodica-andronache** [comment]
@contactashish13 just a small thing, if it can be fixed.
If I go to Visualizer -> Chart Library -> Add New everything is ok
If I go to Visualizer -> Add New Chart -> The notice needs to be dismissed twice
https://www.loom.com/share/ea3a9a3190ae47c987765e18d4cba874

**Comment by contactashish13** [comment]
@rodica-andronache I've fixed this. This happened only when you had no charts and behaved correctly when you had at least one chart showing in the library.

**Comment by rodica-andronache** [comment]
@contactashish13 in the meantime, they've fixed the issue from their plugin. It's ok to close this PR, right?

**Comment by contactashish13** [comment]
@rodica-andronache A user not upgrading to the latest version of MEC would not know about the conflict. Also this PR senses a generic conflict so it would be good to keep this around.
