### ISSUE TITLE
Conflict with elementor pro: elementor icons go missing when visualizer is activated

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#706]
### Reference:
https://wordpress.org/support/topic/conflict-with-elementor-pro-7/

### Technical info
* WordPress version: latest (I assume)
* Plugin version: latest (I assume)

**Comment by rodica-andronache** [comment]
not sure if it helps, but I've tried reproducing this as well, and couldn't do it

**Comment by girishkrishaweb** [comment]
@rodica-andronache I have tested this issue with the NULL version of the Elementor pro plugin with WP - 5.7 and PHP - 7.4 but I haven't found icons missing issue.

Is it possible you can verify with the Elementor pro plugin? Please do let me know the feedback of it.
