### ISSUE TITLE
Gutenberg: Table chart with only string columns throws an error

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#707]
### How to reproduce:
1. Create a table chart with **only string columns**. Assume there is only 1 chart in the library
2. Go to a post, create the visualizer block and click on `Display an existing chart`
3. The block will throw an error

### Expected behaviour:
The block should not throw an error and the table chart should display.

### Current behaviour:
The block will throw an error

### Reference:
![image](https://user-images.githubusercontent.com/12953439/83390203-127f0380-a40f-11ea-8852-39b179b8aa2e.png)

### Technical info
* WordPress version: x.x.x
* Plugin version: x.x.x

**Comment by contactashish13** [comment]
This will be solved as part of https://github.com/Codeinwp/visualizer/pull/666

**Comment by contactashish13** [comment]
@rodica-andronache I'm confused about whether this was fixed as part of the last release or still continues to be an issue. Can you close this if solved?

**Comment by rodica-andronache** [comment]
@contactashish13 it's not yet closed as it's not on production, but you don't need to do anything else for it (that's why is in the Done bin). It's part of this PR that was not yet merged as you suggested we don't add it before we fix some other things https://github.com/Codeinwp/visualizer/pull/666. Let me know if it doesn't make sense

**Comment by contactashish13** [comment]
@rodica-andronache looks like the last release fixed this https://wordpress.org/support/topic/datatable-with-strings-cause-visualizer-chart-error/. Can you check and close this PR/issue?

**Comment by rodica-andronache** [comment]
ok, yes, it's working well in the current version too
