### ISSUE TITLE
Add ability to lazy load charts

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#709]
### Description:
@contactashish13 @DanyCaissy We have a big post on codeinwp where some charts are used, however they are not at the top of the article, but we make the google requests.

There is a chance that most people won't be even looking at the chart, but we still load a lot of js/css. Can we add some option for that?

Like make the request for css/js just when user is close to the chart ( let's say 300px before it?). In some cases the chart can also be behind a tab, with display:none.

cc @selul not sure if you have any ideas on this as well

**Comment by ineagu** [comment]
another approach that I saw is to load an image of the chart by default and on click/hover bring the interaction, sure users can enable/disable that based on how they use the charts

**Comment by DanyCaissy** [comment]
Assuming this can be done in a reasonable amount of development time I think it would be beneficial.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/712 adds this. The main JS files that are responsible for loading the libraries will still be loaded on the page whether a chart is lazy or not, but the additional JS files that Google Charts call will be loaded when a chart is lazy loaded.

Users can add this feature on a per-chart basis by adding `lazy=yes` or `lazy=<number>` to the shortcode e.g. `[visualizer id=123 lazy="yes"]` or `[visualizer id=123 lazy=200]`.  Or they can add the filter that is documented below.

The equivalent feature in the block editor is through Instance Settings:
![image](https://user-images.githubusercontent.com/12953439/84237681-709a9d80-ab17-11ea-8d79-2b93f3dfd2c7.png)


Some pointers:
- If the shortcode provides only `lazy="yes"` the intersection rootMargin is assumed to be `300px`. If the shortcode specifies `lazy=<number>` the intersection rootMargin is assumed to be that number in pixels. To understand how intersection works, look at the section "How intersection is calculated" in https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

- The following filter can be used as well. It works for charts inserted as a shortcode and in the block editor.

```
add_filter( 'visualizer_lazy_by_default', function( $lazy, $chart_id ) {
	// $lazy= 'yes'; for all charts to lazy load with default rootMargin 
	// $lazy= 20; for all charts to lazy load with rootMargin of 20
	return $lazy;
}, 10, 2 );
```
- the shotcode can now be directly copied by clicking this icon. This will paste the entire structure of the shortcode that includes all supported attributes.

![image](https://user-images.githubusercontent.com/12953439/84237788-9758d400-ab17-11ea-9654-94d5b48aac28.png)

**Comment by rodica-andronache** [comment]
@contactashish13 I'm not totally sure I understand this, I couldn't see any difference between lazyload yes or not. Could you please let me know as an example at least, what are the scripts that should not load from the beginning?
And what does it mean that "the additional JS files that Google Charts call will be loaded when a chart is lazy loaded"?
I thought the scripts will be loaded once you scroll the page to reach the charts.

**Comment by rodica-andronache** [comment]
@contactashish13 ok, thank you for the details.
There's an issue with the Gutenberg block. This notice appears and the chart is not visible
![download (16)](https://user-images.githubusercontent.com/3266155/86000922-d8594f80-ba16-11ea-9f1d-c410e58ba083.png)

**Comment by contactashish13** [comment]
@rodica-andronache have addressed this.

**Comment by rodica-andronache** [comment]
@contactashish13 there's another error in the console that doesn't let me add the chart using the visualizer block
<img width="1636" alt="Screenshot 2020-06-30 at 10 04 30" src="https://user-images.githubusercontent.com/3266155/86094498-48b8ad00-bab9-11ea-8c1f-1d7de0c97de8.png">

**Comment by contactashish13** [comment]
@rodica-andronache that should be fine now. I've tried by creating a post, inserting the same chart 2 times and giving each instance a different value of `lazy`. It appears to work properly.

**Comment by rodica-andronache** [comment]
@contactashish13 I can't have two charts appear on the same page, though no error is visible in the console ( didn't set up lazy load for them, I just created some charts with the default parameters ).
https://www.loom.com/share/2005ccc8c9d14515aa8e608cb9437a20

**Comment by contactashish13** [comment]
@rodica-andronache this should be okay now.
