### ISSUE TITLE
revisions are wiped after a while

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#711]
### Description:
On Codeinwp, when using the version 3.4.2, the revisions are getting wiped on a regular schedule, when someone is updating certain posts.

I haven't been able to replicate in a similar environment, but after looking at Codeinwp, the only plugin that was playing with revisions was visualizer. 
I have tried to have a 2nd look over the revision functionalities and identified some possible weak spots that could lead to this. After running this patch on product for more than 1 month, the issues are gone.  
### How to reproduce: 
I don't have a clear way of reproducing this, the problem is when certain posts on codeinwp are getting updated, the revisions for that posts are getting wiped out. 
 
 
### Technical info
* WordPress version: 5.4.1
* Plugin version: 3.4.2

**Comment by selul** [comment]
I have opened a PR with the changes that I did and worked fine in production in the last 6 weeks.

**Comment by contactashish13** [comment]
@selul I have modified the PR to make sure the test cases pass. Can you please check if it works as expected on production?
