### ISSUE TITLE
review notice not dismissable

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#715]
cc @contactashish13 

### Description:
review notice appear immediately after activation and can't be dismissed .

### How to reproduce:

1. Activate the free plugin

### Expected behaviour:

1. The notice would appear after a certain time interval
2. Notice can be dismissed

### Current behaviour:

1. Notice can't be dismissed
2. Notice appear immediately after activation

### Reference:

https://www.dropbox.com/s/c9mooprsmuhc4pc/Screenshot%202020-06-12%2019.41.50.png?dl=0

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.3

**Comment by contactashish13** [comment]
@selul could this be something to do with the SDK?

**Comment by selul** [comment]
Highly unlikely, it would have been present in all products.

**Comment by contactashish13** [comment]
@selul but dismissing a notification is part of the SDK and nothing to do with the plugin, correct?

**Comment by contactashish13** [comment]
@selul I think this is a problem with the SDK. @ineagu may have highlighted problems with visualizer but the fact is that all these functions are part of the SDK.

**Comment by selul** [comment]
Let's keep this on hold until further details on how can be replicated get reported.
