### ISSUE TITLE
Conflict with Edit Flow plugin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/visualizer#716]
### Description:
@contactashish13 Visualizer can't be used on our sites due to this error: https://www.dropbox.com/s/zwibm2gxqhr1dnn/Screenshot%202020-06-12%2019.46.44.png?dl=0, probably we can use a protected or unique name for the function.

### How to reproduce:

1. Go to add the new chart screen

### Expected behaviour:

Do not fail when other plugins use is_block_editor() function

### Current behaviour:

New charts can't be added

### Reference:
https://www.dropbox.com/s/zwibm2gxqhr1dnn/Screenshot%202020-06-12%2019.46.44.png?dl=0

### Technical info
* WordPress version: 5.4.3
* Plugin version: 3.4.3

**Comment by contactashish13** [comment]
@ineagu the error shows a fatal error and not a function name error. Can you check?

Also, if you deactivate the plugin edit flow, does this error vanish?

**Comment by ineagu** [comment]
Is a fatal error right. I can’t deactivate edit flow plugin on the live sites

**Comment by cosmin-serbanescu** [comment]
@contactashish13 yes, deactivating Edit Flow plugin solves it - just tested on staging

**Comment by contactashish13** [comment]
@cosmin-serbanescu thanks! So looks like it is a plugin conflict and also the edit flow plugin does not check for a null object. I don't know how the flow plugin is used in the visualizer library.

**Comment by cosmin-serbanescu** [comment]
I've just created a support ticket: https://wordpress.org/support/topic/plugin-conflict-284/

**Comment by ineagu** [comment]
@contactashish13 I am wondering, there is any chance that the error that edit_flow is doing is a common one? and that there can be 10-100 plugins that fail to work with visualizer add_new_chart page?

**Comment by contactashish13** [comment]
@ineagu It is possible but I haven't seen this error mentioned on the forums. @Codeinwp/support have you seen this on HS?

**Comment by vytisbulkevicius** [comment]
@contactashish13 Nope, I haven't seen this error before. I had one client that was facing a conflict with Modern Events Calendar plugin just like this one that you assisted: https://wordpress.org/support/topic/plugin-conflict-with-modern-events-calendar-2/ (but it's a different error/case).

By searching in HS for this error mentioned by Ionut I only found one old ticket from April 19' : https://secure.helpscout.net/conversation/837289591/187310/

**Comment by ineagu** [comment]
ok, so what we should do here? We need to use both Visualizer & edit flow on our website?

**Comment by contactashish13** [comment]
Installing Edit Flow and trying to edit a chart produces the fatal error. They are checking `is_block_editor` on a null object and this is the line `return get_current_screen()->is_block_editor();`. They are not checking if a screen object exists.

I don't know of any way to fix from our side as their code is messed up. @selul suggestions?

```
PHP Fatal error:  Uncaught Error: Call to a member function is_block_editor() on null in \wp-content\plugins\edit-flow\common\php\trait-block-editor-compatible.php:26
Stack trace:
#0 \wp-content\plugins\edit-flow\modules\custom-status\custom-status.php(292): EF_Custom_Status->is_block_editor()
#1 \wp-includes\class-wp-hook.php(287): EF_Custom_Status->action_admin_enqueue_scripts('media-upload-po...')
#2 \wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 \wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#4 \wp-admin\includes\media.php(539): do_action('admin_enqueue_s...', 'media-upload-po...')
#5 \wp-content\plugins\visualizer\classes\Visualizer\Module\Chart.php(825): wp_iframe(Arr in \wp-content\plugins\edit-flow\common\php\trait-block-editor-compatible.php on line 26

```

**Comment by girishkrishaweb** [comment]
It seems we have a duplication ticket here: https://github.com/Codeinwp/visualizer/issues/792
