### ISSUE TITLE
Error "You called the draw() method with the wrong type of data rather than a DataTable or DataView"

### ISSUE THREAD

**Issue by leoaraujoup** [Codeinwp/visualizer#72]
Hi there!
A couple of days ago whenever I try to create a new chart I got the message error "You called the draw() method with the wrong type of data rather than a DataTable or DataView"
Is anyone else getting this error? 
I can't create new charts at all! Old ones are working though!
I wonder if something got updated in the Google API that it made stop working.

All help will be very much appreciated!
Many thanks!

**Comment by rodica-andronache** [comment]
Hi @leoaraujoup ,

Are you still having this issue? I tested on my side and was able to create a new chart with no problems. If the issue is still there, could you please give more details about recreating it?

Thank you,
Rodica

**Comment by leoaraujoup** [comment]
Hello @rodica-andronache 

I am really sorry for the late reply.

The error message is still appearing when you upload the data. However, if I ignore it and just create a new chart, it will work. My problem is that I was expecting to see the data uploaded before creating (normally it is like this right?) but I figured that if I just ignore the error message, and create a new chart without seeing the data it will work! But the error message is still there!

Many thanks,

L

**Comment by selu91** [comment]
hey @leoaraujoup , yes for the moment you need to save the chart and after you will see that data rendered.
