### ISSUE TITLE
Google charts: Series number format not applying in the Gutenberg editor

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#724]
1) Create any type of core google chart  (line. bar, column, etc)
2) Change `Number Format` in `Series Settings` to a custom value. The change is reflected in the chart. Save the chart.
![image](https://user-images.githubusercontent.com/12953439/85981359-b903f780-ba01-11ea-9a19-442e13db6e42.png)
3) Insert that chart in a Gutenberg block
4) Change `Format` in `Series Settings` in the Gutenberg block to a custom value. The changed value is not visible in the editor,  just on the frontend.
Editor:
![image](https://user-images.githubusercontent.com/12953439/85981606-1ac46180-ba02-11ea-898a-b141d4205482.png)
<img width="1234" alt="Screenshot 2020-06-29 at 18 51 54" src="https://user-images.githubusercontent.com/3266155/86027673-a9080a00-ba39-11ea-8d07-e16f1be8ec01.png">
Frontend:
<img width="884" alt="Screenshot 2020-06-29 at 18 56 18" src="https://user-images.githubusercontent.com/3266155/86028168-3c413f80-ba3a-11ea-9ed2-bd7e8f0c5b4e.png">

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/734 fixes this.

**Comment by rodica-andronache** [comment]
@contactashish13 everything is working well. can you please fix the conflicts as well?
