### ISSUE TITLE
Visualizer sales pages are missing images

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#727]
### Description:
The visualizer pro pages:

https://themeisle.com/plugins/visualizer-charts-and-graphs/upgrade/
https://themeisle.com/plugins/visualizer-charts-and-graphs/

Are missing a lot of images.

Did something happen? Did someone delete too many images? Can we recover these?

@selul

**Comment by rodica-andronache** [comment]
Hi! which images are missing? For me, it's looking ok

**Comment by DanyCaissy** [comment]
@rodica-andronache They were missing yesterday, half of them. It looks fine now.
