### ISSUE TITLE
Permissions tab disappears after a user modifies a chart's data

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#728]
### Description:
Permissions tab disappears after a user modifies a chart's data

### How to reproduce:

1. Create a table (or any other chart/library)
2. Click settings, witness the permissions tab: https://i.imgur.com/B1yTQR5.png
3. Click source again, open manual data and close it immediately (no need to modify data)
4- Go back to settings. The permissions tab is gone.

### Expected behaviour:

The permissions tab remains

### Current behaviour:

The permissions tab is gone

### Reference:
![VtklJtfT2U](https://user-images.githubusercontent.com/5183243/86547992-cab93380-bf08-11ea-80ed-c883f3058f16.gif)

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.4

**Comment by contactashish13** [comment]
@DanyCaissy please always specify if this happens with just one specific chart type/library or with many. That would add more clarity to both development and testing.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/778 fixes this

**Comment by rodica-andronache** [comment]
@contactashish13 when used with Visualizer Pro, if you first edit the chart and go to the Permissions tab, the selects there don't work anymore.
https://www.loom.com/share/a192463504cb43d0b8b86948b599a975

**Comment by contactashish13** [comment]
@rodica-andronache fixed it.

**Comment by rodica-andronache** [comment]
@contactashish13 there's a small case where is still not working for me https://www.loom.com/share/595359585c7d4d999f9735b550171b15

**Comment by contactashish13** [comment]
@rodica-andronache I'm unable to replicate this with this PR and master branch of pro. Could it be a cache problem on your side?

**Comment by rodica-andronache** [comment]
@contactashish13 tried multiple times, clearing the cache, and the same thing happens for me. @irinelenache can you please try as well?

**Comment by irinelenache** [comment]
@rodica-andronache tried the same steps as you did and it happens to mee too. `Select users` doesn't show any user until i open `Select roles` and then go back to `Select users`.
