### ISSUE TITLE
Line Graph Text Overlay is Missing

### ISSUE THREAD

**Issue by optiforms** [Codeinwp/visualizer#73]
http://optiformsinc.com/optical-coatings/protected-gold/

This is a page on our dev site with a line graph I created using the Visualizer plugin. We loved when hovering over the line graph a text overlay would appear with details about that data point. But for some reason the overlay went missing today. No changes to WordPress versions, plugins, database, or other software were made since yesterday when the overlay last appeared.

Is this a bug or was this disabled on purpose?

**Comment by beoeoffice** [comment]
Dear optiforms,

I have the same problem. Is there anykind of solution? I like the plugin very much, cause it´s really easy to handle with and you can visualize a lot of things. One really mysterious thing is, that the text overlay will appear if you use pie charts.....I have no idea?!

**Comment by HardeepAsrani** [comment]
Could you set a value in **Focus Target**, located in **Lines settings** and see if it works after that?

![Settings](https://cdn.pbrd.co/images/1fhwFDrA.png)
