### ISSUE TITLE
add support for string translations

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#731]
### Description:
Allow users to translate their dynamic data.

```
I’d like to translate everything in the graph: titles, axes and series names.
```

https://wordpress.org/support/topic/translation-with-wpml-22/

https://wpml.org/forums/topic/visualizer-charts-and-graphs/

This could be important: https://wpml.org/documentation/theme-compatibility/go-global-program/

**Comment by contactashish13** [comment]
@rodica-andronache do you think this can be added easily (without a code change) like we did in WPPR?

**Comment by rodica-andronache** [comment]
@contactashish13 if you mean with the wpml-config file, I'm not sure. It's a possibility but it will need to be tested

**Comment by contactashish13** [comment]
@DanyCaissy please add this to the correct queue/version. It would also be good if you can do some research on polylang vs wpml and which we should support. Neither of them is easy.

**Comment by Skystream96** [comment]
There is one user that asked about the WPML compatibility of our Plugin and after doing a bit of research I noticed that we don't appear on their list of compatible plugins. then I found this old enhacement that hasn't been solved yet so I posted here.

@girishpanchal30 @vytisbulkevicius do you think it would be a good idea to work with WPML and make our plugin translatable? I haven't seen many users requesting it and I think it is quite a hard implementation but wanted to hear your opinion anyway.

[Here is the user report.](https://secure.helpscout.net/conversation/1967838676/332142?folderId=212390)

Thank you and I'm eager to hear your opinion!

**Comment by girishpanchal30** [comment]
Hey @Skystream96,
If we do the same thing as WPML does for pages and posts, I believe we can add WPML support.
Ref: https://tinyurl.com/27uqumet

Here is my opinion:
Users may quickly set up charts for different languages if we add a new action to the chart list.
Ref: https://tinyurl.com/2a7smugd

Thanks

**Comment by Skystream96** [comment]
Hey @girishpanchal30 ,

That sounds good but would this implementation mean that they will have another chart for that particular language, so let's say I have 3 languages on my website, this would mean I would have the same chart 3 times (once for every language) right?

Wouldn't this affect performance quite drastically?

@vytisbulkevicius what do you think about this?

**Comment by girishpanchal30** [comment]
> That sounds good but would this implementation mean that they will have another chart for that particular language, so let's say I have 3 languages on my website, this would mean I would have the same chart 3 times (once for every language) right?

Yes

> Wouldn't this affect performance quite drastically?

Yes, the above method affect database space.

**Comment by vytisbulkevicius** [comment]
This sounds good to me, and the approach suggested by @girishpanchal30 seems to be efficient. I don't think the space of the database increases that much here to make an impact on the speed of website, right?
I mean the same way you translate every post/page, and it doesn't hurt that much, so we should be good.

I also heard about this request a few times so I think we can proceed with this one.

_P.S This request https://wpml.org/forums/topic/visualizer-plugin-compatibility/ is not related, it was a bug on our end and was fixed here - https://github.com/Codeinwp/visualizer-pro/issues/333_

**Comment by girishpanchal30** [comment]
> I don't think the space of the database increases that much here to make an impact on the speed of website, right?

Yes, you are right it will not affect website performance.

**Comment by girishpanchal30** [comment]
Hey @Skystream96 @vytisbulkevicius,

As per my suggestion, I have implemented WPML plugin support. Please check and do let me know if you have any issues.
PR: https://github.com/Codeinwp/visualizer/pull/947

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Thank you for working on this. 
I tried to test the version of the plugin from the mentioned PR but can't make the translated chart to work. Here is my screencast: https://vertis.d.pr/ewnB0y
I was able to translate data for the chart but when I save the chart it doesn't show me that translated version as a new chart in library and in the different language version of the page I don't see the chart rendered. 
Am I doing something incorrectly?

Also, can we move this feature to the PRO version of the plugin? Sorry for not mentioning this before, this issue was originally created in the free repo but we think it should be a pro feature.
Thank you.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius

> Am I doing something incorrectly?

Yes, I have excluded other language charts from the list page. Users can see the add/edit icon when hover the flag.

For frontend:
Use the main chart ID in the shortcode. It will automatically render another language chart when changing the language.

For example:

{site_url}/chart-demo/ - Display default language chart
{site_url}/chart-demo/fi - Display Finnish language chart OR any other.

Do you want to display the chart on the list page?

> Also, can we move this feature to the PRO version of the plugin? Sorry for not mentioning this before, this issue was originally created in the free repo but we think it should be a pro feature.

Okay, sure!

Thanks

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

> Also, can we move this feature to the PRO version of the plugin? Sorry for not mentioning this before, this issue was originally created in the free repo but we think it should be a pro feature.

I have moved the pro feature and also added some list improvements. Please check with the below PR.

Free: https://github.com/Codeinwp/visualizer/pull/947
Pro: https://github.com/Codeinwp/visualizer-pro/pull/355

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the feature seems to be working fine for me 👍 

A single mention, the flags weren't visible for me until i had this setup in the WPML settings https://vertis.d.pr/1d6Tx2 (I tried with fresh instances on tastewp/instawp and i always had to check this in order to make it work)

**Comment by girishpanchal30** [comment]
> A single mention, the flags weren't visible for me until i had this setup in the WPML settings https://vertis.d.pr/1d6Tx2 (I tried with fresh instances on tastewp/instawp and i always had to check this in order to make it work)

@irinelenache Yes, This is the first step to enable translation support.

**Comment by AndreeaCristinaRadacina** [comment]
Hi there!

While creating the doc, I have made a few more tests, to check how this behaves and I have some questions ( maybe suggestions, if you consider them useful ):

- If I have created a translated chart it doesn't inherit the filters, but I am not sure if it's intuitive. I mean, I know we can design the translated chart and make it exactly like the default version, but I just wanted to point this out. 
- Why are we allowed to pick another type of chart when we create the translated version?

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

What do you think about these questions?

1) If we have a clone with a setting, the user wants to reconfigure chart data.
2) I've opened a new chart model so users can choose a different chart if the user wants. Otherwise, the user chooses the same chart and configure it for another language.

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

In my point of view when clicking the flag to translate the chart we should make a clone of existing chart without an option to choose a different type of chart, the purpose of this is to translate strings. Of course, we can keep those other options available but allowing to create a completely different type of chart creates confusion IMO.
So clicking the flag should make a clone and inherit everything that existing chart in main language already has. 

Also, I tested again now in my test instance with the latest versions above and to me it doesn't work the way you defined above:

> Yes, I have excluded other language charts from the list page. Users can see the add/edit icon when hover the flag.
> 
> For frontend:
> Use the main chart ID in the shortcode. It will automatically render another language chart when changing the language.
> 
> For example:
> 
> {site_url}/chart-demo/ - Display default language chart
> {site_url}/chart-demo/fi - Display Finnish language chart OR any other.
https://github.com/Codeinwp/visualizer/issues/731#issuecomment-1274339714


Here is my screencast - https://vertis.d.pr/v/KmglpN
So should it work the way as it works in my screencast or how described above?

**Comment by girishpanchal30** [comment]
@vytisbulkevicius

> In my point of view when clicking the flag to translate the chart we should make a clone of existing chart without an option to choose a different type of chart, 

Okay

> Also, I tested again now in my test instance with the latest versions above and to me it doesn't work the way you defined above:

Can you please share the test instance details here?

Thanks

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

Sure, as this repo is public I shared it here - https://github.com/Codeinwp/visualizer-pro/pull/355

**Comment by girishpanchal30** [comment]
> Also, I tested again now in my test instance with the latest versions above and to me it doesn't work the way you defined above:

@vytisbulkevicius Fixed, Can you please retest with the latest commit?

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

Nice, it works now correctly and translated version of the chart is rendered automatically.

I'm planning to make a release but I will wait then till you make that change when creating the translation for a chart it doesn't show you the ability to create a new type and just inherits everything from the one you're translating.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius 
> In my point of view when clicking the flag to translate the chart we should make a clone of existing chart without an option to choose a different type of chart,

Fixed, Please check and do let me know if you have any issues.

**Comment by vytisbulkevicius** [comment]
Works great @girishpanchal30 🚀
Thank you!
