### ISSUE TITLE
Column chart: values between one and zero do not get displayed properly

### ISSUE THREAD

**Issue by pt1602** [Codeinwp/visualizer#732]
### Description:
Values like 0.35 get displayed in the frontend as a 0.35 column but when you click to show the description with the value it show 35% instead of 0.35%.

### How to reproduce:
1. Create a new column chart with a value between one and zero
2. Display the chart on a page
3. Click on the bar to show the value

### Expected behaviour:
Display the true value in the column description with a dot zero before.

### Current behaviour:
It shows a wrong value in the column description.

### Reference:
![Bildschirmfoto vom 2020-07-12 18-13-31](https://user-images.githubusercontent.com/57329320/87251691-d4451d00-c46d-11ea-9d5a-4351137bd5e8.png)

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.5

**Comment by rodica-andronache** [comment]
Hi @pt1602, 
You probably have a custom format for the columns, that's why it displays like that. Make sure you check if you have any custom option in Series Settings.

![ss1](https://user-images.githubusercontent.com/3266155/88022964-e5122480-cb38-11ea-90fd-69a98ec75b12.png)

**Comment by contactashish13** [comment]
@rodica-andronache if you don't think this is a bug, can this be closed?
