### ISSUE TITLE
Google Table chart does not display chart if boolean values are specified

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#733]
### How to reproduce:
- Add a default google table chart
- edit the data to make the last column a boolean with these values
```
Month,Bolivia,Ecuador,Madagascar,Papua New Guinea,Rwanda
date,number,number,number,number,boolean
2004/05/01,165,938,522,998,1
2005/06/01,135,1120,599,1268,0
2006/07/01,157,1167,587,807,1
2007/08/01,139,1110,615,968,1
2008/09/01,136,691,629,1026,1
```
- Click show chart and the chart shows up on the editing frame with the correct ticks and crosses
![image](https://user-images.githubusercontent.com/12953439/87629665-12ce2680-c751-11ea-9491-0d5b62bc6571.png)

- Click save chart and the chart keeps loading in the library (and does not display on the front end; no console error)
![image](https://user-images.githubusercontent.com/12953439/87629720-2f6a5e80-c751-11ea-9d5f-fd02bc36e6ac.png)

### Expected behaviour:
The chart should load and show the correct ticks and crosses corresponding to the boolean values.

### Current behaviour:
As explained above.

### Technical info
* WordPress version: latest
* Plugin version: 3.4.5

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/741

**Comment by rodica-andronache** [comment]
@contactashish13 the chart now load ok in the library.
Saw another small issue which I couldn't replicate on production, as the chart doesn't show at all there.

If you create a chart with both true and false values this happens:

In the chart library, it's ok(I can see both true and false signs)
<img width="989" alt="Screenshot 2020-07-21 at 14 46 51" src="https://user-images.githubusercontent.com/3266155/88051647-a04eb380-cb61-11ea-8ad4-6843214cf089.png">

In the Gutenberg editor, is not ok, as eveything is set us true
<img width="792" alt="Screenshot 2020-07-21 at 14 47 11" src="https://user-images.githubusercontent.com/3266155/88051662-a349a400-cb61-11ea-9c25-23c0b69eeb38.png">

On frontend, it's ok(I can see both true and false signs)
<img width="874" alt="Screenshot 2020-07-21 at 14 47 26" src="https://user-images.githubusercontent.com/3266155/88051664-a3e23a80-cb61-11ea-929f-b070fe8bb871.png">

**Comment by contactashish13** [comment]
@rodica-andronache have addressed this. It may be a good idea to test a variety of data with tables (google and datatables).

**Comment by rodica-andronache** [comment]
@contactashish13 tested further and saw two issues (for the GoogleChart library):

- [ ] Error clicking on advanced options
1. Create a table chart with a `boolean column somewhere in the middle of the chart table` (so not the last column of the table).
2. Insert the chart in a post using the Gutenberg block
3. Clicking on `Advanced Options` throws the error “The block has encountered an error and cannot be previewed.”
![1](https://user-images.githubusercontent.com/3266155/88532486-5b1cfc80-d00d-11ea-818d-aa040bfe16a8.png)
![2](https://user-images.githubusercontent.com/3266155/88532499-5eb08380-d00d-11ea-808b-b4c1903f8541.png)

- [ ] Trying to edit a chart in the Gutenberg editor
1. Install Visualizer Pro
2. Create a table chart with a boolean column
3. Insert the chart in a post using the Gutenberg block
4. In the block, click on Manual Data > View Editor
![3](https://user-images.githubusercontent.com/3266155/88532982-26f60b80-d00e-11ea-8efe-097c0c18ccab.png)
5. Edit the values for one of the other columns (not the boolean one)
![4](https://user-images.githubusercontent.com/3266155/88533246-a683da80-d00e-11ea-8199-b0364def2275.png)
6. After saving the chart, the false values dissappear from the boolean column in the editor
![11](https://user-images.githubusercontent.com/3266155/88533536-1eea9b80-d00f-11ea-849a-fc9548b4c6ca.png)

7. If I try to add them back, in the editor, all the values appear as true, even tho in the frontend they appear correct.
![5](https://user-images.githubusercontent.com/3266155/88533385-eba80c80-d00e-11ea-8521-8a5babcc4773.png)

**Comment by contactashish13** [comment]
Have addressed both.
