### ISSUE TITLE
Update backlinks on wp.org

### ISSUE THREAD

**Issue by adelina17** [Codeinwp/visualizer#739]
We need similar updates for Visualizer too: https://wordpress.org/plugins/visualizer/

These are the links that have to be corrected: http://prntscr.com/tl9xsa

From http://justfreethemes.com/ to https://justfreethemes.com/
And from http://www.codeinwp.com/blog/best-wordpress-themes/ to https://www.codeinwp.com/blog/best-wordpress-themes/

Thanks! :)

cc @rodica-andronache @contactashish13

**Comment by contactashish13** [comment]
@adelina17 done. Can you please close this issue when you verify it is okay?

**Comment by adelina17** [comment]
@contactashish13 Thanks, all good.
