### ISSUE TITLE
Show chart ID in the chart library

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#740]
### Description:

Previously ID of the chart was visible in the library because at the bottom of the chart we were displaying full shortcode with that ID: https://prnt.sc/tlglip

Since the latest update (Version 3.4.5) it was replaced with an icon to copy full shortcode by clicking it: https://prnt.sc/tlgmpp
However, clients are missing a way to easily see ID of the chart. It's available at the top of the chart but only if there is no title set for the chart and title displays instead if it's set: https://prnt.sc/tlglip

My recommendation would be to always show the ID of the chart at the top instead of title no matter if it's set because the title appears on the chart itself and it's duplicated: https://prnt.sc/tlgno0

**Thoughts of clients:**

> It makes it a lot harder for us to edit the charts in the dashboard. We have many charts that are virtually identical with the exception of a single segment.

> I am lost at the moment. I think your IDs were shown in previous versions. I need them for including them in the data fields.

> If I clone a graphic, I don't know which is the original and which the clone. The name is the same (no copy added), and without date or ID, I am lost.

I also think it's good to have them as a unique identifier, even when we are referring to one of the charts and want to tell clients which chart is in question it's much better to have ID than the name which is not unique.

In general, I think it really doesn't hurt to have them, we can have them not instead of the title on the top but next to the new icon to copy the full shortcode if that sounds better. Not a full shortcode as before but just the ID.

### Alternatives:

The alternative is to copy the shortcode and paste it somewhere to know the ID of that chart.

This is a feature not a single client is missing, tickets:
https://secure.helpscout.net/conversation/1228749193/237020?folderId=212385
https://secure.helpscout.net/conversation/1231126101/237355?folderId=212385

cc @contactashish13

**Comment by contactashish13** [comment]
@vytisbulkevicius I don't understand why clients would need to see the ID. Can you please summarize your thoughts on this in the original post?

**Comment by vytisbulkevicius** [comment]
@contactashish13 updated with thoughts of clients and my opinion

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/742 shows the ID next to the date updated. Hopefully this is fine @vytisbulkevicius.

![image](https://user-images.githubusercontent.com/12953439/88022553-1c8acc00-cb4d-11ea-8ee4-388ee9651e53.png)
