### ISSUE TITLE
DateFormat in table automatically adds year and sets to 2001

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#743]
### Description:
With the latest version of Visualizer (Version 3.4.5) if you create a table and add date there like that:
![image](https://user-images.githubusercontent.com/36594177/88776471-a9a5d480-d18e-11ea-8aa1-d1e63d991c58.png)
Visualizer also adds a year to the date and table looks like this:
![image](https://user-images.githubusercontent.com/36594177/88776527-c04c2b80-d18e-11ea-87e3-2b71aa019796.png)

This year's value (2001) is not taken from some settings in WordPress as the system date in WordPress is set to today.

Same happens for the client using CSV as a data source: https://docs.google.com/spreadsheets/d/e/2PACX-1vRYYmAIyplOPnlQ5XeCDxdhw7P4EGxn6cC7gPEOvNOTo_iUtQESCYHUJdFoIPFBb9lIqun_ca8C8nTV/pub?gid=662406791&single=true&output=csv

Result:
![image](https://user-images.githubusercontent.com/36594177/88776732-02756d00-d18f-11ea-82ff-e1ccf8662282.png)

This doesn't happen with previous versions, with v 3.4.4 table looks just like in the source data:
![image](https://user-images.githubusercontent.com/36594177/88776961-5c763280-d18f-11ea-9a79-547bc3561f91.png)

### How to reproduce:
1. Create a new table in Visualizer and set only month/date for date value without year.
2. Data can look like this: 
![image](https://user-images.githubusercontent.com/36594177/88777129-89c2e080-d18f-11ea-91ef-b6ec64fd10de.png)

3. Save and chart and check how it looks - year 2001 is added.

### Expected behaviour:

Year shouldn't be added if it doesn't exist in the source data.

### Current behaviour:

Year is added and the year is not current year but 2001.

### Reference:
Screenshots provided

Test instance created:

https://fond-vole.jurassic.ninja 📋 will be destroyed in 7 days.

User: demo 
Password: jhSlo5L0mIXg

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.5

**Comment by contactashish13** [comment]
@rodica-andronache @vytisbulkevicius v 3.4.4 did not have google table charts; they were introduced in 3.4.5. Is this issue with google table charts (as per the screenshot) or with any table chart or with any chart?

**Comment by rodica-andronache** [comment]
couldn't replicate it as mentioned initially.

For `DataTable, it works well`, while for `Google Charts, the field appears empty in the charts library`.
![11](https://user-images.githubusercontent.com/3266155/89188817-d51e2a00-d5a7-11ea-95a2-44952d6bc4c7.png)

And while adding the `Google Chart `chart in a post using the Gutenberg block, this appears.
![12](https://user-images.githubusercontent.com/3266155/89189009-11518a80-d5a8-11ea-9644-4eed0e64583e.png)

**Comment by vytisbulkevicius** [comment]
@contactashish13,

Sorry for not pointing that out - this issue with the year 2001 added by default happens **only with Google Table chart.** It doesn't happen with DataTable even with the version 3.4.5.

Here is how Google Table chart looks with the same file:
![image](https://user-images.githubusercontent.com/36594177/89288384-399bc080-d65e-11ea-9e6b-56a533666485.png)


here is how DataTable type looks with the same file:
![image](https://user-images.githubusercontent.com/36594177/89288391-3ef90b00-d65e-11ea-9284-d24c4635e771.png)


Can be tested here (both tables are created):
```
https://adventurous-tiger.jurassic.ninja 📋 will be destroyed in 7 days.

User: demo OP1TonIRoQaZ 📋

SSH User: userfe3938a1 📋 Password: OP1TonIRoQaZ
```

The data file (CSV) that was used to create table looks like this:
![image](https://user-images.githubusercontent.com/36594177/89288540-7ebff280-d65e-11ea-9aad-1cd24ad908c3.png)


Can be downloaded here: https://easyupload.io/9pecqq

**Comment by contactashish13** [comment]
@vytisbulkevicius this is the default behavior of google table charts. You can try it here https://jsfiddle.net/xo0as4kh/ and see that it adds 2001 by default if the year is missing. If you want it to be treated like a string, then the type should specified be a string not date.

**Comment by vytisbulkevicius** [comment]
Thanks, @contactashish13, this makes sense. @rodica-andronache you have mentioned some other issues - I was not able to replicate them, have you used the same data file that I provided or just created data manually? I'm not sure if I should close this or not

**Comment by contactashish13** [comment]
@rodica-andronache can you please check if this can be closed?

**Comment by rodica-andronache** [comment]
couldn't replicate the issues anymore. Everything seems good
