### ISSUE TITLE
Check Metabase for analytics

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#744]
@selul as discussed, we may want to analyse this further to understand our customers. I think we have been adding features that we feel would be helpful without tracking if they have been. Maybe we should have detailed tracking for each feature we have added over the last year.

My thoughts:

- Adding ChartJS was a wasteful effort as very few seem to be using it (as seen on metabase 4 months ago). 
- No one cares about using ChartJS in Gutenberg or we would have seen a billion tickets with that request. 
- Similarly, the gutenberg implementation was full of bugs, which we are now fixing, so I also believe that almost no one is inserting these charts on gutenberg when it is easier for them to copy/paste the shortcode in the same console.

@rodica-andronache any suggestions?

cc @DanyCaissy

**Comment by DanyCaissy** [comment]
Personally I think the reason we don't see many chartJS charts is the the interface, the dropdown at the very bottom is very small and existing users might not even have noticed that it was added.

That problem would be solved by https://github.com/Codeinwp/visualizer/issues/622, as it would give both libraries the same amount of real estate. At this point we could get a good idea of what users prefers, based on new charts.

**Comment by rodica-andronache** [comment]
I also feel that chartJS is not visible/easy to spot where it is, at the bottom of the page, and in that select, causing people to miss them. I wasn't aware of it for a long time, while using the plugin. 
I'm not exactly sure that would be ideal, but I'm thinking that chosing the library could be an extra step in the wizard, after you choose the chart type.
