### ISSUE TITLE
Confusing chart title details

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#745]
### Description:
When changing the titles of the charts from back-end, two charts have _"Text to display in the back-end admin area"_ under the **title label**, and in the front-end the text is the same as the others _"Text to display above the chart"_. This happens to Gauge and Timeline and it's confusing **when changing the title from editor** as you can't see it anywhere and the other charts have it.

### How to reproduce:
1. Create the Gauge and Timeline charts.
2. In back-end, check the `Settings > General Settings > Title > Chart title` details.
3. In editor, add a chart and go to `Advanced options > General settings > Title > Chart title`.

### Expected behaviour:
In editor, under the label, the text to be _"Text to display in the back-end admin area"_.
### Current behaviour:
The text is _"Text to display above the chart"_.
### Reference:
https://prnt.sc/tt9fa6 -> Back-end (Gauge chart)
https://prnt.sc/tt9g2o ->Editor (Gauge chart)

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.5

**Comment by contactashish13** [comment]
@irinelenache some charts do not support the title attribute in the chart display area and that is why the title is only used for the admin area. Those charts have `Text to display in the back-end admin area`. The charts that support the title attribute as part of the chart display have `Text to display above the chart`. This cannot be fixed till google visualization tools fixes this.

**Comment by irinelenache** [comment]
@contactashish13  in admin area the charts that don't support the title attribute have `Text to display in the back-end area`, but the same charts, in editor, have `Text to display above the chart`. It's a bit confusing and i thought they should have `Text to display in the back-end admin area` in the editor too.
