### ISSUE TITLE
[WP 5.5] Notices appearing when editing posts/pages

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#748]
Similar to what we had in the sdk https://github.com/Codeinwp/themeisle-sdk/issues/91, there are some `notices` appearing when `editing/adding a new page/post`, when using Visualizer.
The notices look to come from Visualizer itself in this case and can be seen here if you pause the video https://www.loom.com/share/0a1c0f5dd4f7452e941fe828acfa2940
This happens just in the WP 5.5. I've tested using `WP 5.5-RC2-48740`

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/749 addresses this. It would be a good idea to test how the front end actions behave as well as this change will affect those.
