### ISSUE TITLE
check if focus default value is set

### ISSUE THREAD

**Issue by selu91** [Codeinwp/visualizer#75]
Can you check if the default value for the focus target in the line settings is set, and it's value is  'Focus on a single data point ' ? 

Thank you !

**Comment by contactashish13** [comment]
@selu91 do you want me to set this whenever the plugin in activated?

**Comment by selu91** [comment]
yes, exactly.

**Comment by contactashish13** [comment]
rather, when every chart is saved.

**Comment by selu91** [comment]
i would like for the users to have the default value set in order to work from the first time the focus.
