### ISSUE TITLE
Google GEO chart is not rendering if 3rd data column is added

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#750]
### Description:

When creating GEO chart it doesn't render if 3rd data column is added. 
Any data can be added as the 3rd column like this: https://prnt.sc/txdx1q

The chart is displayed in the preview: https://prnt.sc/txdxec
However, after you click save chart it can be displayed and just spins: https://prnt.sc/txdxun

If you add it on the website it doesn't display and nothing is rendered. Example:
![image](https://user-images.githubusercontent.com/36594177/89831933-5442cd80-db67-11ea-8a6a-1a33ebd06e0a.png)

**No errors in browser console neither on the website nor in the dashboard where chart spins.**

I tried rolling back to previous versions of Visualizer and chart renders just fine with version 3.4.3

### How to reproduce:
1. Using Visualizer 3.4.4 or 3.4.5 create a Geo chart.
2. Add the 3rd data column to the chart.
3. Try to save the chart and check it in Visualizer library or try adding to the post/page.

### Expected behaviour:

The chart to render.

### Current behaviour:

The chart doesn't render - spins in the dashboard and doesn't appear in the front-end.

### Reference:
Provided in the description.

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.5

**Comment by vytisbulkevicius** [comment]
ticket: https://secure.helpscout.net/conversation/1250100723/240322/

**Comment by contactashish13** [comment]
@vytisbulkevicius AFAIK geo charts, like pie, only work on 2 values/columns. Why is a third value being added? Is it a valid use case?

**Comment by vytisbulkevicius** [comment]
@contactashish13,

In provided examples additional value like Area of the country/city can be passed instead of the population only:
https://developers.google.com/chart/interactive/docs/gallery/geochart#displaying-proportional-markers

And it works fine in the preview until chart is saved - you can hover on the country/city and both values are shown but after chart is saved it doesn't work. And also it worked fine till version 3.4.4 was released.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/753 addresses this. This would have affected all charts that do not support annotations viz. 'table', 'timeline', 'gauge', 'geo', 'bubble', 'candlestick' so it would be a good idea to test all of them.

**Comment by irinelenache** [comment]
@contactashish13 
Google GEO chart works fine now with 3 columns, but im not sure what to test exactly in the other charts

**Comment by contactashish13** [comment]
@irinelenache changes are often not restricted to one chart type - they affect other charts too. That is why I suggested comprehensive regression testing with the other charts.
