### ISSUE TITLE
Refreshing page while charts are still loading causes them not to render at all

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#751]
### Description:

With Visualizer versions 3.4.4 and 3.4.5 if the page, where charts are placed, is still loading and you hit refresh page again - page loads without charts on it at all. This is not so common behavior but sometimes visitor refresh the page if loading takes longer than they expect or just accidentally hit refresh and this causes charts not to render at all.

### How to reproduce:
1. Add Visualizer charts to some post or page (using Visualizer 3.4.4 or 3.4.5 (latest))
2. Go to that page and see that charts are correctly rendered
3. Refresh the page and hit refresh again while the charts are still loading (not visible) - after this page should load without charts rendered.

**The lazy load was not used.**

### Expected behaviour:

Charts should still render no matter if you refresh the page again or not.

### Current behaviour:

Charts do not render after a duplicate refresh.

### Reference:
Recording: https://www.loom.com/share/a7f7c41330444df1aeb72846ad4df8e0

Can be tested here:
https://round-trout.jurassic.ninja/2020/08/11/testvisualizer/

**User**: demo
**Password**: 8qa8gZ7va5gf

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.5

**Comment by vytisbulkevicius** [comment]
ticket: https://secure.helpscout.net/conversation/1231126101/237355?folderId=212385

**Comment by contactashish13** [comment]
@vytisbulkevicius this is a known issue and cannot be fixed currently. The only way out is to wait for 5 seconds and refresh the page again - you should get the charts back.

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/1267758415/242933/
