### ISSUE TITLE
numberFormat doesn't work in Bar chart if there is column for annotation value in between

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#752]
### Description:

When creating a Google bar chart it's possible to add a column with values for the Annotation type. This works fine, however, when the column for annotation value is used the numberFormat field for the next column which is value for the bar no longer works.

This is how data looks like: 
![image](https://user-images.githubusercontent.com/36594177/89913060-f44a3680-dbfb-11ea-92a3-3c0270a74b22.png)

Same data in text type:
```
Campus,Masters,annotation1,Doctoral
string,number,string,number
Boston,0.41,"(This is expected to increase significantly, because the thesis requirement has been dropped.)",0.67
```
The rendered chart looks like this (Even though numberFormat is also set to #% for this value):

![image](https://user-images.githubusercontent.com/36594177/89913390-54d97380-dbfc-11ea-8b8d-be833e702fb0.png)

_If the column for annotation is removed from data and only number values are used - numberFormat works fine for both values and percentage value is displayed._

### How to reproduce:
1. Create a bar chart type and use the data provided above
2. Change second series type to annotation
3. Set numberFormat to **#%** for the third series to show percentage value on hover.

### Expected behaviour:

NumberFormat should work for all numeric values.

### Current behaviour:

The percentage value for the third series is not shown - numberFormat doesn't work.

### Reference:

Recording: https://www.loom.com/share/ee1e80dc788341c492c204ccf1914d02

Can be tested here:
https://just-boa.jurassic.ninja 📋 will be destroyed in 7 days.

**User**: demo
**Login**: H7CYb6CtY9fA 

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.5

**Comment by vytisbulkevicius** [comment]
ticket: https://secure.helpscout.net/conversation/1244098522/239468/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/754 fixes this.
