### ISSUE TITLE
Cypress: Gutenberg tests fail/crash on WP 5.5

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#755]
### Description:
If WP 5.5 block related changes are supported in the tests, cypress crashes.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/756

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/763 tries to fix the error that made travis fail (https://github.com/Codeinwp/visualizer/pull/762#issuecomment-694799700)

**Comment by rodica-andronache** [comment]
@contactashish13 is still failing, do you want to give it another try?

**Comment by contactashish13** [comment]
@rodica-andronache this is not going to pass. travis keeps crashing. 

![image](https://user-images.githubusercontent.com/12953439/93749633-dbc83580-fc17-11ea-96a4-49d822bf0ad4.png)
