### ISSUE TITLE
Import JSON: Reordering columns only reorders the label not the associated data

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#759]
### Description:
When using JSON endpoint in Visualizer you can reorder columns by dragging them. This functionality works and you can reorder columns when editing the data but when "Show chart" is clicked or you save the chart only the **label** is changed and the **value** of that label remains in the original column.

Video about it: https://www.loom.com/share/e1f4c43767ca4684a266a87183fa2389

### How to reproduce:
1. Create a new chart (for example a table or bar chart)
2. Use import data from URL and use JSON endpoint: https://compassdevapp.compmort.com/Scoreboardapiweb/scoreboard/getscoreboard
3. On Step 4 (Select the data to display in the chart) include several columns and try to reorder them - columns are being reordered in this view but after you click show chart only the label is reordered and values remain in original columns.

### Expected behaviour:

Not only the label should be reordered but also the value that belongs to that label.

### Current behaviour:

Only the label is reordered.

### Reference:

Video table reordering: https://www.loom.com/share/634c75b6e21f4ffaa75853f323194ca9 (works in a same way for both Google Charts and DataTable)
Video bar chart reordering: https://www.loom.com/share/e1f4c43767ca4684a266a87183fa2389

### Technical info
* WordPress version: 5.5
* Plugin version: 3.4.6

Ticket: https://secure.helpscout.net/conversation/1259716244/241743/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/760 fixes this.

**Comment by contactashish13** [comment]
The latest commit fixes this issue.

**Comment by irinelenache** [comment]
@contactashish13 tested it and it works fine now! :+1:

**Comment by rodica-andronache** [comment]
@contactashish13 found another issue ( unfortunately after the release ), but we can have another one for this.
After you create the chart using import from JSON, if you try to `edit` it, the chart goes crazy, as you can see in the video. I've tested with the previous version and was not happening before, so it's related to this. 
https://www.loom.com/share/21889be92023475aae3a37ce5cad1023

**Comment by contactashish13** [comment]
@rodica-andronache can you please create a new issue for this? Also, can you check if this happens with any other chart type (e.g. bar) because for me it didn't happen with that.

**Comment by rodica-andronache** [comment]
@contactashish13 ok, moved it here https://github.com/Codeinwp/visualizer/issues/765. Tested for Bar too, you can see in the video what happens when I try to edit it.
Do you think this issues or https://github.com/Codeinwp/visualizer/issues/764 have anything to do with the pro version, or we could release https://github.com/Codeinwp/visualizer-pro/pull/278 in the meantime?

**Comment by contactashish13** [comment]
@rodica-andronache it seems to be independent of the pro version so you can release pro if you want.
