### ISSUE TITLE
Warning is thrown when remote file is used as source

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#764]
### Description:
After the recent upgrade if Chart/Table is using an external source (CSV) file as a resource Visualizer throws a warning on the page where the chart is added:

`Warning: Declaration of Visualizer_Source_Csv_Remote::getData() should be compatible with Visualizer_Source::getData($fetch_from_editable_table = false) in /srv/users/user71b5fd9c/apps/user71b5fd9c/public/wp-content/plugins/visualizer/classes/Visualizer/Source/Csv/Remote.php on line 50`

After rolling back to 3.4.6 the warning disappears.

### How to reproduce:
1. Create a new chart and use CSV file as an external resource.
2. Add the chart to post/page and go to that page.
3. You'll see the warning on the page below the chart. (It's also visible in the Charts Library).

### Expected behaviour:

No warnings.

### Current behaviour:

Warning is thrown.

### Reference:

https://finned-cattle.jurassic.ninja/2020/09/23/first-chart/ (page where warning is visible)
![image](https://user-images.githubusercontent.com/36594177/94085980-4cd33d00-fe12-11ea-883d-d06b83e3c6e8.png)

![image](https://user-images.githubusercontent.com/36594177/94085997-55c40e80-fe12-11ea-9060-c9a76a44b876.png)

Can be tested here:
https://finned-cattle.jurassic.ninja/wp-admin will be destroyed in 7 days.

User: demo
Password: NhFQrmyHR27M

### Technical info
* WordPress version: 5.5.1
* Plugin version: 3.47

**Comment by vytisbulkevicius** [comment]
Tickets: 
https://secure.helpscout.net/conversation/1290796816/246412/
https://secure.helpscout.net/conversation/1289498073/246215/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/773 fixes this
