### ISSUE TITLE
Can't edit charts imported from JSON

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#765]
@contactashish13 
After you create the chart using import from JSON, if you try to edit it, the chart goes crazy, as you can see in the video. I've tested with the previous version and was not happening before, so it's related to this.

Table chart
https://www.loom.com/share/21889be92023475aae3a37ce5cad1023

Bar chart
https://www.loom.com/share/524c9543872243979cb3098866b33e21

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/767 addresses this
