### ISSUE TITLE
Pie chart slices offset problem in gutenberg editor

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#769]
### Description:

When editing a **pie chart** in gutenberg editor, after setting `slice offset` to some slices and saving, the offset is moved to other slices.
I found that the slices offset control is empty in editor https://prnt.sc/uqkkw6 and after setting empty values to 0, the issue isn't happening anymore.
### How to reproduce:

1. Create and add a pie chart to a post.
2. Set slice offsets to a few slices.
3. Save the chart.

### Expected behaviour:
After saving, the selected slices should have offsets
### Current behaviour:
After saving, the offset goes to other slices.
### Reference:

https://www.loom.com/share/779703a30c3344d3816b5b675c606c29
### Technical info
* WordPress version: 5.5.1
* Plugin version: 3.4.8

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/774 addresses this by making offset as number field.
