### ISSUE TITLE
Multiple charts on the same page don't render for Safari & Edge

### ISSUE THREAD

**Issue by dpellenwood** [Codeinwp/visualizer#77]
Hello,

We're using the charts plugin to display several charts (via shortcode) on the same page. In Chrome, Firefox and IE the charts load and look great. In Safari (on a Mac) and Edge, only the first chart is rendered. The other instances get the shortcode embedded, but it never renders.

You can see an example here: http://conroe.tri.be/schools/stewart-k-6-school/

Any ideas why this might be happening?

Thanks for the help.

**Comment by selul** [comment]
@dpellenwood the example page is not working ?

**Comment by dpellenwood** [comment]
Sorry about that bad URL. I completely forgot we've got it blocked for unauthenticated traffic. Here's the updated example URL with a auth bypass:

http://conroe.tri.be/schools/stewart-k-6-school/?secret=secret

**Comment by selul** [comment]
@contactashish13 can you please check what issue could be ?

**Comment by contactashish13** [comment]
@selul we've addressed this kind of a bug before as well: https://redbooth.com/projects/1529021/tasks/22205522

**Comment by contactashish13** [comment]
@dpellenwood This appears to be an issue with the latest library/safari combination. Even this example http://jsfiddle.net/katalin_2003/Lz3yj9gu/ that uses the latest API does not work on safari but http://jsfiddle.net/kimmobrunfeldt/79ffvayr/ uses the old API and works.

**Comment by dpellenwood** [comment]
@contactashish13 Both of those examples work fine for me in all browsers. Specifically, in Safari:

![image](https://cloud.githubusercontent.com/assets/1151082/16657708/0a9e5fac-4429-11e6-98a8-d182e6555ef1.png)

![image](https://cloud.githubusercontent.com/assets/1151082/16657721/1a065da0-4429-11e6-8183-857e6466a0f4.png)

And neither of those examples relate to our specific case where the first chart renders fine in *all* browsers (regardless of the chart type), but the remaining charts on the same page don't render in Safari or Edge, but they do in Chrome, Firefox, and IE.

**Comment by dpellenwood** [comment]
Curious if there has been any progress here. Thanks!

**Comment by selul** [comment]
@dpellenwood it's hard to replicate the issue and i think will take more time. We will keep you updated when is done

**Comment by contactashish13** [comment]
@dpellenwood we are able to see multiple charts in the following OS/browser combinations (screen shot attached)

1) El Capitan + Safari 9.1 and Safari Tech Preview
2) Yosemite + Safari 8
3) Mavericks + Safari 7.1

![bs_macelc_safari_9 1](https://cloud.githubusercontent.com/assets/12953439/16795480/27893836-48fb-11e6-8e2b-b5e994d0cd24.jpg)
