### ISSUE TITLE
Geo chart throws error only in Gutenberg Editor

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#770]
### Description:

Geo chart throws an error in gutenberg editor, before and after selecting it to be added, but it works fine in front-end.
May be related to https://github.com/Codeinwp/visualizer/issues/675
### How to reproduce:

1. Create a Geo chart.
2. Add it on a post. 
3. Check changes in editor and front-end.

### Expected behaviour:
The chart should load in editor.
### Current behaviour:
The chart works only on front-end.
### Reference:

https://www.loom.com/share/09ee8550cfac4b5fa3d908f6d01473d0
### Technical info
* WordPress version: 5.5.1
* Plugin version: 3.4.8

**Comment by vytisbulkevicius** [comment]
Thanks @mghenciu, the thing that it doesn't work on Posts looks to be an isolated case for TasteWP instances. On other servers it works added to Posts as well (using both ways), the only issue that exists is that it throws the error when added via Gutenberg editor.
