### ISSUE TITLE
Option to download CSV data of the chart without the row with series type

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#772]
### Description:
Visualizer has an option to enable the ability to download the chart's data in CSV format in the front-end for users. Few users asked if it is possible to make that CSV file be downloaded without a series type (_string, number, boolean, date, datetime, timeofday_).

![image](https://user-images.githubusercontent.com/36594177/94718370-57358f80-035a-11eb-86b6-5ef0f2034023.png)

I'm not sure if this should be the only option as some users might want to have that row but maybe we can have some filter that could be used to exclude that line if clients do not want to have it in the downloaded version of the chart's data?

### Alternatives:
I am not aware of an alternative that we could offer.

**Comment by irinelenache** [comment]
@girishkrishaweb i tried to test this but i can't find the option to exclude series type. can you provide a screenshot or some test instructions, please?

**Comment by girishkrishaweb** [comment]
@irinelenache To exclude series type from download CSV, we have added a filter for it. By default the series type will be in export data when you will export CSV data. You need to add filter `add_filter( 'vizualizer_export_include_series_type', '__return_false' );` to exclude it from export data.

**Comment by irinelenache** [comment]
@girishkrishaweb in which file should i add the filter?

**Comment by girishkrishaweb** [comment]
@irinelenache You need to add the filter in the current theme's **functions.php** file or you can add the filter on custom_plugin.php files if you have a custom plugin.
