### ISSUE TITLE
The data will not save or update

### ISSUE THREAD

**Issue by zebrastribe** [Codeinwp/visualizer#784]
### Description:

The plugin does not save the data and cannot update or import new data.

### How to reproduce:

1. New install of plugin og wp
2. make a new graph
3. try to edit the data

### Expected behaviour:
The data should updated
### Current behaviour:
The data is not updated
### Reference:

Also look here:
https://wordpress.org/support/topic/stable-version-please/
I install version 3.4.5 and that version works

### Technical info
* WordPress version: 5.6
* Plugin version: 3.4.9

**Comment by rodica-andronache** [comment]
Hi @zebrastribe,

Do you still have issues with the latest update 3.4.10?

**Comment by zebrastribe** [comment]
> Hi @zebrastribe,
> 
> Do you still have issues with the latest update 3.4.10?

On my empty wordpress install the issue has being fixed. 
Thank you for a quick handling for the bug :-)
