### ISSUE TITLE
Mobile display of charts

### ISSUE THREAD

**Issue by carlosinho** [Codeinwp/visualizer#786]
Not sure this is the right place to mention this, but the way Visualizer handles charts on mobile is not very good.

Check out this post https://www.codeinwp.com/blog/how-to-invest-in-stocks/

The charts on mobile get converted to raw data tables. ![chart bad](https://user-images.githubusercontent.com/10775157/102492713-5d422f00-4072-11eb-8f94-f6f0120ae0ce.png)

This is not useful to the reader at all.

It could simply look like this ![chart good](https://user-images.githubusercontent.com/10775157/102492705-5adfd500-4072-11eb-94a9-cc5b416cd47f.png)

And if not this, then the chart can be converted to an image file. I think we had something like that before.

cc @selul

**Comment by selul** [comment]
We can explore if we can add an image representation of the chart for some context, i.e maybe generated via a PHP script or via CRON. The goal is to easy represent a chart via an image

**Comment by girishkrishaweb** [comment]
@irinelenache I have checked this URL https://www.codeinwp.com/blog/how-to-invest-in-stocks/ and on this page, we have an issue with chart render but when I tested the same with multiple test/demo setup I haven't got this issue anywhere.

Is it possible you can verify with different test setup? It seems like something is wrong with codeinwp site.

**Comment by irinelenache** [comment]
I couldn't replicate it either. I tried with Neve / Neve pro installed, different plugins and different blocks added in the page
