### ISSUE TITLE
Consider trimming BOM (byte order mark) characters from JSON endpoint result

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#791]
### Description:
The client reported that his JSON endpoint is using a BOM character at the beginning of the JSON response that cannot be easily removed. With that character there, when they try to click "Fetch Endpoint" to get the JSON, Visualizer says it doesn't look like it's a valid JSON format (no additional errors/notifications).

A suggestion is to trim such characters from the endpoint result. Client provided code that worked to achieve this:

In `visualizer\classes\Visualizer\Source\Json.php`

Change this:

`$array = apply_filters( 'visualizer_json_massage_data', json_decode( wp_remote_retrieve_body( $response ), true ), $url );`

To this (of course, it doesn't have to be on separate lines/steps):

```
$bom = pack('H*','EFBBBF');

$responseBody = wp_remote_retrieve_body($response);

$responseBody = preg_replace("/^$bom/", '', $responseBody);

$array = apply_filters( 'visualizer_json_massage_data', json_decode( $responseBody, true ), $url );

```
### Alternatives:

Remove BOM characters from JSON endpoint before using it in Visualizer or use the code provided that requires modifying the plugin's file directly.

Reported here: https://secure.helpscout.net/conversation/1437544511/268598

**Comment by irinelenache** [comment]
@girishkrishaweb @vytisbulkevicius can you provide some test instructions for this issue, please?

**Comment by girishkrishaweb** [comment]
@irinelenache Yes sure.
Here are the steps which you need to follow.

1. Go to the **Chart** and edit it.
2. Select **Source** from the right top corner's tab.
3. Expand **Import data from URL**.
4. Expand sub-section **Import from json** of main expanded section.
5. Now click on to **Create Parameters** button and enter JSON URL with DOM characters.

**Screenshots**
https://tinyurl.com/ygrg4tzu
https://tinyurl.com/yzgsajgy

**Comment by selul** [comment]
@girishkrishaweb can you provide a JSON URL with these chars?

**Comment by selul** [comment]
you can use JSON mocking generators, something like https://mocki.io/

**Comment by vytisbulkevicius** [comment]
@irinelenache,

This is the URL that client provided as an example:
https://compass.servicefirstmtg.com/webservices/my-purchase-vs-refi-json/?timeframe=Rolling12&loemail=ndavenport@servicefirstmtg.com

It still works so should be good for testing.

**Comment by irinelenache** [comment]
@vytisbulkevicius @girishkrishaweb @selul thanks for the help, did some testing and i see it works fine now 👍
