### ISSUE TITLE
How do I change vertical values in a chart

### ISSUE THREAD

**Issue by CreativeCharly** [Codeinwp/visualizer#80]
As I adjust the plug ins Visualiser in mijn WP Enfold theme there was told I could adjust the vertical values of the charts. But Somehow I can't do it, it's not possible to change the values.

Can somebody please help me and lee me what to do to change it?

**Comment by selul** [comment]
@CreativeCharly can you please contact the support team on themeisle.com/contact/ with more details about the issue ?
