### ISSUE TITLE
Charts do not show when a user is logged in

### ISSUE THREAD

**Issue by dshakya** [Codeinwp/visualizer#801]
### Description:
The chart is not displayed when a user is logged in. The chart displays fine when a user is logged out or to the general public.

### How to reproduce:

1. Log in to Wordpress
2. Visit page with the chart
3. Chart does not display

### Expected behaviour:

Chart is displayed

### Current behaviour:

Chart only displays when logged out.

### Reference:

https://wordpress.org/support/topic/visualizer-charts-not-showing-when-logged-in-to-wordpress/

### Technical info
* WordPress version: 5.7.1
* Plugin version: 3.5.0

**Comment by selul** [comment]
Thanks for reporting @dshakya! 

We will look into it.

**Comment by girishkrishaweb** [comment]
@dshakya I have tried to reproduce the issue but I haven't found anything. Is it possible for you to share the screenshots/video with us?

Also, I would recommend you to check this issue after disabling all other plugins and do let us know about it.

Thanks

**Comment by Nexus2k** [comment]
Looks like the issue is caused by having the "Google Site Kit" Plugin installed, it does load it's own version of charts/loader.js. Disabling it gives me back the ability to edit charts within the Post editor.

**Comment by dshakya** [comment]
Thanks @Nexus2k for debugging it. I deactivated the Google Site Kit and  - Yes, I can see the chart when logged in. @girishkrishaweb - How do we solve this we Sitekit is important tool. Thanks.
