### ISSUE TITLE
Special Characters not showing

### ISSUE THREAD

**Issue by ered15** [Codeinwp/visualizer#81]
Word disappears when using special characters like áéíóúñ, how can I fix this?

**Comment by selul** [comment]
@contactashish13 can you investigate this ?

**Comment by contactashish13** [comment]
@ered15 this seems to be fine (screenshot below). Can you please give more details on where you are trying to add the special characters?

![image](https://cloud.githubusercontent.com/assets/12953439/16943970/12534752-4dbc-11e6-9958-51f312a92021.png)
