### ISSUE TITLE
Can't edit chart colors as rgba

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#818]
### Description:

Some charts have rgba colors set by default, but if i want to change it, i can't input another rgba value, neither by typing or copy-pasting. 
### How to reproduce:

1. Create a chart (I used Polar area cause it had rgba values by default)
2. In a color picker, try to add rgba values

### Expected behaviour:
Changing rgba values should work
### Current behaviour:
Adding a rgba value doesn't work neither by typing or copy-pasting
### Reference:

Default rgba value - https://vertis.d.pr/dg7xIE
Video - https://www.loom.com/share/38b2d0b0456046b79f6ed75a30815cf1
### Technical info
* WordPress version: 5.7.2
* Plugin version: 3.5.1

**Comment by girishkrishaweb** [comment]
@irinelenache We have added wp-color-picker alpha support to get RGBA value from picker but you couldn't write RGBA value manually. This is the default of behaviors of wp-color-picker.
https://www.loom.com/share/c548cbf7ab794bb19d601d9b3df5ceff
