### ISSUE TITLE
Disable/Enable Switch for Automatic Image Download of the Chart in the Media Library

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/visualizer#825]
### Description:
At this moment, whenever you create a chart, an image of that chart is created in the Media Library. It doesn't matter if the Frontend Action of "Download Chart as Image" is activated or not. It would be useful to have a switch that enables the admin to select if he wants an image of the chart to be saved in his media library or not.

Some user have limited spaces on their servers thus this feature kills their website.

### Alternatives:
If the switch cannot be created then we could disable this automation on default. It can be enabled whenever the user selects the "Download Chart as Image" frontend action.

**Comment by selul** [comment]
here we can add a checkbox in the chart settings which when enabled will create the image for the chart in the media library. By default, the setting will be off. We can name the setting `Save chart as an image inside Media Library`. 

The default, as well as the saved value, should be filterable in case that devs would like to enable this sitewide or change the default behavior. 

Let's ignore the setting `Download Chart as Image`

**Comment by girishkrishaweb** [comment]
@selul If we will give the enable/disable option that would be created an issue with the AMP pages and Shortcode attributes (use_imge=yes).

On disable, When someone creates a google chart, the chart will not display on the amp page and shortcode attributes because a plugin renders chart image on AMP and shortcode page.

**Comment by selul** [comment]
@girishkrishaweb can we do the following: 

1. If the amp is active, we turn the default `on` automatically
2. If the amp is added later on and we don't have an image associated, we can switch to the default behavior that we had before? the table display or hide the chart entirely if is easier

**Comment by girishkrishaweb** [comment]
@selul For the second point, You mean, we need to restore the default behaviors (Char will show in table format).

**Comment by selul** [comment]
yes, or either we can stop rendering entirely chart if on AMP.

**Comment by girishkrishaweb** [comment]
@selul Ok. Thanks I'll review it.

**Comment by selul** [comment]
Thinking more about this, lets use the table approach when the image is not available, on amp.

**Comment by girishkrishaweb** [comment]
@irinelenache Added new setting field from **General Settings -> Save chart as an image inside Media Library** - https://www.awesomescreenshot.com/image/10748680?key=005190248a673b974c2b3d6ab17cc626
