### ISSUE TITLE
No direct link in "Add media"

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#84]
It looks like we have a button where users can directly add a map to the post on integreo, but there is none for visualizer.

A user requested asking for this, was it ever possible? http://prntscr.com/btvf53

Also I know we have the previous issue for moving these settings page from the media area, what would we do in this case for a quick add? The usual answer of course is a tinyMCE button.

@selul

**Comment by UVLabs** [comment]
It seems this was possible before: https://github.com/Codeinwp/visualizer/wiki/How-can-I-create-a-chart%3F

**Comment by selul** [comment]
@contactashish13 can you please investigate ? I know that this was integrated in the previous version ?

**Comment by selul** [comment]
@contactashish13 which is the difference between visualizer-google-jsapi-old and visualizer-google-jsapi-new ? Why we need to use both of them ?

**Comment by contactashish13** [comment]
@selul as mentioned https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading

![image](https://cloud.githubusercontent.com/assets/12953439/16947138/e1cd320a-4dca-11e6-9efe-7fcb38c90bfd.png)

**Comment by selul** [comment]
@contactashish13 ok, @UVLabs can you please check if the media link s working as it should ?

**Comment by selul** [comment]
i have checked and all works fine
