### ISSUE TITLE
remove pointer from the free version 

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#85]
IN the free version we have a wp-pointer which tells users about the pro version. 

i would like to remove it for now

**Comment by contactashish13** [comment]
@selul do you want to remove all pointers from the free version?

**Comment by selul** [comment]
@contactashish13 there is just one i think.

**Comment by selul** [comment]
can you please also remove the js enqueue : 

https://github.com/Codeinwp/visualizer/blob/development/classes/Visualizer/Module/Admin.php#L256-L287 


And the js file for pointer from the plugin 

Also please remove the feedback mechanism we wanted to implement firstly here, we would go further with the intergeo version, but later on we will implement here. 

You can look at the commit where you integrated this, to help you remove the code.

Thanks !
