### ISSUE TITLE
Changing Line Chart series style to dot on some series changes the order of tooltip information

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/visualizer#850]
### Description:
If you apply dot style to a line in a Line Chart you will notice that the tooltip information changes order for that line series. An example is when all series are lines the data in the tooltip is Date, then Title and Value whilst on the dotted lines is Title, then Date and Value.

### How to reproduce:
1. Install Visualizer and Create a Line Chart
2. You can import a chart or use the default one as in my example
3. Go to Settings > Series Settings > Choose one series > Change Line width to 0 and Point Size to a value > than 0 > Save Chart
4. Observe how for that dotted line only, the tooltip data has changed its order as opposed to the not modified series.

### Expected behaviour:
The tooltip data remains the same across all series, no matter their display setting.

### Current behaviour:
The tooltip data has changed the order of information for the series formatted with dots.

### Reference:
User Reported here: https://wordpress.org/support/topic/dates-shown-wrong-tooltip-format-inconsistent/#post-14969290
Screencast of issue: https://vertis.d.pr/Aoo07E

### Technical info
* WordPress version: 5.8.1
* Plugin version: 3.7.0

**Comment by girishpanchal30** [comment]
@Skystream96 It accepts a higher than zero values(e.g. 0.1,0.2,.03) in `lineWidth` setting option( https://tinyurl.com/yjlnf2m4 )

It will display like this - https://tinyurl.com/yjlnf2m4

Do you think, we need to disallow 0 in this field?

cc @selul
