### ISSUE TITLE
Multiple Visualizer charts causing rendering issues (blank page)

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#851]
### Description:
If you add more charts on one page (the number could be different depending on the charts probably) you can get a blank screen when loading a page with Visualizer charts.
No errors are visible even with debug mode enabled.

In my case as I was testing on a fresh test instance the problem happens with 8 default charts on the same page, however, users reported the same problem with more than 3 charts so it could be because data used in the charts or size of the page itself.

Here is a test page with multiple (8) charts - https://bathecloth.tastewp.com/2021/10/18/multiple-visualizer-charts/
Backend - https://vertis.d.pr/gLj11k

If I remove one or more charts, the page renders fine again.

### How to reproduce:
1. Create 8 or more Visualizer charts
2. Create a new page and add all the charts to the same page
3. Try loading the page - you should get a blank screen

### Expected behaviour:
Page should load or at least some error should appear about some server limit being exceeded.

### Current behaviour:
Blank page is loaded.

### Reference:
The issue reported by multiple clients here -  https://wordpress.org/support/topic/when-i-use-more-than-3-charts-on-one-page-the-page-becomes-blank/
And here - https://wordpress.org/support/topic/multiple-charts-will-let-the-page-size-increase-incredibly/ (performance issues)
They said this wasn't happening before and appeared since Visualizer updated and after moving to WordPress 5.8.
I tried this with older Visualizer versions and nothing changes.

However, I tried with WordPress 5.7.3 and it works fine, even with 9 charts the page renders -
https://obeythread.tastewp.com/2021/10/18/158/

Is there something we can do?

### Technical info
* WordPress version: 5.8.1
* Plugin version: 3.7.0

**Comment by girishpanchal30** [comment]
@irinelenache We installed the LiteSpeed Cache plugin to reproduce the issue in my local machine and we have fixed it.

Could you re-test it?

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

In another [issue](https://github.com/Codeinwp/visualizer/issues/857) that also reports chart being slow a user provided such insights:

> file - visualizer/classes/Visualizer/Module/Frontend.php
> class - Visualizer_Module_Frontend
> method - renderChart()
> line - 263-430
> 
> The problem starts on line 398, when you loop through the class's _charts array. If multiple charts are included in a single page, this loop will run repeatedly as additional charts are saved to the _charts property.
> 
> For example, if I had 3 charts, renderChart() will be called three times, but wp_localize_script will be called for each chart in each loop:
> 
> First loop - wp_localize_script() is called for chart visualizer-1
> Second loop - wp_localize_script() is called for charts visualizer-1 and visualizer-2
> Third loop - wp_localize_script() is called for charts visualizer-1, visualizer-2 and visualizer-3
> 
> Additionally, each time wp_localize_script() is called, it's localizing the data for everything saved in the _charts property, not data specific to one chart. So the page ends up with 6 instances of var visualizer = {"charts":{...}, ...}; and each instance contains progressively more data. The final three instances each contain all the data for all three charts.
> 
> Unfortunately my dashboard contains 9 charts, so you can see how this is causing memory issues and timeouts. I am able to load the page when there are only 7 charts, but this uses about 512MB of memory. I am unable to save a copy of the page to show you, but I've attached a screen shot that has all the instances of var visualizer displayed.

Just FYI if you think this could be changed also as I see in the code that was changed this wasn't the change you made.

Thanks!

**Comment by girishpanchal30** [comment]
@vytisbulkevicius have improved scripts loader like enqueue script & localize script. @irinelenache Could you re-test it?

**Comment by irinelenache** [comment]
@girishpanchal30 Tested with the latest patch and the issue is fixed 👍
