### ISSUE TITLE
CSS perfomance improvements

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#855]
Let's try to do the following to have a better performance for visualizer charts: 

- [x] Load front.css and inline style, we don't need a separate CSS file for that since the CSS is minimal. Apply same thing for front.css in PRO.
- [ ] Review datatable and chartjs CSS and load that in footer, you can review this on how to do it https://wordpress.stackexchange.com/a/186066

**Comment by girishpanchal30** [comment]
@selul I have added inline CSS instead of loading the front.css file in both plugins.
For the second task `datatable` and `chartjs` styles are already loaded in the footer so we can't do anything there.

cc @cristian-ungureanu

**Comment by irinelenache** [comment]
@girishpanchal30 Tested with Visualizer lite and both lite and pro and didn't find any problem, the enhancement seems to work fine 👍
