### ISSUE TITLE
Charts resize on mobile only after you scroll the webpage. Might be related to issue #847

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/visualizer#872]
### Description:
When you create a chart (any type) it will properly size for mobile, however, if you modify the view to Landscape, you need to scroll the page for the chart to properly resize to the Landscape mode. The same happens if from Landscape you switch to normal view. You need to scroll the page for the chart to properly resize. This issue might be related to issue #847 

### How to reproduce:

1. Create a chart
2. Open the page on a mobile device and turn the device into landscape view
3. Observe how the chart is not resizing initially
4. Scroll the page 
5. Observe how the chart is properly resized

### Expected behaviour:
Chart resizes live. You do not need to scroll the page to resize the chart.

### Current behaviour:
You need to scroll the page for the chart to resize properly

### Reference:
[Screencast of the issue on a mobile device.](https://d.pr/rdDqxQ)
No errors show in the console log.

### Technical info
* WordPress version: 5.8.2
* Plugin version: 3.7.1

**Comment by irinelenache** [comment]
@Skystream96 I didn't manage to replicate the issue, tried with more browsers/devices and network throttling and it worked fine for me. Can you please check if you missed some replicating steps or if the issue persists? Thanks.

**Comment by Skystream96** [comment]
Hello @irinelenache I have tried recreating the issue again and for me it is still happening on 2 websites (Php 7.4 and 8). You can access these 2 pages and see if you can reproduce it too?
https://reviewbook.tastewp.com/charts-page/
https://reproduceyak.tastewp.com/charts/

Also, I have to mention that I have tested it on an actual mobile device (IOS in my case in Chrome, Safari) as when I try to replicate it on desktop using Inspector Tool and the orientation button, the charts are behaving correctly.

I managed to check the issue now on an android device and it doesn't replicate there so it might just be affecting IOS devices.

**Comment by irinelenache** [comment]
@Skystream96 Thanks for the input, i could replicate it now on Iphone 11 using Chrome 👍 
@girishpanchal30 Tested the fix and the issue persists, both on my phone and on browserstack (https://vertis.d.pr/5FG0oR)

You can check it here:
```
 Admin area URL: https://heapdowntown.tastewp.com/wp-admin 
 Username: irinel 
 Password: 1G4-gi44QhI 
```

**Comment by girishpanchal30** [comment]
@irinelenache Can you retest again? I have fixed the issue and tested with a real iPhone 11 device

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Now the issue is fixed, thanks 👍
