### ISSUE TITLE
Multiple charts are not loading in a page due to lazy rendering

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/visualizer#877]
### Description:

If I add multiple charts on a page, initially it shows only one chart. The weird thing is that when I right-click and open the "Inspect" window, the other charts load immediately.

What I discovered is that if we disable the lazy rendering option under the chart settings then all the charts load as expected.
Charts with lazy rendering option enabled - https://defectivedinner.tastewp.com/test/
Charts with lazy rendering option disabled - https://defectivedinner.tastewp.com/shortcodes/

### How to reproduce:

1. Create 3-4 Visualizer charts
2. Create a new page and add at least two charts to the pages
3. Try loading the page - you should see one chart only.
4. Now open the inspect element - you will see the other charts.

### Expected behaviour:
The page should load all the charts.

### Current behaviour:
One chart (mostly the last chart that was added to that page) appears on the page.

### Reference:

Screencast >> https://vertis.d.pr/G7Jg0X
HS ticket >> https://secure.helpscout.net/conversation/1749179387/305207?folderId=4354547
WP ticket >> https://wordpress.org/support/topic/4-charts-when-using-safary-but-only-1-when-using-chrome/
Test instance details:
 Admin area URL: https://defectivedinner.tastewp.com/wp-admin 
 Username: poonam 
 Password: 1ufFnRd3dZk 

### Technical info
* WordPress version: 5.8.2
* Plugin version: 3.7.2

**Comment by MarinescuLucia** [comment]
There are a few other users on the forum who reported a similar issue in the last week that I think may be related to this. Sometimes their charts load immediately, sometimes only a few charts load or other times they don't load at all. Unfortunately most of the users didn't come back with a reply yet, so there are no more details about the issue, but I'll add the links to the threads below, maybe they are helpful. Some users said that the issue disappears for them if they roll back to the previous version.

https://wordpress.org/support/topic/inconsistent-chart-loading-after-update-to-3-7-2/
https://wordpress.org/support/topic/only-one-graph-per-page-is-visible-despite-more-having-been-added/
https://wordpress.org/support/topic/charts-not-appearing-on-first-page-load-and-throwing-google-is-not-defined/
https://wordpress.org/support/topic/charts-not-displayed/

**Comment by girishpanchal30** [comment]
Hello, @MarinescuLucia I'm checking this issue I'll update you soon here.
Also, we have an alternate solution to disable the lazy loading charts globally.

Here is the code for the same:
`add_filter( 'visualizer_lazy_load_chart', '__return_false' );`

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Thanks for the note about the filter, we will add it to our documentation.
By the way, doesn't this new lazy-loading feature duplicate what we had before in the Gutenberg block - https://docs.themeisle.com/article/1363-how-to-use-lazy-load-feature-in-visualizer

And do you know how it works if they are both enabled? Maybe that's causing some conflict?

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius This is a new feature for the lazy load plugin script.
Here is the enhancement ticket - Codeinwp/visualizer-pro/issues/315

> And do you know how it works if they are both enabled? Maybe that's causing some conflict?
- It is working properly if both are enabled

Thanks

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/1759041435/306396/
