### ISSUE TITLE
Chart is much wider than it needs to be

### ISSUE THREAD

**Issue by petrakid** [Codeinwp/visualizer#88]
I created a bar/column chart which you can see below.  As you can see, it's way too wide!  All I need are the three sets of bars.  I've tried moving the legend to the side, but it doesn't help.

Also, as you can see in the images, there is ALWAYS an empty item in the legend (both in the bar and in the pie).  This is frustrating!!!
<img width="480" alt="2016-08-10" src="https://cloud.githubusercontent.com/assets/9057136/17560366/6e29d99c-5ee7-11e6-9071-6aa8c4ed99ca.png">
<img width="512" alt="2016-08-102" src="https://cloud.githubusercontent.com/assets/9057136/17560367/718d4100-5ee7-11e6-9344-174cf1618663.png">

**Comment by selul** [comment]
@UVLabs @Basilakis @HardeepAsrani can you check ?

**Comment by UVLabs** [comment]
@petrakid could you please provide us with those CSV files so we could have a look?
