### ISSUE TITLE
Multiple charts on the same page load inconsistently

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#883]
### Description:
This doesn't look related to the lazy-loading feature as I turned it off and this still happens.
Client reported that charts on his website load not every time, I'm able to replicate it, sometimes all the chart loads and sometimes just one of them or none of them. 
Charts do not load on the Firefox browser all the time.

His website is here - https://keywordsentiment.com/
I also exported the charts and tried to replicate them on the test instance here - https://petiterequest.tastewp.com/2022/01/20/483/

Recording of the issue: https://vertis.d.pr/dzF7LA (I'm switching between the private browsing mode and regular mode, in private browsing mode where I'm not logged in as admin it happens almost all the time).
Interesting thing is that opening developer tools sometimes fix the issue so probably screen resizing triggers the chart loading.

### How to reproduce:
1. Open this page - https://keywordsentiment.com/ or this one - https://petiterequest.tastewp.com/2022/01/20/483/ 
2. Try reloading page multiple times, try incognito mode and Firefox browser
3. You should face the issue that charts are sometimes not loaded, sometimes there is an error in the console about google not defined, or jQuery not defined, sometimes there is no errors.

### Expected behaviour:
Charts should be loaded.

### Current behaviour:
Charts are not loaded sometimes.

### Reference:
Issue can be checked here for several days:
 Admin area URL: https://petiterequest.tastewp.com/wp-admin
 Username: bvytis 
 Password: OxWguiFb7go
 
 https://secure.helpscout.net/conversation/1750303307/305322

### Technical info
* WordPress version: 5.8.3
* Plugin version: 3.7.3

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/1763945817/307035

**Comment by ineagu** [comment]
any idea when this would be released?

**Comment by cristian-ungureanu** [comment]
We've just made a release 9 days ago. I was waiting for more things to be ready but we can have a small release on Monday as I saw nothing else is in progress.

**Comment by MarinescuLucia** [comment]
+1 https://wordpress.org/support/topic/multiple-charts-not-rendering-on-the-page/#post-15300242
+1 https://wordpress.org/support/topic/is-it-possible-to-display-two-charts-in-one-page/

For these users the charts are properly displayed after resizing the browser window.
