### ISSUE TITLE
Label "other" is not visible on PIE chart (not rendered)

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#900]
### Description:
If you have many series for the PIE chart those smaller ones are combined to the last group that is called "other".
When you upload a file before you click to save it that "other" label is visible:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/36594177/169509477-68eebe7b-a328-405f-b90e-eaf9e394f8c7.png">

But once you click "Create Chart" that label gets disappeared in both Library and front-end:
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/36594177/169509603-04a59af6-49f4-4c6f-8d3d-53f73ac6efa1.png">

I tried rolling back many versions back and this issue is always present so doesn't look like a regression issue.

### How to reproduce:
You can use this file to create a PIE chart - [WW-Pie-priority-states-2.csv](https://github.com/Codeinwp/visualizer/files/8738665/WW-Pie-priority-states-2.csv)

1. Create a PIE chart and upload the file provided (as it has multiple series)
2. Check that after you import data the "Other" label that combines smaller values is present
3. Click to Save Chart - you'll see that label is not rendered.

### Expected behaviour:
"Other" label should be present
### Current behaviour:
Label not present.
### Reference:
Screenshots provided
Ticket here - https://secure.helpscout.net/conversation/1889352416/323511/

### Technical info
* WordPress version: 5.9.3
* Plugin version: 3.7.5

**Comment by girishpanchal30** [comment]
@vytisbulkevicius 
Fix  "Other label rendering issue on PIE Chart". for details refer below video & test instance.

https://www.awesomescreenshot.com/video/9231129?key=82cdc0f8a3842435a6ee7907bb26af95

**Test Instance**
URL: https://adselection.s2-tastewp.com
username Username: admin
password Password: NR0Ixqb8-n4

**Comment by vytisbulkevicius** [comment]
@girishpanchal30, looks good! Thank you
