### ISSUE TITLE
Charts do not render in some cases with combination of ACF repeater fields

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#914]
### Description:
A client reported that charts stopped rendering with ACF Repeater fields. I made some tests and found out that this is related with improvements made in Visualizer free version since version 3.7.2. With version 3.7.1, it still works.

In the changelog I see this one that should be related:
**Improve JS performance**

This is a page where the issue is happening:
https://rivercyndevdev.wpengine.com/total-return-bond/

### How to reproduce:
1. Create charts and use Visualizer 3.7.2 version
2. Use ACF Repeater fields to add shortcodes
3. Charts are not rendered properly while downgrading to 3.7.1 fixes the issue

Charts are added like this using shortcode:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/36594177/180984096-04efeee7-7109-4c5f-a1d5-fa6ab55f4d6c.png">

A page where they are not loading - https://www.rivercanyonfunds.com/total-return-bond/

We have a test instance shared with this issue occurring that is valid for 7 days if needed.

### Expected behaviour:
Charts should load
### Current behaviour:
Charts are not loading
### Reference:
Screencast - https://vertis.d.pr/I8LmHQ

Reported here - https://secure.helpscout.net/conversation/1958634053/330708/

### Technical info
* WordPress version: 6.0
* Plugin version: starting with 3.7.2 and higher

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I think it seems to relate to the custom trigger some class `visible` to display the chart.
I found some custom trigger events in the theme js file here: https://tinyurl.com/29y56bka

When I add class(`visible`) in visualizer parent div and it starts to display.
Ref: https://tinyurl.com/25jctx6n

The js file( `canyon-partners/js/theme.min.js` ) is minified so I can't get more details above the custom trigger js.

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Sorry for the delay but the user replied only now, I asked him to provide the JS files (minifed and unminified). Are you able to take a look if we can share any more guidance what could be causing the issue with this theme or solve it from our end?

Those files can be downloaded here - https://wetransfer.com/downloads/29963e99a01e061ca3f2196304d84e6d20220808102100/76e8ccef0c890ffb714a5e03b61730a820220808102128/40d6cf

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I'll check and update you here...

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I think it's better if users use the default chart lazy load method instead of a custom solution. we have two ways to enable a lazy load chart and also it improves the page performance.

1) https://tinyurl.com/2fn9vwxw - For individual chart.
2) `add_filter(
  'visualizer_lazy_load_chart',
  function( $lazy_load, $chart_id ) {
    return true;
  },
  10,
  2
);` - Filter for enable lazy load global or condition base.

**Note: Remove JS/CSS related to the custom solution if the user used the lazy load method.**


If a user wants to use the existing solution then update theme.js according to the below diff.
Diff: https://www.diffchecker.com/zPXRfpeO

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Thank you for analyzing this.

Could I clarify to make sure I understand? So the problem here is that user's theme is lazy-loading our charts and the problem occurs because we are already lazy-loading them and duplicate lazy-loading makes them not to load at all?

But I double checked that lazy-loading is disabled for our charts in settings, so then his lazy-loading should work? As it works with version 3.7.1? 

Is there a filter I can provide to him that completely disables the lazy-loading added after version 3.7.1 instead of suggesting to change the theme .js file or that's the only thing we can recommend to him?

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

>But I double checked that lazy-loading is disabled for our charts in settings, so then his lazy-loading should work? As it works with version 3.7.1?
>Is there a filter I can provide to him that completely disables the lazy-loading added after version 3.7.1 instead of suggesting to change the theme .js file or that's the only thing we can recommend to him?

Need to update the theme.js file as well.

I think it would be good if use the default lazy load method instead of a custom solution.

We have added a lazy script loading feature( user interaction events ) for render charts here- https://github.com/Codeinwp/visualizer-pro/issues/315

Thanks

**Comment by girishpanchal30** [comment]
@vytisbulkevicius If the suggestions above work, could you kindly close this issue?

**Comment by vytisbulkevicius** [comment]
The client told me they will try the recommendations and haven't come back, so I assume it worked for them. Thanks for the help, closing the issue.
