### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by luvejo** [Codeinwp/visualizer#918]
### Description:
There is a broken link that is still used across the code base: 
```
http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax
```

### How to reproduce:
1. Verify that this URL is actually in the code base (it is).
2. Open URL.

### Expected behavior:
Link points to a page about the ICU date and time format.

### Current behavior:
The page shows a 404 error.

### Screenshot
This is the link that appears below the "**Data Format**" field: 

![image](https://user-images.githubusercontent.com/16514302/182742644-ef14e413-2745-4e84-989f-374c4c7e5e27.png)

**Comment by girishpanchal30** [comment]
Hello @luvejo,
Thank you for the report, I fixed the broken documentation link and you can see the changes in the next plugin release.
New Docs URL: https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax

Thanks
