### ISSUE TITLE
No Axis Text color option

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#92]
I didn't check all charts but so far I could see that barcharts and filled line charts do not have the option.

If user tries to put a transparent chart against a dark background then there would be readability issues: 
http://prntscr.com/cbix8w @selul

**Comment by selul** [comment]
@contactashish13 can you check ?

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/visualizer-pro/pull/31
