### ISSUE TITLE
Data Format field doesn't seem to work with dates

### ISSUE THREAD

**Issue by luvejo** [Codeinwp/visualizer#920]
### Description:
In the Vizualizer wizard, I try to render a bar chart with dates; but if I fill the "**Data Format**" field, the rendered date is always December 1969.

Here I haven't set any format, yet the rendered date is a bit strange:

![image](https://user-images.githubusercontent.com/16514302/183116414-1b29b018-363a-4eeb-b455-131bc4c73944.png)

Now, when I set a format, all dates become "**December 1969**":

![image](https://user-images.githubusercontent.com/16514302/183117855-f013fa24-c5be-42cb-ad28-eed2063b1e36.png)

### How to reproduce:

1. Create a new **Bar Chart** (using **ChartJS** as a library).
2. Populate it with this data:
```csv
Year,Austria,Bulgaria
date,number,number
2003-02-21,1336060,100361
2004-04-02,1538156,366849
```
3. Set **`MMM yy`** as the Vertical axis "**Data Format**" (the field located at **`Settings`** > **`Vertical Axis Settings`** > **`Formatting`**).

### Expected behaviour:
Dates are formatted using using UCI syntax (i.e, "**Feb 2003**", "**Apr 2004**").

### Current behaviour:
All dates are rendered as "**Dec 1969**".

### Technical info
* WordPress **v5.9.3**
* Visualizer: Tables and Charts for WordPress **v3.7.10**
* Visualizer: Tables and Charts Manager for WordPress AddOn **v1.10.7**

**Comment by girishpanchal30** [comment]
Hello @luvejo,
Thank you for the report, I fixed the axis date format issue and you can see the changes in the next plugin release.
