### ISSUE TITLE
Line chart color options not working as expected. [in visualizer chart library options] +a spin button is not working properly. 

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/visualizer#924]
### Description:

When playing with the different color settings of the chart, I noticed that when you try to make the vertical axis visible by changing the color of the base line it is not visible [both in chart and block options].

Also, a Spin button which can be found under Minor grid lines is not working properly.

### How to reproduce vertical axis base line issue:
1. Go to the visualizer menu and create a new line (or column) chart.
2. Go to chart settings > Vertical axis settings > general settings > base line color.
3. Change the vertical axis base line color.
4. Observe that Nothing changes.

### How to reproduce the spin button issue:
1. Go to the visualizer menu and create a new line chart.
2. Go to chart settings > Vertical axis settings > general settings > Minor grid lines [Same for Horizontal axis settings].
3. Enter a value in the field.
4. Try to increase the value using the spin button.
5. Button doesn't work: It fails to increase the value.
6. Now try to decrease the value.
7. Instead of going to one lower value it goes directly to value 1.

### Expected behavior:

- Vertical axis base line should respect the color settings and be visible.
- Spin button should increase and decrease the value correctly.

### Current behavior:

- Nothings changes [ vertical axis base line is not visible ]
- Button is not increasing the value 

### Reference:
Screenshots For vertical axis issue :
![Screenshot_3](https://user-images.githubusercontent.com/110405452/185570538-1fca855b-13da-41b0-9cc3-f3f61e21ee1d.png)

Screenshot for spin button issue :
![Screenshot_7](https://user-images.githubusercontent.com/110405452/185700599-1540d032-cce9-4703-acf9-d641490f7d89.png)

Screen recording for spin button issue: https://www.loom.com/share/82a3180c28544b11a4013fa497f73c18

### Technical info
* WordPress version: 6.0.1
* Visualizer version: 3.7.10

**Comment by girishpanchal30** [comment]
As per the google document, vAxis baseline is added automatically with baseline color.
Ref: https://tinyurl.com/2obdtdf5

> Button is not increasing the value

Fixed

Thanks
