### ISSUE TITLE
 Fatal error caused by conflict with TF Random Number Plugin.

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/visualizer#933]
### Description:
The latest version of Visualizer(v3.7.11) is having trouble with the TF random number plugin. If you add a short code of this plugin on your website’s page/post then the page doesn’t get published because of some errors caused by Visualizer.

The log file says the error is because of the Visualizer module on line 804.

I checked the previous version of the visualizer with TF random number plugin and this issue doesn't occur in the last version.

### How to reproduce this issue:

1. Install the latest version of the visualizer and TF random number plugin(https://wordpress.org/plugins/tf-numbers-number-counter-animaton/)
2. Go to the Random Number option in the sidebar and add a sample number.
3. Copy the shortcode of the sample number.
4. Create a New page or post. 
5. Insert the shortcode of the sample number in post.
6. Publish the page/post. 
7. Observe the error.
8. Check the error log file.
9. You will get the following error  :

Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Visualizer_Module::filterChartTitle()

See this screenshot to view the full error:

![bug1](https://user-images.githubusercontent.com/110405452/187746328-f21762da-d808-4d3d-abf8-ca65e26994d1.png)

### Expected behavior:

The visualizer plugin should not interfere with different plugins and there should be no error in the log file.
 
### Current behavior:

The latest version of the visualizer plugin is causing a fatal error if you use the shortcode of the TF random number plugin.

### Reference:
You can use this documentation to learn the basic usage of TF random Number Plugin: http://themeflection.com/docs/tf-numbers/

![Screenshot_1](https://user-images.githubusercontent.com/110405452/187746524-86e54700-7449-45f4-9ab7-5e6082035a1e.png)
![Screenshot_2](https://user-images.githubusercontent.com/110405452/187746560-e0fcab04-a3ee-416c-9619-1b4efbce05e5.png)
![Screenshot_3](https://user-images.githubusercontent.com/110405452/187746584-77b75b82-da4c-4d0b-930d-9dc67992304b.png)

User reported here: https://wordpress.org/support/topic/conflict-with-another-plugin-tf-random-numbers/

### Technical info
* WordPress version: 6.0.2
* Visualizer version: 3.7.11

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/2001063149/335880
