### ISSUE TITLE
Compatibility issue with the Fire Department theme

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/visualizer#935]
### Description:

The latest version of Visualizer is not compatible with the Fire Department theme. 

### How to reproduce:

1. Install and activate the Fire Department theme - zip here

[fire-department.zip](https://github.com/Codeinwp/visualizer/files/9498554/fire-department.zip)

2. Create a chart, for example, a Pie Chart.
3. Try to display the chart on a regular page - the page will be white(no chart) with no error in the browser console. This happens with Visualizer version 3.7.11. If you roll back to version 3.7.10, everything works normally.

The PHP error occurring when the chart is not displayed is the following one:

```
Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Visualizer_Module::filterChartTitle(), 1 passed in /s1-controlpatch/wordpress/wp-includes/class-wp-hook.php on line 307 and exactly 2 expected in /s1-controlpatch/wordpress/wp-content/plugins/visualizer/classes/Visualizer/Module.php:804
Stack trace:
#0 /s1-controlpatch/wordpress/wp-includes/class-wp-hook.php(307): Visualizer_Module->filterChartTitle()
#1 /s1-controlpatch/wordpress/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#2 /s1-controlpatch/wordpress/wp-content/themes/fire-department/fw/core/core.wp.php(1468): apply_filters()
#3 /s1-controlpatch/wordpress/wp-content/themes/fire-department/fw/core/core.wp.php(1269): fire_department_get_post_data()
#4 /s1-controlpatch/wordpress/wp-content/themes/fire-department/single.php(16): fire_department_show_post_layout()
#5 /s1-controlpatch/wordpress/wp-includes/template.php(772): require('/s1-controlpatc...')
#6 /s1-controlpatch/wordpress/wp-includes/template.php(716): load_template()
#7 /s1-control in /s1-controlpatch/wordpress/wp-content/plugins/visualizer/classes/Visualizer/Module.php on line 804
```

### Expected behaviour:

![Markup on 2022-09-06 at 18:47:06](https://user-images.githubusercontent.com/26867648/188679387-e132cc52-423e-4083-8f93-de0a13a96e94.png)

### Current behaviour:

![Markup on 2022-09-06 at 18:47:35](https://user-images.githubusercontent.com/26867648/188679404-6508a1af-e512-4d3f-88c7-382147a3cdaa.png)

### Reference:

https://secure.helpscout.net/conversation/2001063149/335880

### Technical info
* WordPress version: 6.0.2
* Plugin version: 3.7.11
* Theme version: 1.9

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu
Mentioned issue is resolved by this PR problem.https://github.com/Codeinwp/visualizer/pull/934. Please check with the #933 issue.
Thanks

**Comment by stefan-cotitosu** [comment]
@girishpanchal30, you are right, the issue I reported is fixed with [this version](https://github.com/Codeinwp/visualizer/pull/934#issuecomment-1234044641) of the plugin.

I didn't realize it's a duplicate, thank you.
