### ISSUE TITLE
We can change copy Short Code icon

### ISSUE THREAD

**Issue by harshitarora-in** [Codeinwp/visualizer#945]
Currently we are using **scissor** icon to copy chart short code, but we can replace it with a more familiar icon.

### Reference: 

Current icon:
![Desktop - 3 (1)](https://user-images.githubusercontent.com/56164789/194761736-ea9df055-2b6a-4715-b4ca-10a7cef0e255.png)

Recommended icon:
![Desktop - 2](https://user-images.githubusercontent.com/56164789/194761646-eafbd58d-03fd-401f-adb7-28632cc5d03f.png)

**Comment by girishpanchal30** [comment]
Hey @harshitarora-in
Could you please provide me new icon? I can not find the icon in the existing ui-icon image.
Ref: https://github.com/Codeinwp/visualizer/blob/master/images/ui-icons.png

Thanks

**Comment by harshitarora-in** [comment]
@girishpanchal30 Here is the Dashicon [link](https://developer.wordpress.org/resource/dashicons/#admin-page)
