### ISSUE TITLE
Fatal appear in the latest version

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#95]
The following appear is appearing when trying to use the latest Visualizer for a lot of people:

`Fatal error: Can't use function return value in write context in /home/content/n3pnexwpnas02_data02/66/3243266/html/wp-content/plugins/intergeo-maps/templates/library/list.php on line 3`

I'm not able to reproduce this but a lot of people have reported it so far, like this: https://secure.helpscout.net/conversation/247226117/0/

**Comment by selul** [comment]
@HardeepAsrani this is related to intergeo
