### ISSUE TITLE
Import from other chart doesn't work in post editor

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#951]
### Description:

When i add a chart inside the post editor and try to import the data from another chart, the block breaks and i'm getting an error in the console https://vertis.d.pr/v/igzhMo
### How to reproduce:

1. Create a chart and add it to a post/page
2. Try to import from other chart

### Expected behaviour:
Importing should work and no error should be visible
### Current behaviour:
The block breaks and i'm getting an error in console
### Reference:

https://vertis.d.pr/v/igzhMo
### Technical info
* WordPress version: 6.0.3
* Visualizer version: 3.8.1
* Visualizer pro version: 1.11.1

**Comment by girishpanchal30** [comment]
Hey @irinelenache,
I can't reproduce this issue in a local system. Can you please share your test instance details here?
Ref: https://www.loom.com/share/4a2e7fdfcbaa4bbe8602b675fc9a948c
**Note: I have tested with the development branch**

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 I tried to replicate it again but i couldn't, maybe it was related to some caching. Thanks for checking, i'll close the issue and will open it again if i'll encounter it in the future 🙏
