### ISSUE TITLE
Visualizer 3.9.0 breaks with Polylang

### ISSUE THREAD

**Issue by todeveni** [Codeinwp/visualizer#960]
### Description:
Visualizer 3.9.0 added WPML support in ad22ce37c74ee712039fad617432aa51b2093d48, which breaks the plugin with Polylang, since Polylang registers `icl_get_languages` function for WPML compatibility.

Maybe some additional checks for `$sitepress` global that it's actually `instanceof SitePress`?

### How to reproduce:
Install Visualizer 3.9.0. Install Polylang.

### Expected behaviour:
Site loads with graphs.

### Current behaviour:
Site doesn't load with graphs. 

```
Call to a member function get_element_trid() on null
errfile:wp-content/plugins/visualizer/classes/Visualizer/Module/Frontend.php
errline:312
```

### Technical info
* WordPress version: 6.0.3
* Plugin version: 3.9.0

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/2064385893/344129/
