### ISSUE TITLE
[Bug] Pro Features Lock Bypass

### ISSUE THREAD

**Issue by 0xshdax** [Codeinwp/visualizer#973]
### Description:
The plugin does not properly lock its Pro features which could allow low users such as contribute to bypass the restriction and use them.

### How to reproduce:
1. Log-In user contribute+
2. Add a new Library (Visualizer > Add New)
3. Choose a library (Example: **Line**)
4. When the next click there is a request like the image below.

![image](https://user-images.githubusercontent.com/29938825/211716678-32abe10d-5e7c-46fb-8aef-f68f7103f79e.png)

5. Change the value in the parameter type to bubble

nonce=65c812e22e&type=**bubble**&chart-library=GoogleCharts

6. If the value has been changed as above, then create a chart.

![image](https://user-images.githubusercontent.com/29938825/211717759-3d26514a-a8f8-4fbc-aa2d-d4060e5acff7.png)

#### Example a post with a shortcode

![image](https://user-images.githubusercontent.com/29938825/211718067-2bce0867-c801-41a0-ae29-11cb142d52a6.png)

![image](https://user-images.githubusercontent.com/29938825/211718089-ef122fc9-3d50-4468-884b-544e90f730b1.png)

### Reference:

https://wpscan.com/vulnerability/60eb1d98-8bf9-495c-bac8-fe46cd9f97df

### Technical info
* WordPress version: 6.1.1
* Plugin version: 3.9.3

**Comment by selul** [comment]
@0xshdax Thanks for reporting, we will look into it.
