### ISSUE TITLE
"custom format" for chart series values is not available in Pie Charts and is not working as expected on Line Charts (Chart.js engine - Visualizer 3.9.2

### ISSUE THREAD

**Issue by javiercardenaswork** [Codeinwp/visualizer#981]
### Description:
Based on the documentation https://docs.themeisle.com/article/672-how-to-format-series-values in order to use "custom format" for chart series values I need to click the "number format" field inside General Settings > Pie Settings. However this option is not present inside the pie chart. 

On the other hand I could find this option on Series charts, but the format is not being applied properly.

### How to reproduce:
1. Create a pie chart with the Chart.js engine on Visualizer 3.9.2
2. Go to General Settings > Pie Settings (You won't see the "number format" option)

![image](https://user-images.githubusercontent.com/87084313/217088283-f09d277a-e32d-4d89-a25f-bab9b26c0fd9.png)

### Expected behaviour:
- I should see the "custom format" field

### Current behaviour:
- "custom format" field is not present

### How to reproduce:
1. Create a line chart with the Chart.js engine on Visualizer 3.9.2
2. Go to General Settings > Series Settings 
3. Set a format, e.g. `$#.#` I should see a number like $1.2

### Expected behaviour:
- Format should work as expected and show a $ before the number

### Current behaviour:
- Number isn't formatted as expected.
![image](https://user-images.githubusercontent.com/87084313/217089120-9ecb97bd-a209-416a-965b-4fa84c1bcd59.png)

### Technical info
WordPress version: 6.1
Plugin version: 3.9.2
Chart.js engine

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius @irinelenache

I've fixed both issues per the user's request, if you find any issues, kindly let me know.

Thanks

**Comment by javiercardenaswork** [comment]
hi guys any plans of including this fix on the new release?

**Comment by vytisbulkevicius** [comment]
Hi @javiercardenaswork,

Thank you for the follow-up. We will make a release with it addressed this week.

**Comment by Fran-AllanSolutions** [comment]
Hi all, we already are in the latest version and as you can see below the formatting is not working as expected. Is there something I'm missing?

# Data
![image](https://github.com/Codeinwp/visualizer/assets/107567703/a4186f4a-8f52-40fb-adc0-5bc0cbd50a68)

## Examples
![image](https://github.com/Codeinwp/visualizer/assets/107567703/47ec75d4-4433-4884-aead-75c673d4306e)
![image](https://github.com/Codeinwp/visualizer/assets/107567703/fb427a47-d672-4ec2-b6fe-ae7dad25222c)
![image](https://github.com/Codeinwp/visualizer/assets/107567703/50161dcc-ce22-4458-9a12-bd28dbd74c3f)
![image](https://github.com/Codeinwp/visualizer/assets/107567703/3ad12a0b-090c-4d87-948d-b5203d06a37e)
