### ISSUE TITLE
Compatibility conflict with plugin "Front End Users" (not possible to activate Visualizer)

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#983]
### Description

It's not possible to activate Visualizer plugin if you also have plugin "Front End Users" installed as it's causing a fatal error:
`Fatal error:  Cannot redeclare Matrix\adjoint() (previously declared in /visualizer/vendor/markbaker/matrix/classes/src/Functions/adjoint.php:20) in /front-end-only-users/PHPSpreadsheet/vendor/markbaker/matrix/classes/src/functions/adjoint.php on line 20`

Plugin - https://wordpress.org/plugins/front-end-only-users/

Reported by the client here - https://secure.helpscout.net/conversation/2155879197/356976

### Step-by-step reproduction instructions

1. Install the plugin mentioned above, "Front End Users"
2. Try installing Visualizer plugin - the error will appear

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/36594177/220314205-3ffe1e0c-06eb-444e-87aa-4dfeafc6f348.png">

### Environment info

https://pastebin.com/CnYvwumL

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've reviewed this issue and it seems we can't fix it through the visualizer plugin.
We need to inform below changes in the `Front End Users` plugin so this issue is fixed easily.
Plugin SVN Changes - https://github.com/Codeinwp/visualizer/files/10840372/visualizer.983.txt
cc @selul

Thanks

**Comment by selul** [comment]
@vytisbulkevicius I suggest we can close this for now and open a support request in the plugin wp org page.

**Comment by vytisbulkevicius** [comment]
Sure, informed them here https://wordpress.org/support/topic/compatibility-with-visualizer-plugin/#new-topic-0 and will follow the thread if they have any requests for us.
