### ISSUE TITLE
Empty charts

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/visualizer#997]
### Description

A lot of users reported today that their charts don't appear anymore. In most cases, the axis are displayed, but the data and the graphs themselves are not. I was able to replicate this on my instance with no other plugins active and the Twenty Twenty theme. In the dashboard, a horizontal line appears on the chart and nothing appears on the front end. No error is thrown in the console and rolling back the plugin doesn't seem to solve the issue. I tried to downgrade WP to 6.1 as well but it doesn't help.

### Step-by-step reproduction instructions

1. Create a chart
2. Check how it is displayed in the charts library
3. Add it to a page and check the behaviour on the frontend as well

### Screenshots, screen recording, code snippet or Help Scout ticket

![back](https://user-images.githubusercontent.com/86592341/229725347-a14f5709-0c48-44ef-8558-71fe04edcdcf.JPG)

![front](https://user-images.githubusercontent.com/86592341/229725366-d84c5aba-4d19-4e3b-8087-95d452ab777b.JPG)

https://secure.helpscout.net/conversation/2203670293/364344?folderId=212390
https://secure.helpscout.net/conversation/2203314956/364302?folderId=212390
https://secure.helpscout.net/conversation/2203214822/364285?folderId=212390
https://secure.helpscout.net/conversation/2203257526/364290?folderId=212390
https://secure.helpscout.net/conversation/2203575912/364316?folderId=212385
https://secure.helpscout.net/conversation/2203685603/364347/
https://wordpress.org/support/topic/no-data-but-with-data/#post-16624300
https://secure.helpscout.net/conversation/2203693965/364348?folderId=212390
https://secure.helpscout.net/conversation/2203712319/364359/
https://secure.helpscout.net/conversation/2203737734/364375/
https://secure.helpscout.net/conversation/2203800006/364393/
https://secure.helpscout.net/conversation/2203783258/364389?folderId=931549
https://secure.helpscout.net/conversation/2203956134/364441/
https://secure.helpscout.net/conversation/2204030770/364455/
https://secure.helpscout.net/conversation/2203994805/364450/
https://secure.helpscout.net/conversation/2204049266/364457/
https://secure.helpscout.net/conversation/2204059811/364460/
https://secure.helpscout.net/conversation/2204057068/364459/

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30, please prioritize this one as it affects many users and customers

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've reviewed this issue and found that issue occurs with the latest Google chart JS.
Ref: https://developers.google.com/chart/interactive/docs/release_notes#current:-april-2023

For now, I've set a specific Google chart library version to fix this issue, and I will investigate the compatibility issue with the latest version.

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 tested and couldn't find any issues 👍

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

Checklist issue is fixed in this PR #988
Ref: https://github.com/Codeinwp/visualizer/pull/988/commits/72052afacbb43aa88c468aad5c84a30000fc48b4

Thank
